### ISSUE TITLE
Admin: Simplified editor for the blog / news / events posting

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#1]
In the administration interface for libraries as contributors we need simpler interface.

The librarians are going to be scared by the Wordpress default options.

At least the editor for the textarea of the posts must be simple.

Simple text editing bold / italic / underlined + links + upload of an image and including the image would be better.

---
1. Erfassung von Beiträgen (Blog, News, Event)

Unsere Nutzer dürfen nicht mit den Standard-Tools konfrontiert werden.

![image002](https://f.cloud.github.com/assets/59284/360752/bd67270e-a1a7-11e2-89f2-c2c42082b475.jpg)

Es gibt unter den 20 potentiellen Bloggern vielleicht 3 die damit umgehen können. Die anderen werden einfach nie einen Beitrag schreiben (und das wäre sehr schlecht für das Portal). Der Zugang muss sehr einfach und intuitiv sein. Bei einem Blog muss nur ein minimal formatierter Text (Absätze, ev. spezielles Format für Zitate) sowie ein Bild hochgeladen werden. Das Hochladen des Bildes muss ebenfalls ganz einfach sein (siehe Beispiel auf www.nikibrown.com) Die Metadaten zum Bild und Tags soll nicht der Autor sondern der Administrator vor dem Freischalten dazufügen. Ist es möglich, wie im Beispiel mit vordefinierten Feldern zu arbeiten?

http://www.nikibrown.com/designoblog/2011/07/24/customizing-wordpress-admin-for-clients/

**Comment by JackuB** [comment]
![kp](https://f.cloud.github.com/assets/1788727/405069/b15ce962-a9ae-11e2-8efe-c5820466c4cd.PNG)

Editor window is now greatly simplified

**Comment by klokan** [comment]
Thanks
