### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#10]
The services should look like on this mockup:

![kartenportal-webdesign-v4-services-detail09](https://f.cloud.github.com/assets/59284/405107/3f8d4f32-a9b5-11e2-860c-a9e87468b70e.jpg)

**Comment by klokan** [comment]
The photo should be aligned to red line in the header.

**Comment by JackuB** [comment]
Services page is ready - that map slider at bottom is missing

**Comment by klokan** [comment]
Thank you The map slider at bottom is suppose to be the slider with the five thumbnails of the different services in this case.

**Comment by JackuB** [comment]
Map slider is now on homepage ( http://kartenportal.klokantech.com/ ) and on service detail ( http://kartenportal.klokantech.com/blog/mit-kartenmaterial-arbeiten/ )

**Comment by radimkacer** [comment]
the services page isnt optimized for 1024...  http://kartenportal.klokantech.com/articles/
the right column is below first one...

**Comment by JackuB** [comment]
Services listing media queries has been rewritten - fixed

**Comment by klokan** [comment]
Note: It would be good to make the longer texts slightly shorter, so there is no need to scrolling.
