### ISSUE TITLE
Remove space in title of record 13025472X

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#101]
There is a space in the title of record http://search.kartenportal.ch/#id=13025472X which does not appear in Swissbib and NEBIS.

It should read "Le monde musulman" instead of "Le mond e musulman". Note that the title is correct in both Swissbib and NEBIS since at least 10 January 2013. Therefore check why and how this space has been introduced in Geosearch, or, why the record has not been updated since.

**Comment by klokan** [comment]
Regression bug on #88. Work has started.

**Comment by klokan** [comment]
While testing this we have discovered a new issue with maps covering whole world - which will be fixed soon as well.
