### ISSUE TITLE
Font Size Blog Layout

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#103]
J little change of font size and space. J like the concept, but the font size is for my perception to big. J prefer it like this:

![layout blogpage](https://f.cloud.github.com/assets/4223790/1007432/e12fb6aa-0b07-11e3-9f66-14b08885aa3a.jpg)

**Comment by klokan** [comment]
This is exactly what was scheduled internally - and it will be deployed later today.

**Comment by klokan** [comment]
Done.
