### ISSUE TITLE
Kartenportal.CH logo in vectors and print ready version 

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#104]
The Kartenportal.CH project the logo in Color, BW and Grey variants in vectors. And possibly a short design manual with used color codes and usage instructions.

It is required for the project announcement, PR, presentations and for printing on marketing materials and posters of the project in future.

Formats: Manual in AI and PDF with all logo variants (1 file), each logo in PDF (3 files) and large PNG with transparency (3 files) for the every colour variant.

**Comment by klokan** [comment]
The reqested graphic is in:
https://drive.google.com/folderview?id=0BwUe1kqIRJWSUlpvQlRhR21yTWM&usp=sharing

**Comment by radimkacer** [comment]
DONE
