### ISSUE TITLE
SUSANNE: Translating the administration interface

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#107]
We need ASAP the translated version of the administrative interface for the libraries.
For the german translation of the dashboard see comment at #97.

**Comment by JackuB** [comment]
Dashboard translated
![image](https://f.cloud.github.com/assets/1788727/1044938/5f8ea872-101b-11e3-989f-45510445bef6.png)

**Comment by ethbib-susanne** [comment]
If you are logged in as a library - by selecting the language in the top bar there is no change. The translation should run here too.

We will get the english texts for this section from Susanne.

**Comment by klokan** [comment]
The English texts are in: #162

**Comment by klokan** [comment]
@JackuB This is very urgent - please report on this ticket ASAP.

**Comment by klokan** [comment]
> Where can J translate these terms and texts:

These texts are being injected into admin area, thus they need to be translated separately 
http://www.kartenportal.ch/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php under plugin called "Sweet Custom Dashboard"

> and the menu items on the left:

The menu is defined in "Einstellungen -> Menu editor". These should be natively English, not German.
http://www.kartenportal.ch/wp-admin/options-general.php?page=menu_editor

Then these original English menu items can be translated via: WPML -> String Uebersetzung.
http://www.kartenportal.ch/wp-admin/admin.php?page=wpml-string-translation/menu/string-translation.php

**Comment by klokan** [comment]
@JackuB Can we enforce the switch of the language for translation as well as for content. It did not run for me when the libraries selected that. I mean the language for the names of the fields was different from the gettext language. I guess you will fix this faster then me.

The libraries should be just able to select a single language and automatically see the whole administration as well as the content in the administration in that language.

Susanne can then pre-configure the non-german language via 'admin' account to libraries which are from Italian and French speaking parts of Switzerland.

**Comment by JackuB** [comment]
**WPML language settings** in user profile is now controlling visible content in admin area etc. When language is selected, it'll show content and admin area in this language.

To change this, **you need to login as the library**, and change it in their profile (it have to be done this way, as on the background there are other (nonvisible) options being changed for that library. That's something admin can't do from his profile)

**Comment by klokan** [comment]
This is finished from the technical point of view - but Sussanne still did not make the translation of menus correctly - so I am reopening it - so she can see the links in the list of tickets.
