### ISSUE TITLE
Last small layout modifications homepage

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#108]
Please set 15px (until now 13 px)for the font of the introduction text beneath the search bottom and change the space between button and text to 35px (until now 50px).

![suche-box](https://f.cloud.github.com/assets/4223790/1035041/4ce69dda-0f24-11e3-9573-cc18a4acbfea.jpg)

**Comment by ethbib-susanne** [comment]
Please reduce the distance between the to paragraphs. (This request was already made in a closed ticket)

![abstand](https://f.cloud.github.com/assets/4223790/1035160/2695f926-0f26-11e3-8cfd-8fd142c23b05.jpg)

**Comment by ethbib-susanne** [comment]
Please add a link to the map picture in order to get to the map library search when clicking on the map.

![kartensammung_finden](https://f.cloud.github.com/assets/4223790/1042262/6bbe0fd0-0fe8-11e3-99d8-1234f3e59370.jpg)

**Comment by klokan** [comment]
I have set the map as clickable and switch the whole front page as a translatable template - via GetText.

We need for the front page template the final texts in English.

**Comment by ethbib-susanne** [comment]
The translations are to be finished soon. J will send you the texts in about two days.

**Comment by klokan** [comment]
Two days? Well, the German texts need to be replaced by English (as they were originally) so that they can be translated to other languages. Until then you will see a mixture of English and German on the front page.

**Comment by ethbib-susanne** [comment]
Please set the line pitch to single spacing in this paragraph:

![kartensammlungen](https://f.cloud.github.com/assets/4223790/1125883/c392d2e0-1b19-11e3-954d-92d04a1ae2d4.JPG)

**Comment by ethbib-susanne** [comment]
The Link 'Zum Verzeichnis' should be on a new line.

**Comment by klokan** [comment]
Done
