### ISSUE TITLE
Last small font size and distance modifications

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#109]
Please shorten the distance between title and picture to 40px (until now 55px) for all pages. This request was made before in a closed ticket.

.singlePost h1 {
    margin-top: 40px;

![abstand2](https://f.cloud.github.com/assets/4223790/1035206/0921b3fc-0f27-11e3-8245-e7f2e8156b39.jpg)

**Comment by radimkacer** [comment]
DONE
