### ISSUE TITLE
GeoSearch integration with the web

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#11]
We will host it as static files (HTML,CSS,JS) on URL:

/karten/
/en/maps/
/fr/cartes/

Let's prepare a stub (empty index.html) into GIT and production server.

**Comment by JackuB** [comment]
http://kartenportal.klokantech.com/karten/

http://kartenportal.klokantech.com/en/maps/

**Comment by klokan** [comment]
http://kartenportal.klokantech.com/en/ does not respond correctly - it is probably because of this change.

**Comment by JackuB** [comment]
WordPress/WPML can't handle /en folder - I renamed /en to /geosearch

**Comment by klokan** [comment]
OK. We will use the unique directory names, such as:
http://kartenportal.klokantech.com/karten/
http://kartenportal.klokantech.com/cartes/
http://kartenportal.klokantech.com/geosearch/ (or /maps/)
etc.
