### ISSUE TITLE
Google Maps map extract size and link on libraries detail page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#110]
1. Please make the map extract a bit larger (300x250).
2. The link to Google maps doesn't always produce the requested result. Sometimes there is no result or not relevant results. We can avoid missing or false results by transfering only the street adress, postal code and city name.

Bad Example:
![goolge_link_1](https://f.cloud.github.com/assets/4223790/1043072/b8c42a62-0ff7-11e3-9f9f-a9d1196e0956.jpg)

Work around:
![goolge_link_2](https://f.cloud.github.com/assets/4223790/1043084/da8e212a-0ff7-11e3-953d-24b7e18a17aa.jpg)

**Comment by ethbib-susanne** [comment]
Please translate titles in the libraries detail page.

**Comment by JackuB** [comment]
1, map image is now larger
2, Search term is now only address - without library name
3, Texts now have corrected translation (english strings instead of german strings)

**Comment by ethbib-susanne** [comment]
1. J don't understand why there are english strings on a german webpage. Do J have to translate these texts in the translations interface?

**Comment by klokan** [comment]
Yes - you have to translate English into all other languages.

Please use the translation interface as admin:
http://kartenportal.klokantech.com/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php&type=themes

**Comment by ethbib-susanne** [comment]
Hello Petr

J tried to understand how the translations work. J didn’t succeed. Can you please give a little bit more instructions (screenshots of the admin interface in question) and working steps?

**Comment by ethbib-susanne** [comment]
Is this the interface? And how do J have to proceed?

![translation](https://f.cloud.github.com/assets/4223790/1106975/3fa091e2-1953-11e3-8a1e-f97ad882a414.jpg)

**Comment by klokan** [comment]
Click on Bearbeiten next to Deutch.

**Comment by ethbib-susanne** [comment]
J have done so but J can’t filter the relevant terms. There are 5’900 text strings.

**Comment by klokan** [comment]
You have to open the "Themes" in the blue upper line of links. On the screenshot you have selected "Wordpress".

By clicking on the link which I provided (http://kartenportal.klokantech.com/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php&type=themes) you should have been taken directly into the relevant page - were you not?

**Comment by klokan** [comment]
BTW I still have to fix your hacks where German phrases were put into the source code where belongs only English - I will do it tonight.

**Comment by ethbib-susanne** [comment]
Hello Petr

Thank you – J am at the right place now.  J was irritated by the amount of languages.
