### ISSUE TITLE
Colour of search result

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#112]
From the usability point of view, the connection between the highlighted result in the Trefferliste and its footprint on the search map should be improved. In fact, we think that both should be in the same colour. See attached mockup. 

![geosuche](https://f.cloud.github.com/assets/59284/1064770/fac93912-134d-11e3-96fc-a338f7d10e2b.PNG)

**Comment by klokan** [comment]
We need to switch the colours of the rectangles on map only.
The review record is going to be blue, and temporary rectangle red.

**Comment by zb-markus** [comment]
Well, we think that the highlighted record and its footprint rectangle are the most important items for the user, and that these need to be distinct from any other colour used for navigation controls, filters, menues etc. Therefore we prefer to keep the red colour for the rectangle and to change the colour of the highlighted record in the Trefferliste. 

The red in the Trefferliste shown on the mockup needs to be more inviting, probably less yellowish and less strong. It is too glaring now.

**Comment by klokan** [comment]
OK. This is very reasonable. We will make it  - with the same red as the search button on web frontpage and of the line on top of the logo.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
