### ISSUE TITLE
Libraries search - missing libraries

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#114]
There are two libraries that are not displayed when selected:
- Zentral- und Hochschulbibliothek Luzern
- Bibliotheque cantonale jurassienne

**Comment by klokan** [comment]
These libraries are missing latitude and longitude records stored in the WordPress administration - and these values needs to be added via the admin interface by @ethbib-susanne because they were not present in the XLS during the imported XLS provided - the provided excel file is linked from #13

```
<li><a data-lon="" data-lat="" href="http://kartenportal.klokantech.com/library/kart40" target="_blank">Liechtensteinisches Landesarchiv, Vaduz</a></li>
<li><a data-lon="" data-lat="" href="http://kartenportal.klokantech.com/library/kart22" target="_blank">Missionshaus Betlehem, Immensee</a></li>
<li><a data-lon="" data-lat="" href="http://kartenportal.klokantech.com/library/kart21" target="_blank">Stiftsbibliothek Einsiedeln</a></li>
```

**Comment by klokan** [comment]
@ethbib-susanne Is there a reason why these three libraries did not have the lat lon in the provided XLS?

Shall we try to identify these based on the address and fill the data on our side?

**Comment by klokan** [comment]
OK. I see that the reported issue is in fact related yet another problem.

The dead links after click in the list in http://kartenportal.klokantech.com/libraries/ on:
- Zentral- und Hochschulbibliothek Luzern
  http://kartenportal.klokantech.com/library/LUZHB
- Bibliotheque cantonale jurassienne
  http://kartenportal.klokantech.com/library/310480000

**Comment by klokan** [comment]
LUZHB has difference in SwissBib ID as LULES:
http://kartenportal.klokantech.com/library/LULES/

310480000 has difference in SwissBib ID as 310410000:
http://kartenportal.klokantech.com/library/310410000/

We will fix this but to me is completely unclear where this difference of identifiers comes from.

**Comment by JackuB** [comment]
This is weird... anyway, Swissbib ID is now being used for generating links to library detail page...
