### ISSUE TITLE
Distinction between Main and Filters menu

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#116]
We have noted that the Main menu (Home, Search, Libraries, ...) and the Filter menu (Timeline, Attributes, Library) do not separate very well. 

In order to have a better distinction between the two menus, we propose to have the labels in the Filter menu and the Help in the same colour (blue) like their icons. If this is not appropriate because of the overall design principles, we then propose to increase the thickness of the line between the two menus.

**Comment by klokan** [comment]
Well, this is exactly the reason why we were very much in favour of design with dark background in the main website navigation header. To have a better contrast between the two menus. This has been refused - and here comes the reports of issues...
I also hope the reported issue is not related to a wrongly configured monitor which is not displaying the shades of grey correctly.

We are a few days before release and doing only last small changes and fixing bugs at this point on Search. Everything according the Lastenheft has been already implemented.
I am radically against large changes which would involve editing both the web and the search header layouts (fix width and full screen implementation). NO!
It means no change in the thickness of the grey line (which would again break the secondary thick line in the web on top of the sidebar) and no change in the main navigation menu.

A small change which could help against possible confusion - if such has been reported and is major from your point of view - could be either:
1) aligning the main upper navigation menu text to the right on the line of search results block or
2) set the blue colour of the secondary filter menu (but selected item in the navigation menu is blue as well) or
a similar small modification in the filter menu.

Designer is against any changes, but you are the customer.
Order exactly what you want us to do, if you really want a change. We will implement it.

**Comment by zb-markus** [comment]
We have seen test users clicking the wrong menu because both look quite similar. I am not responsible for the upper navigation menu, though. What I therefore did is to propose small modifications in the filter menu or of the thin dividing line. 

We accept that any change of the line thickness is not appropriate. Let us try to set the filter menu to blue instead, accepting that the selected item in the navigation menu is blue as well. I have the impression that two different shades of blue are involved, the blue in the upper navigation menu being lighter than the darker blue of the filter menu icons. If true, that would support our goal to distinct between the two menus.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
