### ISSUE TITLE
Print, share, RSS, ICS

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#117]
Are all these functions implemented?

**Comment by klokan** [comment]
Yes. This should be already implemented, but we will check again. There may be regression with the last changes on the website.

**Comment by JackuB** [comment]
RSS is not working because of lockdown
ICS is working

**Comment by klokan** [comment]
Closing - if there is an report of issue we reopen or create a new ticket where the issue is described.
