### ISSUE TITLE
Susanne: Wrong size of images in map gallery

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#121]
The map gallery contains records which were not made by us with images which were uploaded with a wrong pixel size and are now breaking the design layout on the gallery.

These are:
http://kartenportal.klokantech.com/maps/typometrie/
http://kartenportal.klokantech.com/maps/faksimile/
http://kartenportal.klokantech.com/maps/vogelschaukarte/
http://kartenportal.klokantech.com/maps/atlas/

This can be fixed only by the person who has the original images and it should be done via the administration interface.
@ethbib-susanne?

**Comment by klokan** [comment]
This is a task for Susanne to do.

**Comment by ethbib-susanne** [comment]
J will do this. Can you please give me the exact dimensions (pixel sizes)?

**Comment by klokan** [comment]
I expect 726 x 472 px - same as the images made by the designer.

**Comment by klokan** [comment]
OK. I am closing this ticket - because it is not a job for KlokanTech.
