### ISSUE TITLE
Responsive "Libraries"

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#122]
The http://kartenportal.klokantech.com/libraries/ layout does not behave correctly as responsive.

This should be solved via CSS only. On a small screen and for printing only the list of libraries is displayed and map is hidden. The list should fill the whole screen - gray background texture is replaced by gray color.

There is also a bug in responsive design related to the more design (such as http://kartenportal.klokantech.com/maps/lithografie/ and others) where on the small variant the gray background texture should be removed.

**Comment by JackuB** [comment]
Updated CSS is in github. Some problem occured with git autodeploy.

**Comment by klokan** [comment]
The "Search" button next to the input field is broken now.

**Comment by klokan** [comment]
For 1024px in wide the map should be still available - for example on the iPad. It should switch to the list a bit later, please.

**Comment by JackuB** [comment]
Break is now on 880px
