### ISSUE TITLE
Post-launch tasks

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#124]
These are tasks we need to do after www.kartenportal.ch is switched to the new versions:
- [x] Ensure swissbib.js is regularly updated and accessing live http://www.kartenportal.ch/kartensammlungen/ dynamically every night and refreshes the list of libraries appropriately. Related to #115
- [x] Ensure the links from search.kartenportal.ch top menu are correct. Be aware of '/de/' in URL issue during translation which needs to be fixed properly once we have the final translations.
- [x] Make redirect from http://kartenportal.mapranksearch.com/en/ to http://search.kartenportal.ch/ in order to let users follow old links (comment from zb-markus)
- [x] Redirect "kartenportal.ch" to www.kartenportal.ch.
- [x] Redirect "kartenportal.klokantech.com" to "www.kartenportal.ch" 
- [x] Kartenportal.ch new website send to Google for reindexing - in this moment indexes only the old one

**Comment by klokan** [comment]
All the tasks mentioned above are done.

**Comment by zb-markus** [comment]
Redirects tested and accepted.
