### ISSUE TITLE
Layout Contact page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#125]
The line in the sidebar must be removed. There should be some pixels space at the left and right border of the input fields in the sidebar. Otherwise it looks unfinished.. Then the line below 'Contact' should be closer 'Contact' - this also the blog page (see Issue #98 solution for blog list).  

![kontakt](https://f.cloud.github.com/assets/4223790/1124809/c7f9104c-1b05-11e3-9041-82570aaf3255.jpg)

**Comment by klokan** [comment]
Done according your request.
