### ISSUE TITLE
Bottom menu in French and Italian

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#126]
The Bottom menus in French and Italian are not complete.

**Comment by JackuB** [comment]
Bottom menu can be controlled here: http://kartenportal.klokantech.com/wp-admin/nav-menus.php

I'd add missing links myself, but I don't have translated names for links...

**Comment by ethbib-susanne** [comment]
You can write the names in Englisch. J will translate them later.

Thank you
Susanne

**Comment by klokan** [comment]
Done
