### ISSUE TITLE
Colour of catalog button in Detailansicht

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#129]
After we have changed the colour of the record in the Trefferliste from blue to red (#112), this calls for a colour change within Detailansicht as well: The Catalog buttons should be in the same red instead of orange.

**Comment by ethbib-susanne** [comment]
Please wait with processing this ticket. J first have to discuss the color question with Markus.

**Comment by zb-markus** [comment]
After discussion with Susanne we agreed that the issue is valid and remains to be done. That is: catalog buttons within Detailansicht should be red (same red like in Trefferliste).

**Comment by zb-markus** [comment]
To be clear: This applies only to "normal" catalog buttons, not to the Swissbib metacatalog button.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
