### ISSUE TITLE
Libraries - the database initial data

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#13]
The clear structure (possible fields) in english must be clarified.
The initial data for importing into database of libraries needs to be provided.
Then importing and implementation on the server side (WordPress) is the next step.

**Comment by klokan** [comment]
A sample record originally provided:
https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWSYWxjV2VZS1FxU0E/edit

**Comment by klokan** [comment]
The complete database of all Swiss libraries is available from SwissBib at:

http://www.swissbib.ch/libraries

and downloadable at:

http://www.swissbib.ch/libraries/tpgreen-libraries.xml

The XML file is updated in case there is a change in SwissBib database - we have parsing script and we could probably implement a synchronisation of the two databases.
We have also the old obsolete Kartenportal database:

http://www.kartenportal.ch/kartensammlungen-schweiz.html

From these sources we need a new database presented on the new Kartenportal website, regularly updated and partly editable from the administrative interface by the libraries.

**Comment by ethbib-susanne** [comment]
How will we proceed? Will J complete the data in the kartensammlungen interface. What about the map collections that are not on the swissbib list?

**Comment by klokan** [comment]
I have prepared a convertor from XML to Excel: https://gist.github.com/klokan/e910351681ef52e77f1c

**Comment by klokan** [comment]
There is right now 855 records for libraries in the XML file. I assigned the geographic location based on the address.

The data looks geographically like:
https://www.google.com/fusiontables/data?docid=1Th8vPvvIbv-cXb4TlvrJN1LFfzXw6jgjYMGUSf8#map:id=3
and it can be downloaded as Excel from:
https://docs.google.com/spreadsheet/ccc?key=0AgUe1kqIRJWSdFAycTZWdm5kOTR3OGZrQ0RXd1RmYWc&output=xls

For us the column "name" is the most important, because this is the unique identifier used in the geosearch as well.

Susanne @ethbib-susanne: these data is what we have and what we use in the GeoSearch right now.

The best would be if you prepare an excel spreadsheet with the structure:
First row a header, then one row per map library. The first column will be the "name" identifier, and others the extra fields you want to show for the libraries.

You don't have to repeat the data from this table such as address or url to the website (we can load their new and updated version at anytime), but we need from you all the other data which are missing in the excel above.

Are there really more map libraries then these which you want to have in the database on the website?

What should be the logins for the libraries into the administration? Ideal seems to me the "name" identifier again.

**Comment by ethbib-susanne** [comment]
J sent the list of all map libraries for our directory with the information available so far by e-mail. On Monday J will add more fields.

J suggest to use the e-mail-adress as a login information.

J had to change some information provided by swissbib (blue color name and institution_url fields). Please don’t overwrite this information.

**Comment by klokan** [comment]
The selected SwissBib libraries with additional records from Susanne are in our intranet:
https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWSWjBSbUpmOVNrREU/edit?usp=sharing

The new new fields for the library detail page defined in #19 are not yet available in this file.

**Comment by klokan** [comment]
The final data are going to be provided by Susanne. Some of the fields are empty - they should be filled by the libraries via the Wordpress administration interface.

**Comment by klokan** [comment]
Here is the final file "Daten Verzeichnis Kartensammlung.xls" provided by Susanne:

https://docs.google.com/a/klokantech.com/spreadsheet/ccc?key=0AgUe1kqIRJWSdG00NVUtaVJIQUhZOE9fOHcxdFJUVUE#gid=0

**Comment by klokan** [comment]
@ethbib-susanne Where does the identifiers kart001, kart002 comes from?

**Comment by klokan** [comment]
The identifiers "kart00X" has no meaning - can be removed. Links to GeoSearch in the library detail page should be present only if the identifier is available and not empty.

**Comment by ethbib-susanne** [comment]
Is there a way that the url's are displayed and usable as links?

![urls](https://f.cloud.github.com/assets/4223790/953948/cc85f376-0405-11e3-9afa-2a9d3508198c.jpg)

**Comment by JackuB** [comment]
89 libraries were imported, 2 duplicates

URLs are now clickable http://kartenportal.klokantech.com/library/E01/

**Comment by klokan** [comment]
Please run the import again - as the identifiers visible in the URL use the first column from the spreadsheet. Where is missing identifier use "kart001" and "kart002" etc. The placeholder [text] [url] should be empty texts instead - so that no titles are displayed unless the library provides the data after first login.

How will we pass the passwords for the first login to the institution?

**Comment by JackuB** [comment]
Cleared old data and imported them again...

On launch we'll reset all passwords on kp and send link to all users to create new password.

Empty fields are automatically hidden. If all fields are empty text is displayed instead of empty page.
