### ISSUE TITLE
Links in news and events section on homepage

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#130]
Here there should be a link 'Show all news' that opens all news on the blog page.

![neuigkeiten](https://f.cloud.github.com/assets/4223790/1129268/18d44a1e-1b87-11e3-8c95-418b03146003.jpg)

Here there should be a link 'Show all avents' that opens all events on the blog page. Please only display two events:

![veranstaltungen](https://f.cloud.github.com/assets/4223790/1129273/22eecab0-1b87-11e3-83cb-ea8829c35f74.jpg)

**Comment by ethbib-susanne** [comment]
The link 'Show all events' is instead of the link 'next page'

**Comment by JackuB** [comment]
Done

![image](https://f.cloud.github.com/assets/1788727/1145294/7abba0d4-1e06-11e3-8efd-7912cc69df3d.png)

**Comment by klokan** [comment]
Responsive design is now broken on the front page - the dashed lines are not equally long and on smaller screens the Map libraries do not align to the left.
