### ISSUE TITLE
Width of map selection buttons

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#131]
The width of the map selection buttons needs to be enlarged due to the German language.

With the same, the space between the buttons should also be enlarged, similar to the space between the zoom level controls.

**Comment by zb-markus** [comment]
French and Italian need even more space.

If necessary you may arrange labels on two lines. Example (French version):

Vue
aérienne

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
