### ISSUE TITLE
Upload French and Italian

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#132]
The French and Italian versions have been revised, i.e. cleaned from the worst machine-translated errors. Because both languages are visible in the Geosearch interface, we cannot wait until the official translations are ready.

**Comment by klokan** [comment]
Updated. Links to the main website are broken - Susanne changed all URLs.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
