### ISSUE TITLE
Remove password protection

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#133]
On the 17th of semptember the website will be presented to the ETH library staff in a internal newsletter. There is a link to the new webportal which shouldthen  not be protected by a password anymore.

Please remove password today and confirm the work step by mail. Thank you.

**Comment by ethbib-susanne** [comment]
For the presentation tomorrow J would like to remove test items in the events, news and mapportraits section. Is this ok for you? Or do you still need the items for testing purposes?

**Comment by klokan** [comment]
Password protection removed. Feel free to change the content as you want...

**Comment by ethbib-susanne** [comment]
Hello Petr

What to you mean about changing content? J don’t understand.

Regards
Susanne
