### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#134]
There is a problem with the pointed line in the libraries detail page:

![responsive_design](https://f.cloud.github.com/assets/4223790/1148975/5a0e5da0-1ed2-11e3-98c8-010b687008dd.jpg)

**Comment by JackuB** [comment]
Pointed line is hidden on smaller resolutions.

Also layout of button on smaller resolutions was tweaked.
