### ISSUE TITLE
Calendar on the sidebar issues

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#137]
The calendar does not display correctly the dates form events with the range.

Should always display 'from' date if there is a range.

For events which has just one date it is now correct already.

**Comment by ethbib-susanne** [comment]
Do this at the end and hide the calender until the problem is solved - this is not urgent for me.

**Comment by klokan** [comment]
There are not dates highlighted for the Announcement and Map blog post publishing dates. They were there before... See mockup #64 and the original implementation at: http://kartenportal.klokantech.com/kalender/

**Comment by JackuB** [comment]
Just two notes: 

1, there were always only events in that calendar.

2, Another thing is, this new feature is linked to https://github.com/klokantech/kartenportal-tickets/issues/64#issuecomment-22830632 as there would have to exists some consolidated archive to link each date to...

**Comment by klokan** [comment]
@JackuB Can we add the links to individual posts? This way it was planned from the beginning in mockups and in #64. We don't need links to archive of given day, if there is more then one posts in given date only one will be linked. If there is an event it has priority over another type of date that day. Thank you!

**Comment by klokan** [comment]
Agreed we keep it as it is - just showing the start date of the event.
