### ISSUE TITLE
Click-to-call

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#140]
Do we have the right phone number format to work successfully? 

The actual format is: 044 632 43 84

Maybe we need a format for human reading: +41 (044) 632 43 84
and another one for click-to-call (link behind the human reading format): +44416324384

J forgot to add the Prefix for calls from abroad. I is recommend inserting the phone number in the international format: the plus sign (+), the country code, the local area code, and the local number. We do not really know where our visitors will be located. If they are in the same country, or even in the same local area, the international format will still work.

**Comment by JackuB** [comment]
Phone numbers are wrapped in tel: links (works just like mailto: links for emails)
All phones will pick those numbers.

So if you can add those prefixes (+ or 00) to correct these numbers, it'll be just fine

**Comment by klokan** [comment]
I am closing this ticket. There is nothing more to do on the programming side. The data must be changed in the administration manually, if this change is required.
