### ISSUE TITLE
New and deleted fields 'profile' form

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#142]
The following field was deleted in the 'profile' form and must be deleted in the database and the library detail page layout:

kartenportal

The following four fields are new in the 'profile' form and must be added to the library detail page layout:

vorbestellungen
karten_online_url_2
publikation_3
publikation_3_url

Important: There are some changed lables but no changed names of existing fields.

**Comment by JackuB** [comment]
What is english translation of vorbestellungen? I need it to add to theme.

Rest of fields were added.

And if you deleted "Kartenportal" field (or any other) in [fields editor](http://kartenportal.klokantech.com/wp-admin/edit.php?post_type=acf) it was also deleted from database.

**Comment by klokan** [comment]
I would say "preorders".

**Comment by ethbib-susanne** [comment]
The name is ‚reservations‘.

**Comment by ethbib-susanne** [comment]
And if you deleted "Kartenportal" field (or any other) in fields editorhttp://kartenportal.klokantech.com/wp-admin/edit.php?post_type=acf it was also deleted from database.

> > Thank you for the information. J realized that. We don’t need that information anymore.

**Comment by JackuB** [comment]
"Reservations" is now visible on authors page
