### ISSUE TITLE
Picture upload problem

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#143]
When J login with the libraries login J can't upload pictures.

![fehlermeldung](https://f.cloud.github.com/assets/4223790/1167165/cf0e889c-2089-11e3-9e50-b7b92856e12c.jpg)

**Comment by klokan** [comment]
It seems you have ordered this in #113

**Comment by JackuB** [comment]
So question now is: _should libraries be able to upload images_? If so, we can revert #113 (that button is needed for upload to work) - all posts are reviewed anyway, so it shouldn't create any issues.

I can see how libraries'd like to upload e.g. poster to event etc.

**Comment by klokan** [comment]
Yes, they shoul be able to upload an image.

On Saturday, September 21, 2013, Jakub Mikulas wrote:

> So question now is: _should libraries be able to upload images_? If so,
> we can revert #113https://github.com/klokantech/kartenportal-tickets/issues/113(that button is needed for upload to work) - all posts are reviewed anyway,
> so it shouldn't create any issues.
> 
> I can see how libraries'd like to upload e.g. poster to event etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/klokantech/kartenportal-tickets/issues/143#issuecomment-24857349
> .

## 

Petr Pridal
(managing director)

Klokan Technologies GmbH
Bahnhofstrasse 9, Baar 6340, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by JackuB** [comment]
Image upload is now working again

**Comment by ethbib-susanne** [comment]
Yes they have to, but they should use only the button ‚Beitragsbild festlegen‘. J described the work flow on the Instructions for map libraries page in the Anleitung für das Hochladen von Bildern section.

In the beginning there was a second button for introducing pictures in the text, which had to be removed.

Von: Jakub Mikulas [mailto:notifications@github.com]
Gesendet: Samstag, 21. September 2013 08:53
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Picture upload problem (#143)

So question now is: should libraries be able to upload images? If so, we can revert #113https://github.com/klokantech/kartenportal-tickets/issues/113 (that button is needed for upload to work) - all posts are reviewed anyway, so it shouldn't create any issues.

I can see how libraries'd like to upload e.g. poster to event etc.
