### ISSUE TITLE
Update German and English (corrected)

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#144]
Please upload the revised German and English (corrected) versions.

**Comment by klokan** [comment]
Updated. Links to the main website are broken - Susanne changed all URLs.

**Comment by zb-markus** [comment]
Please upload German and English (corrected) again. I revised the text considering to your comment in #145.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted. For any future language upload we will open a separate ticket.
