### ISSUE TITLE
Layout of attributes window

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#145]
After updating the languages (#132, #144) the layout of the attributes window is corrupted. This was probably caused due to text that no longer fits in the space allocated. The window should therefore have more width.

When necessary, you may arrange labels on two lines. Example:

Full text
search:

instead of

Full text search:

**Comment by klokan** [comment]
Is the "search" word required? I would suggest removing it and keep just "Full text:".

It is unsystematically repeated at some of the attributes only - and it is quite useless to have it on all attributes. Please comment.

**Comment by klokan** [comment]
Done and deployed.
