### ISSUE TITLE
Layout of Filter menu

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#146]
Due to longer labels in French and Italian versions, the layout of the Filter menu is corrupted. Longer labels are not fully displayed now.

You may arrange longer labels on two lines. Example (French):

Liston de
temps

**Comment by klokan** [comment]
We will fix it in the code, but I think it will not look nice. Isn't there a shorter version, such as "Chronologie"?

**Comment by zb-markus** [comment]
To be sure we have to wait to the official French translations. The current "Liston de temps" is the word-for-word translation, so it may change. But there is not much hope that the official translator finds a shorter expression. "Chronologie" is something else and cannot be used here, I am afraid. Therefore it is wise to prepare a flexible layout that allows longer expressions (or at least allows for labels on two lines).

**Comment by klokan** [comment]
OK. The layout is flexible already in our internal system.
I am making last small changes and will deploy all the modifications very soon.

**Comment by klokan** [comment]
Deployed - we are fixing the alignment of "x Label" tags now.

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
