### ISSUE TITLE
Admin interface - Display of values for name in menu 'benutzer'

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#147]
Please display names of the map libraries in the following interface:

![benutzer](https://f.cloud.github.com/assets/4223790/1179457/1e36a444-21d5-11e3-8932-97b9aadb4c95.jpg)

**Comment by JackuB** [comment]
Field is there - but it cannot be searched/filtered in admin area (I don't think WP have such API to search user fields)

![snimek obrazovky 2013-09-21 v10 54 16](https://f.cloud.github.com/assets/1788727/1185328/927b0bb2-229b-11e3-8367-408ee9c88793.png)

**Comment by klokan** [comment]
I expect Susanne wanted to have in the Name column visible the "ETH Zurich".

**Comment by ethbib-susanne** [comment]
Sorry, J didn’t see the column before.
