### ISSUE TITLE
Broken links in top navigation menu

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#148]
Links in top navigation menu are broken due to a new structure of the main Kartenportal web site (it seems). Please implement the new URLs in close collaboration with Susanne.

**Comment by klokan** [comment]
Done and deployed (now to temporary kartenportal.klokantech.com domain - but in the system prepared for www.kartenportal.ch).

**Comment by zb-markus** [comment]
Tested (for kartenportal.klokantech.com) and accepted.
