### ISSUE TITLE
Library links from Detailansicht to library directory

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#149]
Following the new structure introduced by Susanne on 19 September, the URLs behind the library buttons in the Detailansicht need to be refined. They should also be language specific, i.e. when the user is in the French Geosearch, the library button should link to the French version of the Kartenportal library directory.

German http://www.kartenportal.ch/kartensammlungen/.../
English http://www.kartenportal.ch/en/map-collections/.../
French http://www.kartenportal.ch/fr/library/.../   **
Italian http://www.kartenportal.ch/it/collezioni-di-carte/.../

*\* although 'library' is not correct in French, I do hope that Susanne does not change the URL again

**Comment by klokan** [comment]
We indeed plan to fix the links, but we need the really final ones which are not going to be changed anymore.

@ethbib-susanne - please ensure the links are tonight (Friday) final.

**Comment by ethbib-susanne** [comment]
J go home now and there will be no more tickets ☺

**Comment by klokan** [comment]
The URLs are with /en/library/XXX etc - because WordPress can't localize the iteration pages easily. The links runs.
Done and deployed.

**Comment by zb-markus** [comment]
Tested (for domain kartenportal.klokantech.com) and accepted.
