### ISSUE TITLE
Calendar page

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#15]
Now we have the calendar with events at:
http://kartenportal.klokantech.com/kalender/

It is not clear how to make the design - full width?, upcoming events on the side?

How to make linking to this page - should it be also in the blog side bar?

**Comment by ethbib-susanne** [comment]
J suggest that there is no seperate calender page. Events are listed od the blog page. Events can be displayed using a filter. If somebody clicks on an event on the frontpage this filter is set on the blog page and only events are displayed. The calender is displayed in the blog side bar. If somebody clicks on a date in the calender only events are displayed.

**Comment by klokan** [comment]
Let's put a small calendar in the side bar of every blog page.

This small calendar should mix both days of upcoming events and days of the published blog post.
Let's mark days with blog posts as links (the day number has a color) and the upcoming events as links with coloured background and white font (inverse marking to blog post days).

Next to that the /blog/ allows filtering of the events only - which gives the list. This list would be probably sorted by default by the post date - we may need an option to chronologically sort by the event date.

**Comment by klokan** [comment]
This is beeing implemented as part of #64

**Comment by JackuB** [comment]
I reworked calendar logic to be compatible with WPML and duplicated posts.

Event datetime now correctly copy itself and activate across languages.

Links generated in calendar has also been reworked -> they now links directly to event

Can be closed

**Comment by klokan** [comment]
There is a missing link to ICS (and RSS) feeds.

**Comment by JackuB** [comment]
ICS and RSS were part of #64 

Added

Not working (with Google Cal) for now, because of robots.txt, but events are there (including different versions for different languages)

**Comment by klokan** [comment]
TODO: Google Cal support?

**Comment by JackuB** [comment]
I removed Disallow \* from robots.txt for a second and Google Cal worked fine.
