### ISSUE TITLE
Missing news article on library detail page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#152]
There should be an news article on the detail page of ETH Bibliothek.

**Comment by JackuB** [comment]
Solved. Anouncements are now being shown http://kartenportal.klokantech.com/library/E01/

**Comment by ethbib-susanne** [comment]
J just noticed that the text being shown on http://kartenportal.klokantech.com/library/E01/ ends very abruptly. We shold leave out the start of text und just display title and date of the news article or make the text a bit longer and place a link 'more' ('Weiterlesen') at the end.

**Comment by JackuB** [comment]
I left only date, so it'd look like events above

![image](https://f.cloud.github.com/assets/1788727/1258445/f188149e-2bbd-11e3-89d8-ed7c1e57c8b9.png)
