### ISSUE TITLE
Publications link on library detail page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#153]
This is a new specification and can be charged. Please let me know how many hours of work this will take.

We would like to have following solution:

![publications](https://f.cloud.github.com/assets/4223790/1182674/ee15977a-221f-11e3-9e3d-ae43237766ee.jpg)

Instead of:

![publications_old](https://f.cloud.github.com/assets/4223790/1182680/02ec8c58-2220-11e3-894f-697a5b6a4f35.jpg)

**Comment by JackuB** [comment]
Done.
