### ISSUE TITLE
Expired event notes on front page and blog page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#154]
J discussed the topic with Markus and he also thinks that there should be no expired event notes on the front page and the blog page. This means that expired events must be deleted automatically. 

What can we do on the front page?  J suggest to introduce a static text that is not to short. It is not nice but it will not be often that there is one or no events:

![no_events](https://f.cloud.github.com/assets/4223790/1182827/3143143e-2223-11e3-8c87-52c5012c62b0.jpg)

**Comment by klokan** [comment]
We need a definitive text in English - which will become part of the template and can be translated to other languages.

**Comment by ethbib-susanne** [comment]
J will send you the text this afternoon.

**Comment by JackuB** [comment]
> This means that expired events must be deleted automatically.

So you want to delete event from system? Even if this would mean that links to event page would return 404 error as event won't be visible anymore?

**Comment by klokan** [comment]
No! The deprecated events should just not be displayed on the front page.

**Comment by ethbib-susanne** [comment]
They must be deleted completely.

---

Von: Petr Pridal [notifications@github.com]
Gesendet: Dienstag, 24. September 2013 21:49
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Expired event notes on front page and blog page (#154)

No! The deprecated events should just not be displayed on the front page.

—
Reply to this email directly or view it on GitHubhttps://github.com/klokantech/kartenportal-tickets/issues/154#issuecomment-25036619.

Sendenhttps://mail.ethz.ch/owa/?ae=Item&t=IPM.Note&id=RgAAAABrwb38CyE5RqBKNLb6%2b%2fgrBwCk6XpZm1LfQ6tz0QDOM7ILAAAAS09ZAAAWipoP0juCQ43Io0CuM7U%2bAAAJupCyAAAJ&a=Reply&cb=0&pspid=_1380054012895_633964650#

**Comment by JackuB** [comment]
Final word then?

I personally vote for letting events stay (maybe only hiding past ones on front page) - website won't look empty and like it was launched yesterday (archives/old posts on websites are building credibility) and it'll prevent [link rot](http://en.wikipedia.org/wiki/Link_rot)

**Comment by klokan** [comment]
@ethbib-susanne Your final word?

We are strongly against deleting records - it is a very bad idea - because of the mentioned reasons.

Let us know whether you really want to delete the whole history of events automatically instead of just not showing the expired records on the front page.

**Comment by klokan** [comment]
@ethbib-susanne We still need the final English texts you want to include instead of the empty space.

**Comment by klokan** [comment]
@ethbib-susanne Reminder for your feedback.

**Comment by ethbib-susanne** [comment]
This is the text:

There are currently no events scheduled. Please check back later for more events.

**Comment by JackuB** [comment]
Added

**Comment by klokan** [comment]
@JackuB - the two events which are now given on the website are not yet expired - because first ends on October 23 and second even in 2014.

I expect we should display on the frontpage the date (or range of dates) the same way as in the blog post, but it has never been formally specified.
