### ISSUE TITLE
Adjust blue flags in Timeline filter

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#156]
The labels that appear within the blue flags in the Timeline filter are different in length in the four languages, e.g. beginnings (English), Anfänge (German) etc. Can the two flags adjust their width dynamically like the map selection buttons? 

If this is not sensible, at least the left flag needs to be adjusted because the correct English term is not "past" but "Beginnings" (if we would keep "past" then its German equivalent would be the even longer "Vergangenheit").

**Comment by klokan** [comment]
It is very complicated to make these dynamically sized in the code and once it is done it will look ugly probably.
If the box space is really dynamic - it is strange once you start to drag and there is a year inside - with four digits on the left as well as on the right but in two differently sized boxes.

The translation does not have to be exactly the same in all languages at all.

You can just easily choose a short word, such as equivalents from "old" to "new", and from "past" to "now", from "beginnings" to "today", etc. It does not make any difference to the user.

**Comment by klokan** [comment]
To be discussed tomorrow.

**Comment by zb-markus** [comment]
Tested and accepted.
