### ISSUE TITLE
Google translation toolkit availability

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#157]
Google's translator toolkit says that user kartenportal is not allowed to use it:

"We're sorry, kartenportal@gmail.com does not have permission to access this translation.You are signed in as kartenportal@gmail.com, but that email address doesn't have permission to access this translation."

Please make the language toolkit available again. We have still to insert the official French and Italian versions and occasional minor corrections in English and German.

**Comment by klokan** [comment]
Because of the changes in URLs Susanne introduced we had to regenerate all translation files from ground up.

I will provide you with the new links to access the new files. For now I removed the old ones, because modifications in the old would not merge to the new ones.

**Comment by klokan** [comment]
Done - an email with links have been submitted to kartenportal@gmail.com. This is the version where final edits can be done.
