### ISSUE TITLE
Front page - click on the map of switzerland

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#160]
... should go to the translated map collections in correct language.

The link is now wrong /libraries/

**Comment by ethbib-susanne** [comment]
The English translation for the Link 'Im Verzeichnis suchen' ist 'Search the collection index'

**Comment by klokan** [comment]
Fixed link: the URL "/en/map-collections/" is a phrase which is translated into other languages. Changes of the URLs could break this again in the future.

The English source text "Search the collection index" added.
