### ISSUE TITLE
Welcome text in English in libraries cms interface

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#162]
Text beginning

All the key information on your map collection can be recorded and updated on the Profile page or your password changed. The new or amended information will immediately be published in the map collection index. 

Instructions and tips for writing articles and publishing events are available here. 

end Text

'here' ist the link to the instructions page, 'Profile page' is a link to the profile section.

**Comment by klokan** [comment]
Application of these texts is being tracked under #107
