### ISSUE TITLE
SUSANNE: Translating texts in dropdown lists (included in specifications)

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#165]
Currently the texts of the dropdown lists are shown in the authors language for all languages. The same is for the fields containing free text. There is presumably not a way to translate the fields containing free text, but we could translate the texts out of drop down lists. Therefore English is used for the texts on seccond place in the drop down configuration interface. The English text can then be translated in the localistation interface. Shall J prepare all dropdown lists accordingly?

 : 
Senza prenotazione : Senza prenotazione
Solo con prenotazione : Solo con prenotazione
Prenotazione desiderata : Prenotazione desiderata

 : 
Senza prenotazione : Without notification
Solo con prenotazione : Only after notification
Prenotazione desiderata : Notification welcome

**Comment by JackuB** [comment]
I found a solution
![image](https://f.cloud.github.com/assets/1788727/1249148/b5cf2610-2ada-11e3-998d-c4ce276ef185.png)

_Trick_ is to have same unified name for each select option. I added code that pull correct field label.
http://kartenportal.klokantech.com/library/E01/

---

Also note, that when you change field name (field name should follow same pattern as in image above, field label (after ':') can have any name), you'll lose all select fields you filled before, and you'll have to set them again for each library.

**Comment by ethbib-susanne** [comment]
Good solution!
The same must be implemented for fields 'Type of catalog' and 'Reservations'.

**Comment by ethbib-susanne** [comment]
Please reopen this ticket and see comment above. J prepared the two dropdown lists according to the first dropdown list which is already implemented correctly:

Example:
online_catalogue : Online-Katalog
local_electronic_catalogue : Lokaler elektronischer Katalog
slip_or_lists : Zettel oder Listen

**Comment by klokan** [comment]
Editing is possible via Custom Fields -> Custom Fields. Switching of languages as always on the right with pencil symbol - you have used that for translations already. Here is a screenshot:

![screen shot 2013-10-09 at 9 58 24 pm](https://f.cloud.github.com/assets/59284/1301123/70abc0ae-311d-11e3-93bf-1dd05402ad12.png)

As noted above: DO NOT CHANGE THE FIELD NAMES, just the labels after ":".

This ticket has been closed because the problem is technically solved with a description of what is necessary to do with the translations with the admin account. All the translations were not provided in this ticket, so we could not include them ourselves. What can we do more?

**Comment by ethbib-susanne** [comment]
Please contact Radim for this question. He might know how to proceed. On my side everything is prepared.

**Comment by klokan** [comment]
Susanne, either fill your prepared text with translated choices into "Choices" field as described (12 days ago) and as visible in the screenshot above (3 days ago), or provide us with the translated texts which should be used and we will include them in the administration interface for you.

It is clear how to proceed.

**Comment by ethbib-susanne** [comment]
No. J don't know how to proceed.

**Comment by klokan** [comment]
Report from the meeting:

Translations finished by Susanne.

On the page: http://www.kartenportal.ch/library/E01/

The two fields: 'Type of catalog' and 'Reservations' are not displayed at all.

**Comment by ethbib-susanne** [comment]
THIS IS VERY URGENT. Map libraries will be confused when they fill in information to the directory that is not displayed for the public. Please confirm date of completion.

**Comment by klokan** [comment]
It is going to be fixed today - to be ready for tomorrow's meeting of libraries.

**Comment by JackuB** [comment]
It looks like it works correctly:

Select fields were empty, so no info was showing in library profile
![image](https://f.cloud.github.com/assets/1788727/1420360/db8e2e64-3fde-11e3-9142-d5ab0546b4b1.png)

When I selected any option, it showed up on website
![image](https://f.cloud.github.com/assets/1788727/1420382/2d6c1624-3fdf-11e3-80ce-ab792ae951a8.png)

Could you test it?

**Comment by ethbib-susanne** [comment]
Hello Jakub

Yes, it works.

Regards
Susanne
