### ISSUE TITLE
Translating login screen and admin interface

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#169]
J write a new ticket because the old one #107 was very long:
1. Where do J translate these texts?

![login screen](https://f.cloud.github.com/assets/4223790/1281466/d54ab1a2-2f63-11e3-87a0-eb3def357ff3.gif)
1. J translated the welcome texts in the CMS interface for map libraries. They are not displayed in French when J change the language setting of ETH-Bibliothek as a test to French (J logged in with the ETH-Bibliothek login - which is important if J unterstand Radims comment).

**Comment by JackuB** [comment]
1. I'm not aware of any way to translate wp-login page. It was announced as future feature in WPML, which we are using for translation, but it's still not part of current release
2. dashboard is currently loading translations correctly

**Comment by JackuB** [comment]
Scratch that, they actually added it, but changed proposed behaviour and didn't mention that in changelog.
Login form is now translated to language from which you are clicking "Login" in footer

**Comment by klokan** [comment]
The link to "Login" on non-german sites is dead.
