### ISSUE TITLE
Rights for map libraries

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#170]
There was a recent change. Libraries can't modify or delete articles anymore. The should have the rights to do so (the changes are reviewed by the admin later)

**Comment by ethbib-susanne** [comment]
Please close all tickets related to cms interface of map libraries until Wednesday Oct 11 (tomorrow). Libraries will have to complete their profiles starting on Tuesday.

**Comment by JackuB** [comment]
Libraries permissions were widened, they can edit/delete already published posts/pages
