### ISSUE TITLE
Workflow for integrating new swissbib libraries in directory

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#172]
How is the workflow for integrating new libraries when they are swissbib members?

**Comment by JackuB** [comment]
You can add users under [Users > Add new](http://kartenportal.klokantech.com/wp-admin/user-new.php) - whatever you put as "Last name" will be visible on site.

You can edit these users same way as others.

User level should always be library and you can choose whether you'll send user new password in mail.

**Comment by ethbib-susanne** [comment]
How are swissbib members connected tot he map search. Is it sufficient to fill in the swissbib ID in the profile section? Will this library have the “Search maps of this library” on the library’s page?

**Comment by ethbib-susanne** [comment]
J made a test. It doesn't work. Please check. (Unfortunately J put the name instead of an ID. J will have to to a new one.)

You didn't answer all questions:
How are swissbib members connected tot he map search. Is it sufficient to fill in the swissbib ID in the profile section? Will this library have the “Search maps of this library” on the library’s page?

**Comment by klokan** [comment]
The ID should be equal to SwissBib ID.

The link "Search maps of this library" should appear in the library detail page always if the SwissBib ID field is not empty.

The links back from geosearch to the library detail pages are made by scanning the website. It is invoked manually, but it should be automated and is marked in the #124 Post-launch tasks as TODO after the web is on the final domain.

**Comment by ethbib-susanne** [comment]
How do J find out the swissbib ID of a library that is member of swissbib.

**Comment by klokan** [comment]
The complete database of all Swiss libraries is available from SwissBib at:

http://www.swissbib.ch/libraries

(information copied from ticket #13 Libraries - the database initial data)

Now you can see the SwissBib ID in the Kartenportal Search as well - if you filter to the particular library it is visible in the URL as: &libraries=E01
