### ISSUE TITLE
Go online Wednesday Oct 9th 16:00

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#173]
The important tickets (those related to the cms interface for map libraries) will hopefully be closed tomorrow afternoon.

So we should go online tomorrow Wednesday Oct 9th 16:00. 

Please confirm.

**Comment by ethbib-susanne** [comment]
PLEASE CONFIRM. I am on holiday from tomorrow until Oct. 20th.

**Comment by klokan** [comment]
Discussed over email.
