### ISSUE TITLE
Tracking code for website evaluation

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#175]
Please insert this code in pages:

Startseite
Kartensuche
Sammlungen
Angebote
Blog
Kontakt
Über Kartenportal.CH
Impressum
Login

Guten Tag Frau Zollinger

Wie von Herrn Semar angekündigt, sende ich Ihnen nachfolgend den HTML-Code, den Sie bitte ähnlich wie beim Google-Analytics-Code idealerweise irgendwo zwischen den <head></head>-Tags Ihres Webauftritts platzieren.

Vielen Dank für Ihre Mithilfe!
Bei Fragen stehe ich Ihnen gerne zur Verfügung.

Freundliche Grüsse
Sascha Beck

```

<!-- begin swissmetrix -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://www.swissmetrix.ch/analytics/";
    _paq.push(["setTrackerUrl", u+"smx.php"]);
    _paq.push(["setSiteId", "12"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"smx.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!—end swissmetrix -->

```

**Comment by ethbib-susanne** [comment]
This ticket is also urgent.

**Comment by klokan** [comment]
We have to add it to Kartensuche as well. This is TODO for @klokan

**Comment by klokan** [comment]
Finished and deployed.
