### ISSUE TITLE
Front page: event formatting

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#176]
Only the start date and end of the event (without place, type, etc.).
e.g.

`Juni 10, 2013 bis February 23 2014`

**Comment by klokan** [comment]
The translation of the second month does not run - it is always in English - everywhere.

For the front page, please hide the time always - people can see the exact time after they click on the event.

**Comment by JackuB** [comment]
Done. Changed date() to date_i18n().

**Comment by klokan** [comment]
Missing requested hiding of the time on the front page.
