### ISSUE TITLE
URL to ICS calendar not correct for German and Italian + Google Calendar

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#177]
The URL under ICS link shows for german:

"webcal://www.kartenportal.c/feed/eo-events/"

wrong domain ".ch"

and for italian:

"webcal://www.kartenportal.ch/i/feed/eo-events/"

wrong 'it'.

Please check Google Calendar functionality (robots.txt)

**Comment by JackuB** [comment]
Fixed
