### ISSUE TITLE
Wordpress installation protocol + backup description + source code on USB

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#181]
For the Kartenportal WordPress website prepare basic documentation (Installation protocol - in KlokanTech Intranet - describe:
- the list of plugins
- system of automatic backup
- process for restoring the backup in case of hardware failure or move to a new hosting.

**Comment by JackuB** [comment]
I've added BackWPup plugin http://www.kartenportal.ch/wp-admin/admin.php?page=backwpupeditjob&tab=job&jobid=1&_wpnonce=81f9cfcf8f

I setup daily backup to folder. It can also do full backups to different FTP/dropbox etc.

Backup contains list of plugins, db dump and all files.

**Comment by klokan** [comment]
Wordpress upgraded to 3.9.1
New USB contains the backup from today and the installation protocol.
