### ISSUE TITLE
Password reset email to libraries

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#182]
The message is now:

```
Subject: Password reset for www.kartenportal.ch

We have had to reset your password on www.kartenportal.ch.

Your username is still E01, but your new password is Ada#d323.
Thanks.
```

We will need to change it according Susanne instructions.

**Comment by ethbib-susanne** [comment]
Text of the email which is going to be submitted to libraries

Email Betreff (Subject): Login und Passwort Kartenportal.CH

Sehr geehrte Damen und Herren

Ab sofort haben Sie die Gelegenheit, das Profil Ihrer Sammlung im Verzeichnis der Kartensammlungen des Fachportals fur Karten der Elektronischen Bibliothek Schweiz anzupassen sowie Veranstaltungshinweise und Neuigkeiten aus Ihrer Sammlung zu publizieren. Mehr Informationen erhalten Sie in einer separaten Mail.

Internet-Adresse Portal: www.kartenportal.ch

Ihre Login auf Kartenportal.CH ist XY.
Alternativ kann mit der im Profil eingetragenen E-Mail Adresse eingeloggt werden.

Ihr Passwort auf Kartenportal.CH ist XY.
Das Passwort kann im Profil angepasst werden.

Bei Fragen wenden Sie sich bitte an mich. Sie erreichen mich von Montag bis Freitag.

Susanne Zollinger
ETH-Bibliothek, Rara und Karten
Raemistrasse 101, 8092 Zürich 
Tel. +41 44 632 43 84
susanne.zollinger@library.ethz.ch
http://www.library.ethz.ch/de/Ressourcen/Geodaten-Karten

**Comment by ethbib-susanne** [comment]
J can't send an English text to Swiss libraries. Instead J removed all mutated vowels (Umlaute).

**Comment by ethbib-susanne** [comment]
Are you ready to reset the passwort this afternoon after my advice?

**Comment by klokan** [comment]
The message has been updated. We will send your library (E01) the test reset message - so you can verify if everything is the way you wanted.

Then, please let us know when we should send it to all libraries.

**Comment by JackuB** [comment]
![image](https://f.cloud.github.com/assets/1788727/1467935/6e4597fa-458a-11e3-8bda-771a0a4ebb69.png)

Password reset email is ready and tested.

**Comment by ethbib-susanne** [comment]
Der Test hat funktioniert, ich habe allerdings im Text noch einen inhaltlichen Fehler gemacht.

Falsch: "Bei Fragen wenden Sie sich bitte an mich. Sie erreichen mich von Montag bis Freitag."
Richtig: "Bei Fragen wenden Sie sich bitte an mich. Sie erreichen mich jeweils von Montag bis Mittwoch."

Bitte diesen Satz noch korrigieren. Danke! 

Ist es möglich die Passwort Reset Mail heute nachmittag um 16 Uhr zu verschicken?

**Comment by klokan** [comment]
OK. We will send it today at 16:00.

**Comment by klokan** [comment]
The email has been submitted.

**Comment by ethbib-susanne** [comment]
Perfect! Thank you.

Von: Petr Pridal [mailto:notifications@github.com]
Gesendet: Dienstag, 5. November 2013 16:10
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Password reset email to libraries (#182)

The email has been submitted.
