### ISSUE TITLE
Inserting Google Analytics Code

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#185]
Please insert Google Analytics Code to the pages in the four different languages. Note the hours of work. There will be some minor works in the post project phase that will be payed extra-contractual. 

http://www.kartenportal.ch/
http://suche.kartenportal.ch
Sammlungen http://www.kartenportal.ch/kartensammlungen/
http://www.kartenportal.ch/angebote/
http://www.kartenportal.ch/blog/
http://www.kartenportal.ch/blog/announcements/
http://www.kartenportal.ch/blog/event/
http://www.kartenportal.ch/blog/maps/
http://www.kartenportal.ch/uber-kartenportal
http://www.kartenportal.ch/impressum/

Insert Code in German pages before closing </head> tag:

```
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21188903-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
```

Insert Code in English pages before closing </head> tag:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-21188903-2', 'kartenportal.ch');
  ga('send', 'pageview');

</script>
```

French Pages:

```
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21188903-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
```

Italian Pages:

```
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21188903-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
```

**Comment by ethbib-susanne** [comment]
Please wait with working on this ticket. J first have to clarify the judicial situation (impressum text). 

Maybe we will have to adapt the code:
http://kress.it/2010/07/google-analytics-anonymizeip-ip-adressen-kurzen-richtiger-code/

Infos:
http://www.blueglass.ch/blog/google-analytics-datenschutz-schweiz/
http://news.worldsites-schweiz.ch/rechtliche-probleme-beim-einsatz-von-google-analytics-vermeiden.htm
http://rechtsanwalt-schwenke.de/google-analytics-rechtssicher-nutzen-anleitung-fuer-webmaster/

Impressum-Texte:
http://www.datenschutzbeauftragter-info.de/fachbeitraege/google-analytics-datenschutzkonform-einsetzen/

J will inform you when you should continue working on this ticket.

**Comment by ethbib-susanne** [comment]
We will not use google analytics for reasons of data privacy. J close this ticket.

**Comment by ethbib-susanne** [comment]
The Google Analytics Code should not be in the html code of the websites (see above). If there is Google Analytics code it must be removed.

**Comment by klokan** [comment]
It is not in the Kartenportal.CH website (because of this ticket).
It is in the geographical search interface (it always has been there since the beta).
