### ISSUE TITLE
Publications without online-link

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#186]
If a publication is not available online (field empty) the link mustn't be displayed.

Example:

![publikation](https://f.cloud.github.com/assets/4223790/1472975/ccaaee52-460d-11e3-8be2-913c213d4d40.jpeg)

This is very urgent. Because map libraries might be confused.

**Comment by JackuB** [comment]
Could you provide link to this?

Right now, field shouldn't be visible unless it contains something. There might be empty space or something similar, but I need to see it.

**Comment by ethbib-susanne** [comment]
Hello Jakub

Here an example:

http://www.kartenportal.ch/library/SGARK/

---

Von: Jakub Mikulas [notifications@github.com]
Gesendet: Dienstag, 12. November 2013 23:10
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Publications without online-link (#186)

Could you provide link to this?

Right now, field shouldn't be visible unless it contains something. There might be empty space or something similar, but I need to see it.

**Comment by JackuB** [comment]
Found it. Fixed.
