### ISSUE TITLE
Markup Validation

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#187]
Please decide yourself wether these errors should be cleared:

http://validator.w3.org/check?uri=http%3A%2F%2Fwww.kartenportal.ch&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices#result

**Comment by klokan** [comment]
Seems mostly as a bug/feature of WPML:
http://wpml.org/forums/topic/w3c-validation-error/
http://wpml.org/forums/topic/bad-value-for-attribute-hreflang-on-element/#post-75467
Let's investigate further.

**Comment by JackuB** [comment]
Validation page is now green
