### ISSUE TITLE
Search function - 'no result'-message 

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#188]
J miss a 'no result' message in the search function:

![suche](https://f.cloud.github.com/assets/4223790/1483473/40c762c6-46f8-11e3-80b6-dd6c8019347b.jpg)

There should a text be displayed:
"There are no results for your search"

Do you need translations or can J translate the text in the translation interface?

**Comment by JackuB** [comment]
Text can be translated in translation interface like all others
