### ISSUE TITLE
News on pages in directory of map libraries

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#189]
The 'Zentralbibliothek Zürich' has posted a 'map portrait' today. The article should be mentionned in 'news' the section on the page of 'Zentralbibliothek' in the directory of map libraries.

**Comment by klokan** [comment]
On the map library page are listed the posts of type "News/Announcements" not posts of the type "Map".

Shall we add a new section with the "Maps"? Or how you want to present the posts of other types?

**Comment by ethbib-susanne** [comment]
On the start page we present news and map portraits entitled ‘news’. Could we do the same on the libraries pages. Map portraits are also kind of news for the map library.

**Comment by JackuB** [comment]
I updated author's page so that maps are included under news.

Please test: http://www.kartenportal.ch/library/Z04/
