### ISSUE TITLE
Rights for map libraries

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#190]
Changes in the profile form are not visible in the profile view. This task is important and urgent. Please check quickly.

Attention: The changes are displayed when you are logged in in the same browser at the same time.

**Comment by klokan** [comment]
It may be a problem of the cache. Wordpress is caching the page for a certain time - for performance reasons storing an older copy of the page both on the server and in the web viewer.

We created a testlib user, edited it's data and opened the profile view: http://www.kartenportal.ch/library/testlib/ in different browser, later changed the values, reloaded and everything is as it should be. 

How shall we reproduce the error?

**Comment by ethbib-susanne** [comment]
It must be the cache thin on server side because in the evening the changes were displayed properly. Can the configuration be optimized? Otherwise we must leave it the way it is and J have to mention this behaviour in the manual for map libraries.

**Comment by klokan** [comment]
Could you please describe in details how shall we reproduce the error? I could not see the issue on my computer.

**Comment by ethbib-susanne** [comment]
Today a made text modifications for a map library.It worked without any problem. J will mention in the manual that there might be a delay between modification and display of modifications. J close this ticket.
