### ISSUE TITLE
Set up of Kartenportal admin user

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#191]
It is not good to use the ETH-Library E01 user for admin tasks. Maybe the editorial staff will be situated in another instituion in the future. Actually it is not good to mix the two roles (library and amdin). Please set up a sepearte admin user for redactional belongings and name it 'Kartenportal'.

**Comment by JackuB** [comment]
I created new user and sent its credentials to maps@library.ethz.ch - please confirm you were able to retrieve username/password and login.

**Comment by ethbib-susanne** [comment]
That's very good. Unfortunately the maps@library.ethz.ch e-mail adresse should not be used any longer. 

Instead please for the user name take just 'Kartenportal' and for the e-mail adresse 'susanne.zollinger@library.ethz.ch. If the web redaction goes to another institution the admin user has to be set up again because of the e-mail adresse. J don't see a better solution.

**Comment by klokan** [comment]
The 'KartenportalCH' user deleted.
New 'Kartenportal' user created - with role: Kartenportal Admin.
Email set to susanne.zollinger@library.ethz.ch. Password the same as the old one for admin.
