### ISSUE TITLE
Google Search and Ranking

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#192]
J noticed that besides the Kartensuche the pages of the Kartenportal Website are not displayed in the google search.

We should optimize this. Did you set up a google xml site? What are further measures to to so?

This work can be payed extra. Plese note all hours.

**Comment by JackuB** [comment]
There was rule in place to prevent page show up in (google) search. I disabled it 2 days ago.

It'll be indexed soon.

**Comment by JackuB** [comment]
Kartenportal.ch is now indexed correctly in Google https://www.google.cz/search?q=site%3Akartenportal.ch&oq=site%3Akarten&aqs=chrome.2.69i57j69i58j69i59.2612j0j7&sourceid=chrome&espv=210&es_sm=119&ie=UTF-8
