### ISSUE TITLE
Jakub as author

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#194]
![jakub](https://f.cloud.github.com/assets/4223790/1549981/40c8548c-4df7-11e3-818e-946083b367d1.JPG)

When articles of the section services and worth knowing are displayed after a search Jakub ist mentionned as author. The author should be the new user 'Kartenportal'.

**Comment by klokan** [comment]
Done. Jakub admin user has been removed and his posts credited to "Kartenportal".

We have now 'admin' user for software developers and 'kartneportal' user for content administration.
