### ISSUE TITLE
Title tags startseite (home)

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#195]
Please add following texts to titel tag of startseite

German: Kartenportal ¦ Das Fachportal für Karten der Bibliotheken und Archive in der Schweiz
English: Kartenportal ¦ The specialist portal for maps from libraries and archives in Switzerland
French: Kartenportal ¦ Le portail d’accès aux cartes géographiques des bibliothèques et archives suisses
Italian: Kartenportal ¦ Il portale specialistico per mappe conservate in biblioteche e archivi in Svizzera

This work can be payed extra. Plese note hours.

**Comment by JackuB** [comment]
Do you want to edit titles only on homepage? Or do you plan to edit even other pages?

If so, I could add WP plugin to control titles on every page. Otherwise, I'll only update homepage manually.

**Comment by ethbib-susanne** [comment]
The other titles are ok. So you can do it manually. Thank you.
