### ISSUE TITLE
Admin Permissions

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#197]
The admin needs permissions to access all the translation interfaces:

http://www.kartenportal.ch/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php&type=themes

![permissions](https://f.cloud.github.com/assets/4223790/1613799/d1876734-55df-11e3-8a30-3ae8349797ea.gif)

**Comment by JackuB** [comment]
Sorry for delay.
You can now access it under Options menu (when loged as admin)
Fixed.
