### ISSUE TITLE
Library detail page

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#2]
The layout of the library detail page should be changed.

It should contain only a small static map - which after click goes to relevant address on http://maps.google.com/ (we did it on http://www.bmarchives.org/contact).

The layout should count with missing Events / Annoucements / Maps.
It should make more prominent the textual information and data about library. On the older layout the map has been too big.

**Comment by klokan** [comment]
The mockup of the design of library detail page is here:

![kartenportal-webdesign-v4-libraries-detail06](https://f.cloud.github.com/assets/59284/402149/d74eae02-a8f6-11e2-8249-e34690c90451.jpg)

We need confirmation from Susanne, if this should be implemented into HTML.

**Comment by klokan** [comment]
Note: If there are no Upcoming events and News - right block including the vertical line is removed.

**Comment by ethbib-susanne** [comment]
The font size of the main information is to small. J would prefer if the publications were displayed on the right side underneath News. Then the 'find maps' button should be beneath the send email link.

**Comment by klokan** [comment]
The font size is going to be the same as on other pages (to be solved in #18).

The red button is very important on the top right side, otherwise the whole right part of the screen is going to completely empty for most of the libraries (which will not have own upcoming news and events - which is 99% of all). and all the texts are going to be on the left side squeezed in a small space.

Publications (as static HTML text in column "publications" provided in the excel for #13) can be displayed on the right column.

Let's start with the implementation in HTML, once we are ready with milestone START.

**Comment by klokan** [comment]
The sample texts in German and English are in #19

**Comment by klokan** [comment]
Notes from meeting: data in the middle column without extra spaces all same line height.
The telephone number should be picked by the mobile for one-click call. Confirmed by Susanne.

**Comment by klokan** [comment]
TODO:
- The red button should link http://search.kartenportal.ch/#libraries=E01 where the E01 is the record in column "SwissBib" for the provided data. There are libraries which do not have this identifier, then the red button is not displayed. 
- Ensure the localisation runs correctly - the translated titles for fields are displayed and it is possible to switch between languages while looking at the library detail page

**Comment by JackuB** [comment]
The red button - done
Ensure the localisation runs correctly - done
The telephone number should be picked by the mobile for one-click call - done
data in the middle column without extra spaces all same line height. - done

**Comment by klokan** [comment]
Localisation: the switching between languages on the detail page does not run for FR and IT.

**Comment by JackuB** [comment]
Language switching now work correctly
