### ISSUE TITLE
Libraries: search with a map

### ISSUE THREAD

**Issue by radimkacer** [klokantech/kartenportal-tickets#20]
the left column has to be same width as is red line above logo and without space between column and map.
http://kartenportal.klokantech.com/sammlungen/

The libraries are displayed on the map as dots. The map is always a street map - we can style it.

The map will have inside a place search box.

By zooming in the list of the libraries on the left side shrinks so only the visible are in the list.
Hover on the marker or on the list highlight the same record on both maps and the marker.
Click on marker or in the list brings visitors to the detail page of the library.

Technically it runs similar to:
http://storelocator.googlecode.com/git/examples/custom.html

We need to base it on Google Maps V3 API.

There is always a white KML/polygon overlay with the shape of Switzerland.

**Comment by radimkacer** [comment]
![kartenportal-point-blue-large](https://f.cloud.github.com/assets/3808072/590400/a393a4b2-c9e1-11e2-9f7d-ebf1db0fbf56.png)
![kartenportal-point-blue-small](https://f.cloud.github.com/assets/3808072/590401/a3aecb3e-c9e1-11e2-975d-12f42595aa35.png)
![kartenportal-point-red-small](https://f.cloud.github.com/assets/3808072/590402/a3d23678-c9e1-11e2-8399-4144430c9f83.png)

**Comment by klokan** [comment]
Mockup for the libraries:

![kartenportal-webdesign-libraries03](https://f.cloud.github.com/assets/59284/590624/e2b225b8-c9e8-11e2-8e70-1f16a2af11bc.jpg)

**Comment by klokan** [comment]
The Switzerland mask: http://www.vasile.ch/hacks/ft-mask/ and KML from:
https://www.google.com/fusiontables/DataSource?dsrcid=812706

converted to GeoJSON:
http://geojson.io/#6190361
https://gist.github.com/klokan/6190360
https://gist.github.com/klokan/6190360/raw/7d142a8abf4823e95642aaaf96630c3964ddc2c4/map.geojson

which should be usable with:
https://github.com/JasonSanford/geojson-google-maps

**Comment by klokan** [comment]
We started to work on the JavaScript implementation - it will reuse these data tags for displaying the markers on the map. Markers are connected with the list of libraries and interaction will highlight both. Click goes to the library detail page.

@JackuB We need new attributes `data-lat="50.1234" data-lon="20.1234"` on each `<a>` in the `<ul><li>` list.

**Comment by ethbib-susanne** [comment]
Very nice! J like the layout and the interaction design. 

One last point: Is it possible to have a "go back to library search" button on the libraries detail page. The idea is that somebody who already filtered the list and changed to a library detail page can go back easily to the selection made before in order to check other libraries.

**Comment by klokan** [comment]
Thanks for the praise.

We will open the library in a new window/tab instead and keep the libraries list open in the background - same as we do that for geosearch and links to SwissBib and catalogs.

**Comment by klokan** [comment]
Done.
