### ISSUE TITLE
Display of mutuated vowels in suggestions

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#200]
Mutuated vowels must be displayed properly in the list of proposed subjects or names.

Example: When you search with "kümmerly" the proposed name in the list is "kummerly". The filter works correctly. All maps that contain "kümmerly" are displayed.

**Comment by ethbib-susanne** [comment]
The 'kümmerly' example in the publisehr field works correctly now. But there is still a problem with mutuated vovels like 'ü, ä, ö' in the subject field. Example: type 'gösch' or 'schäch' or 'zür'.

Please reopen ticket.

**Comment by klokan** [comment]
In the subject field are not suppose to be any geographic names, according to my knowledge. Related to #206 - these should be removed.

I can not reproduce you reported issue. For example 'zür':

![screen shot 2013-12-06 at 09 28 27](https://f.cloud.github.com/assets/59284/1690809/35f397ca-5e54-11e3-8131-4be98ee69cdc.png)

**Comment by ethbib-susanne** [comment]
My screenshot tool at home can't take a picture of the dropdownlist. For this reason J didn't send a screenshot. J can reproduce the problem in Firefox 25.0.1 and Internet Explorer 10

The point of the mutuated vowels 'ü, ö, ä' are displayed above the following letter. Ex. zürich ist written zurich and the point are displayed above the 'r' insteadt avove the 'u'.

**Comment by klokan** [comment]
Wrong unicode encoding again. To be fixed @keosak.

**Comment by klokan** [comment]
We have over 10 hours already on fixing this issue.

**Comment by ethbib-susanne** [comment]
Finish this at the end. It is not nice but it is possible to test the function.
