### ISSUE TITLE
Subjects that are not displayed + "~" match inside subject

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#202]
Try to select "geomorphologische karten" in the list of proposed subjects. The term doesn't appear in the list while it is more or less frequently used. In the meantime the English equivalent "geomorphological maps" appears in the list. 

Example for a geomorphological map:
http://klokan.github.io/maprank-client/index.de.html#id=130121231

J also miss the subjects "übersichtskarten" or "general maps". Then J find "topographische karten" but don't find "topographic maps":

Example for topograpic map:
http://klokan.github.io/maprank-client/#id=130575658

**Comment by keosak** [comment]
The term "geomorphologische karte" is specified to be a synonym to "geomorphology", which does appear as the first result. This is correct according to the specification.

The autocompleted input field displays only ten most frequent phrases. The "topographic maps" term,however, is less frequent then all the "topographische karte" variants. It is the same with "ubersichtkarten". The solution to this is to unify all the variants into one, but you will have to provide rules for doing this.

The term "general maps" doesn't appear anywhere in the dataset.

**Comment by klokan** [comment]
I would add that all the subjects we are processing are visible at: http://api.kartenportal.ch/subjects-count.txt

**Comment by ethbib-susanne** [comment]
The terms of column one to four must appear at the beginning of the list of proposed terms according to the chosen language. Some to already but this is caused by there frequency of ocurrence in on of the indexes (ex. geologie, hydrologie). Others don't appear in this form in any index (ex. hydrogeologie, hydrogeologie).

**Comment by klokan** [comment]
Terms are sorted by frequency - this is specified in the contract. The issue regarding the "hydrogeology" does not belong here but to #201. It is fixed, but it will be visible tomorrow - as reindexing happens over night.

**Comment by klokan** [comment]
Synonyms in the Google Spreadsheet can now be prefixed with a "~" character. It means that the term will be searched inside subjects instead of being matched directly against them.
