### ISSUE TITLE
Ranking problem

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#203]
Zoom to 'basel' an select 'waldkarten' or 'forest maps'. There is a ranking problem because the two most relevant results are at the end of the list after world forest maps that are much less relevant. This can be reproduced for any region in Switzerland.

**Comment by klokan** [comment]
Please provide the permalink showing the problem.

**Comment by ethbib-susanne** [comment]
Zoom to 'klosters' and then justify window as in the picture below:

![zoomlevel](https://f.cloud.github.com/assets/4223790/1671760/6746aba6-5cc3-11e3-9f8d-22bb9e6bc94e.jpeg)

Narrow search to 'vegetation maps'. The result lists starts with some rather relevant results. They are followed by world maps that should be displayed at the end of the list. At the end the most relevant results appear.

![relevant_results](https://f.cloud.github.com/assets/4223790/1671758/5eb950d8-5cc3-11e3-8cbb-b4cd1ee69a34.jpeg)

Can you reproduce this? It can be reproduced for other regions in Switzerland.

**Comment by klokan** [comment]
http://klokan.github.io/maprank-client/#bbox=9.854474057006883,46.86459835090159,9.892511556795512,46.884510288550665&q=subject%3Avegetation%20maps&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

**Comment by klokan** [comment]
It is now fixed. Closing this ticket.

It has been multiple days of work (over 20 hours). The ranking algorithm was adjusted to remove this issue. New version of ranking is now deployed on the live Kartenportal.CH as well. According to our internal tests there are no regression problems or newly introduced ranking issues with this step - but if you find something let us know.

Work on this task has not been estimated and was not part of the ETH contract functional packages. I am afraid we may need to reduce at least some of the time from the Kartenportal project maintenance credit in 2014 for this.

**Comment by ethbib-susanne** [comment]
The new ranking is tested and works fine. 

J understand that there was some extra work. J will inform Markus about the issue. We let you know whether the maintenance credit is the right account to charge.

Regards
Susanne

**Comment by zb-markus** [comment]
Susanne and I agreed that I will discuss the financial aspects of the present issue by private e-mail.
