### ISSUE TITLE
Ranking of proposed subjects

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#204]
The proposed subjects, authors and editors should be ranked according to their frequency of occurrence in the list of all subjects.

**Comment by klokan** [comment]
An example: for "road" query the "road maps" should be first.

The bug identified - we are sorting according the the frequency but alphabetically not numerically. To be fixed soon.

**Comment by ethbib-susanne** [comment]
Since today the terms of columns one to four are not visible anymore in the list of proposed subjects. They should according to the chosen languange.

**Comment by klokan** [comment]
PLEASE, SUSANNE:

ALWAYS GIVE US EXAMPLES, BROWSER VERSION AND COPY & PASTE OF THE LINK TO MAPRANK URL WHERE WE CAN SEE WHAT YOU ARE SPEAKING ABOUT!

Report like the one above is impossible to reproduce.

In the latest Chrome on the URL:
http://klokan.github.io/maprank-client/index.de.html#bbox=8.017000000000053,46.967,9.016999994444518,47.367&q=&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

I can indeed see autocomplete suggestions in German language from the spreadsheet:
![screen shot 2013-12-06 at 15 15 40](https://f.cloud.github.com/assets/59284/1692716/9df0d284-5e81-11e3-9abb-5d71227b31bc.png)
UPDATE: I uploaded wrong screenshot originally.

**Comment by ethbib-susanne** [comment]
Take a term of the first four columns of the synonyms list and start typing the term. It will not appear in any browser. Example J search for geological maps and type 'geologie' - the subject 'geologie' doesn't appear in the list of proposed subjects. It should.

Ex.:
geologie    geology geologie    geologia
geomorphologie  geomorphology   geomorphologie  geomorphologia
ozeanographie   oceanography    oceanographie   oceanographia
topographie topography  topographie topografia
geobotanik  geobotany   géobotanique   vegetatione
hydrologie  hydrology   hydrologie  idrologia
hydrogeologie   hydrogeology    hydrogeologie   idrogeologia
hydrographie    hydrography hydrogaphie idrographia
klimatologie    climatology climatologie    climatologia
geophysik   geophysics  géophysique    geofisica

**Comment by klokan** [comment]
Term "geology" does not appear. To be investigated @keosak

**Comment by ethbib-susanne** [comment]
"we are sorting according the the frequency but alphabetically not numerically"
J don't understand this. May be it is the answer to my question. But the search doesn't work well this way:

Besides the above listet problem there is still another problem concerning the ranking of the proposed problems. 

When J type 'bod' the term 'bodenkarten + bodenkundliche Karten" should appear on top of the list because it is the most frequent subject. Now it is even not on the list:

![boden1](https://f.cloud.github.com/assets/4223790/1705674/70f902b6-60e2-11e3-8f1c-946d35e22504.jpeg)

When J type "boden" which is a very intuitive term for this search the subject is still not on the list:
![boden2](https://f.cloud.github.com/assets/4223790/1705742/b71c17dc-60e3-11e3-9226-539e62fb06c0.jpeg)

When J type "bodenk" the term appears but it is still not the first subject of the list:
![boden2](https://f.cloud.github.com/assets/4223790/1705676/74f54f50-60e2-11e3-9756-aa2fdeb55420.jpeg)

When J type "bodenka" the subject finally appears on top. This is to late because we can't expect the user to know that the subject is "bodenkarten". We can expect that he types "boden".
![boden3](https://f.cloud.github.com/assets/4223790/1705678/7a4a2fde-60e2-11e3-92de-68acd1a6ba5d.jpeg)

**Comment by ethbib-susanne** [comment]
This ticket is important for testing. At the moment J can't go on testing the synonyme functions.

**Comment by klokan** [comment]
Tested, verified. Last bug hopefully fixed.
