### ISSUE TITLE
Removing of filter settings

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#205]
There should be a way to remove the filter settings of the fields 'title', 'author' and 'publisher' with one klick.

**Comment by klokan** [comment]
New request - not specified in a contract.

Technically we can add "x" to the input box on the right side of these textual fields.

Time tracking to ETH Zurich?

**Comment by ethbib-susanne** [comment]
How many hours?

**Comment by klokan** [comment]
Approx. 2 hours.

**Comment by ethbib-susanne** [comment]
Ok.

**Comment by klokan** [comment]
Tracked under internal ticket https://github.com/klokan/maprank-client/issues/41
