### ISSUE TITLE
Autocomplete Subject: MARC 650$a vs 651$a

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#206]
According the specification in [F.03] in the contract we were suppose to ignore field 650$a as geographical name. It is implemented.

But according the MARC standard the geographical name is the field 651:
http://www.loc.gov/marc/bibliographic/bd651.html

Right now there are many geographical names listed in the:
http://api.kartenportal.ch/subjects-count.txt

These seems to be appearing because they are in 651$a.

Susanne, is the specification 650$a really correct?
Should not it be in fact 651$a?

**Comment by klokan** [comment]
@ethbib-susanne please provide feedback

**Comment by ethbib-susanne** [comment]
I am not in the office and can't check the specification but there must have been a confusion. According a mail that Markus sent to me your are right and

Field 650 contains thematic subjects that must be included
Field 651 contains georaphical subjects that have to be ignored

I am sorry if J caused the confusion.

**Comment by klokan** [comment]
OK. This is going to be updated - and visible online tomorrow latest.
