### ISSUE TITLE
Some SwissBib records without direct links to any catalog

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#207]
SwissBib is providing us with some MARC records without identifiers of individual libraries. These records shows also 0 libraries in the SwissBib interface.

![screen shot 2013-12-10 at 17 22 30](https://f.cloud.github.com/assets/59284/1715757/4f0293e0-61b7-11e3-949b-331e9dd056de.png)

Example:
http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22133952037%22

Visible in Kartenportal.CH at:
http://search.kartenportal.ch/#id=133952037

We need MARC fields 949 or 852 according the specification to link to the individual libraries catalogs.
Internal implementation notes: https://github.com/klokan/maprank-server/issues/10

**Comment by klokan** [comment]
@zb-markus Do you have any additional details about this issue?

**Comment by zb-markus** [comment]
This seems to be still the same problem as in #77.

The Swissbib/Kartenportal record http://search.kartenportal.ch/#id=133952037 was already in the list of 599 records with missing holding information, see https://gist.github.com/keosak/6192215 (9 August 2013).

However, the same record has correct holding information, see NEBIS http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=004600696

It must be a problem at Swissbib. Please discuss with them, they may wish to remove that bug before they set up their new structure early next year. Keep me informed via this ticket.

**Comment by klokan** [comment]
These records still exists in the new SwissBib: http://klokan.github.io/maprank-client/#id=158659678
and https://www.swissbib.ch/Record/158659678 with a note "No Holdings available".

**Comment by zb-markus** [comment]
Well, still the same Swissbib bug. Issue to be postponed until Swissbib has found the bug. Then to be tested by using the list https://gist.github.com/keosak/6192215 (9 August 2013).

**Comment by zb-markus** [comment]
I suppose that the record numbers in this list https://gist.github.com/keosak/6192215 (9 August 2013) are no longer valid. Do you have a new list of record numbers available that have no holding information? Not urgent.

**Comment by keosak** [comment]
An updated list of records without any catalog link is available at https://gist.github.com/keosak/9936813.

**Comment by klokan** [comment]
The original test record mentioned above:
https://www.swissbib.ch/Record/158659678

**Comment by klokan** [comment]
Comment from Tobias at SwissBib:

> 3) Browsing through the examples in the list I saw two different cases:
> 3a) Map items that are coded as ISSUES in Aleph => we do not get items for these due to technical limitations (it’s simply a mass problem we can’t handle zillions of ISSUE-items per library network) If these were coded differently they would be taken.
> 3b) Maps that are linked via field 773. Aleph doesn’t provide usable item information in this case so we cannot process the data.

I don't see what Klokan should do with this case right now. If it is required to make such records NOT discoverable in geosearch - we can adjust our importing scripts to ignore all records without links to library catalogs. But this would be a hack only related to geosearch. A proper fix should be made by SwissBib.

@zb-markus please comment here - or discuss with Tobias your favourite proper solution, if there is any.

Once there is a task for us (Klokan) we should reopen this ticket. I am suggesting to close it now.

**Comment by zb-markus** [comment]
I agree that cases 3a and 3b mentioned by Tobias have to be solved by the libraries. Closing accepted - thank you for investigating the issue. When other cases than 3a and 3b emerge, we will see what needs to be done.
