### ISSUE TITLE
Map series without systemnumber in MARC Field 490 $ w

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#210]
There are some records that contain the field 490 but don't contain a system number in Field 490 $ w. Example:

http://klokan.github.io/maprank-client/#series&id=204320313

If possible the function show/hide other sheets should be surpressed.

**Comment by klokan** [comment]
Processing of the field 490$w was not in the specification of a contract under [F.06]. Sheets belongs to a single series if in 490$a is an equivalent string.

We do not have the data from this field available on the client side at this point.

This is a new request for enhancement - which would require changes on both server and client.

**Comment by ethbib-susanne** [comment]
J give you more instructions in January.

**Comment by ghost** [comment]
FROM:zb
Please close issue. Has been deployed with issue #277.
