### ISSUE TITLE
Hover over list with opened detail window

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#211]
If the detail window is opened the hover over list result should not change the information in the detail window directly - instead a click is required to update the window.

The hover will have a different symbol: red stripes on the side of the box.

Click on the hovered item, which is not yet active, loads it into the detail window.
A click on already active item will close the detail window and next click again on the same item will open it.

During testing of usability this was the most annoying issue of the interface - when the map displayed in the detail window has been changed unexpectedly during the mouse movements.

Mockup:

![kartenportal-webdesign-hover-list](https://f.cloud.github.com/assets/59284/1738485/5e40868a-6385-11e3-9233-e5e219c130b4.jpg)

Note: the function of the result list is not affected if the detail window is not opened.

Please keep the implementation in a separate code branch - so it is possible to revert it or change easily.

**Comment by klokan** [comment]
Implemented and deployed at http://klokan.github.io/maprank-client/

@zb-markus what do you think about this modification? I see it as a huge usability improvement.

**Comment by zb-markus** [comment]
This is fine. 

There is still a small bug, at least in IE8. After scrolling with the mouse wheel, and no detail window is open, the red lines at left and right do appear when scrolling stops at the record above or below the record where the mouse actually is. This happens in about every second or third quick scroll, not in all.
Reproduction:
- IE8, no filters set, no detail window open
- scroll quickly with the mouse wheel
- stop scrollng, do not move the mouse
- the hovered record is full red and another record may be with red lines
- if bug is not seen, start quick scrolling again from where you are in the result list

**Comment by klokan** [comment]
Reproduced, fixed and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
