### ISSUE TITLE
Wrong results with the subject filter "schulkarten"

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#213]
By setting the subject filter to "schulkarten" with autocomplete the results are not filtered by this subject correctly.

Exact URL http://klokan.github.io/maprank-client/index.de.html#bbox=1.3671875,39.749185553172126,30.1171870208334,53.886685504271526&q=subject%3A%23%23%2324%7Cschulkarten&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road
contains the synonymic group: `&q=subject:###24|schulkarten`

First two records in the results are:

1) Map with title "Österreich, Tschechien, Slowakei, Ungarn"
http://klokan.github.io/maprank-client/index.de.html#id=004142861
http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22004142861%22

2) Map with title "Ostfrankreich, Belgien, Luxemburg"
http://klokan.github.io/maprank-client/index.de.html#id=00414287X
http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%2200414287X%22

It seems none of these contains any subjects related to "shulkarten" synonym group, so nothing from:
"Schulkarten", "school maps", "cartes scolaires", "schulkarte", "~schulkarte", "~Geographieunterricht"

These records should therefore not appear in the results. This seems to be a bug.

**Comment by ethbib-susanne** [comment]
Almost every search result is wrong at the moment. A few days ago J had the impression that all the results were correct. Examples:

http://klokan.github.io/maprank-client/index.de.html#bbox=1.3671875,39.749185553172126,30.11718718055556,53.886685504271526&q=subject%3A%23%23%2324|schulkarten&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

http://klokan.github.io/maprank-client/index.de.html#bbox=1.3671875,39.749185553172126,30.11718718055556,53.886685504271526&q=subject%3A%23%23%2310|waldkarten&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

http://klokan.github.io/maprank-client/index.de.html#bbox=1.3671875,39.749185553172126,30.11718718055556,53.886685504271526&q=subject%3A%23%23%2312|hydrologie&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

http://klokan.github.io/maprank-client/index.de.html#bbox=1.3671875,39.749185553172126,30.11718718055556,53.886685504271526&q=subject%3A%23%23%236|topografie&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

and so on.

**Comment by klokan** [comment]
It seems the spreadsheet with synonyms is starting to be very messy and may be filled with some non-sense data by now, which has broken the search by attribute functionality completely at this point.

@ethbib-susanne please work with the spreadsheet with extreme care - with thinking about what you are doing and why you are doing it - to prevent similar issues in future.

Just for the first sight there are really serious problems in the spreadsheet at this moment:
- rows 22 and 23 are almost complete duplicates for "stadtpläne" - both lines seems to be close to equal (possible problem for the system implementation)
- there is a lot of "~" records without a need for that - for example phrases such as "geographieunterricht" does not seems to appear inside of other phrases, no need for "~" then.
- there are overlapping phrases which joins multiple synonym groups (rows) in the spreadsheet together - for example "city plans" is in one row in the first 4 colums and in a different row as alternative column
- there are probably a mistakes as well - such as term "schulkartographie" should belong to "schulkarten", not to "Vogelschaukarten"
- there are terms such as "übersichtsplan [formschlagwort sondersammlungen]" which are in two different synonym groups.
  etc.

Anyway, we will review and fix it on Monday.

**Comment by ethbib-susanne** [comment]
Hi Petr

There might be a mess in our different subject indexes – but the spreadsheet is exactly as it should be at the moment. There are some tests from my side to get a feeling for the functionality. J will revise all these terms after checking the results in the test system. The problems that concern the wrong results after the setting of filters is not related to the synonyms list. There must be a general problem.

Of cours J am glad if you inform me about conflicting terms.

•             rows 22 and 23 are almost complete duplicates for "stadtpläne" - both lines seems to be close to equal (possible problem for the system implementation)

> > The goal is to have only one search term ‘stadtpläne’ also for ‘ortspläne’ which in fact is the same.

•             there is a lot of "~" records without a need for that - for example phrases such as "geographieunterricht" does not seems to appear inside of other phrases, no need for "~" then.

> > Yes it does. Example: http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22168925389%22+IN+%5B4%5D&v=nose&l=de

•             we may have issue overlapping phrases which joins multiple synonym groups (rows) in the spreadsheet together. etc.

> > J don’t understand this. Do you have an example?

**Comment by klokan** [comment]
This issue should be now fixed. Please verify.

**Comment by ethbib-susanne** [comment]
Results are correct now.
