### ISSUE TITLE
Lines matching in series mode

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#216]
The red footprint of the selected sheet should always match the blue lines. It seems that only the right and the bottom of the red footprint need to be adjusted, while the left and the top match already perfectly. Note that the bug sometimes disappears in another zoom level and then shows up again when one zooms even further in or out.

Image for upload follows, made here:
http://klokan.github.io/maprank-client/#series&id=195467345

Bug seen in IE8.

![lines_matching 1](https://f.cloud.github.com/assets/59284/1742927/9fdb8c8c-6404-11e3-8a57-ee19e14a6351.gif)

**Comment by klokan** [comment]
Accepted bug. We will fix it - related to rounding and implementation of the border.

**Comment by zb-markus** [comment]
Tested and accepted.
