### ISSUE TITLE
Remove editions listing within Detailansicht

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#217]
Within the Detailansicht, all the editions are shown in the metadata between the description an the series name. This editions listing should be removed because it interferes with the other metadata of that record, especially the year in the imprint.

Example: http://klokan.github.io/maprank-client/#id=204548551:

Imprint: ... 2006
Description: ...
Editions: 2012 2006 2006 2001 1995 1995 1990 1990 1982 1982 1974 1968 1955 
Series: ...

**Comment by klokan** [comment]
According the contract, section [F.05]: "The detail window must newly present also the information about the available map editions of a particular sheet."

The new map series view in the existing implementation provides an universal interface for selecting all editions of related sheets in the selected series.

If we remove edition list completely then all alternative editions will not be selectable via map series view at all.

@eth-suzanne could you please comment?

**Comment by ethbib-susanne** [comment]
J prefer the new solution for more than one edition and J think that there is not a huge problem for interpreting the given information. It is more usabel and the result list is mor compact. In additon we need a solution to display more than one edition in the special map sheet mode.

As the field name is 'editions' it is clear that the following years indicate more than one edition. The edition year in black color corresponds with the displayed metadata. The blue marked editions are links to get to another edition. All links have the blue color for this users should not be confused. 

Markus, please let us discuss problems before we issue a ticket.

**Comment by ethbib-susanne** [comment]
Petr, Markus and J will discuss the issue and give more instructions in january.

**Comment by zb-markus** [comment]
Ticket closed because issue will be dealt with in nr. 221 referenced above.
