### ISSUE TITLE
Localization of new texts in map series mode

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#220]
Show/hide all sheets of this map series
Alle Blätter dieser Kartenserie anzeigen/ausblenden
Afficher/cacher tous les feuilles de cette série de cartes
Italian text follows

**Comment by klokan** [comment]
Implementation is going to be done once the italian text is available as well.

**Comment by ethbib-susanne** [comment]
This is urgent because J will give a lecture kartenportal at ETH library on the 8th of January.

Texts:
Alle Blätter dieses Kartenwerks anzeigen / Blattübersicht wieder ausblenden
Show all sheets of this map series / Hide map sheet index
Afficher tous les feuilles de cette série de cartes / Cacher la vue d'ensemble des feuilles de la carte
Visualizzare tutti fogli di questa serie di carte / Nascondere la tavola dei fogli della carta

**Comment by klokan** [comment]
This has been finalised a week ago.

For example: http://klokan.github.io/maprank-client/index.de.html
