### ISSUE TITLE
Map indexes with ' in name are not displayed

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#222]
Some map indexes are not displayed while others are:

http://klokan.github.io/maprank-client/index.de.html#series&id=195813529

http://klokan.github.io/maprank-client/index.de.html#series&id=046022546

http://klokan.github.io/maprank-client/index.de.html#series&id=195327276

http://klokan.github.io/maprank-client/index.de.html#series&id=044386567

Reproduced with Firefox 25.0.1 and Internetexplorer 10

**Comment by klokan** [comment]
Reproduced. To be fixed soon.

It is related to the problematic character single quote in the name of the series:
http://stackoverflow.com/questions/18251399/why-doesnt-encodeuricomponent-encode-sinlge-quotes-apostrophes

**Comment by klokan** [comment]
Fixed. Deployed.

**Comment by klokan** [comment]
Regression on " character detected and new fix implemented and deployed.
