### ISSUE TITLE
Synonym problem with terms that contain mutated vowels

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#223]
The synonym look up table works perfect now apart from words that contain mutated vowels. Example: Search for 'übersichtskarten' or 'übersichtspläne'.

**Comment by klokan** [comment]
Autocomplete for these terms does not seem to run.

**Comment by klokan** [comment]
Duplicate to #225

The term 'übersichtspläne' does not exist as subject in the original metadata records.

The term 'übersichtskarten' neither, but it is more complicated - see #226
