### ISSUE TITLE
Autocomplete interaction

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#224]
If J type a term of the first column that is not found in the subjects of metadata the list of suggested terms disappears after typing 6 or 7 letters. The list should be displayed until J type the last letter of the word.

Example: 'geomorfologie'

**Comment by klokan** [comment]
Bug report notes:
this is fine: http://api.kartenportal.ch/autocomplete/?field=subject&lang=de&q=geomor
this not anymore: http://api.kartenportal.ch/autocomplete/?field=subject&lang=de&q=geomorfo

**Comment by klokan** [comment]
Duplicate to #225

The term "geomorfologie" does not exists as subject in the metadata records.
