### ISSUE TITLE
Autocomplete for terms defined only in the spreadsheet

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#225]
The autocomplete does not suggest terms which are new, not available as subjects in metadata records, and are defined only in the spreadsheet.

This must run with diacritic marks as well.

Example terms which does not exist in metadata but are defined in the spreadsheet:
'geomorfologie' -  originally only with 'ph' spelling
'übersichtspläne' - a new term

**Comment by ethbib-susanne** [comment]
THIS IS NOT AN ENHANCEMENT BUT A BUG. It is clear that the words of the first four columns must be suggested in the autocomplete list even if there do not appear in the metadata.

**Comment by klokan** [comment]
This has been just implemented as part of the original contract and it is deployed at http://klokan.github.io/maprank-client/index.de.html

Please test it.

> "It is clear that the words of the first four columns must be suggested in the autocomplete list even if there do not appear in the metadata."

No, this is DEFINITELY NOT CLEAR FROM THE SPECIFICATION in section F.04.

The table is a 'look-up' table (http://en.wikipedia.org/wiki/Lookup_table) "matching against a list of valid items" and defining synonyms between subjects imported from metadata records. Anyway, it does not matter at this point, it is implemented now in the enhanced way you wanted. This gives you more freedom in the sorting of the subjects.

**Comment by ethbib-susanne** [comment]
Thank you :)

**Comment by ethbib-susanne** [comment]
Can this implementation already be tested? If yes, there is a problem. The search results are not correct.

Example:

http://klokan.github.io/maprank-client/index.de.html#bbox=7.836500000000115,46.77499,8.513899962366395,47.28710000000002&q=subject%3A%23%23%2310|%C3%BCbersichtspl%C3%A4ne&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

http://klokan.github.io/maprank-client/index.de.html#bbox=7.836500000000115,46.77499,8.513899962366395,47.28710000000002&q=subject%3A%23%23%2318|hydrografie&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road

**Comment by klokan** [comment]
Regression. We are working on a fix.

**Comment by klokan** [comment]
Only forgotten manual reindexing of the whole SwissBib after the changes were applied.
Normally it would happen automatically over night. It should be fixed by now.

**Comment by ethbib-susanne** [comment]
Is perfect now.
