### ISSUE TITLE
Non-geographic subjects with '(' in the MARC 691$u

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#226]
According the specification F.03 from contract we are ignoring all subjects which contain character '(' in 691$u - as unwanted geographic name.

Unfortunately, there are some records which does contain '(' in 691$u but are not geographic subjects.

Why there is `912%` as well as `912(` in the following record for non-geographic subjects?

```
=691 E1 $a ÜBERSICHTSKARTEN $z ger $u 912(084.3-15)
=691 E1 $a TOURISTENKARTEN $z ger $u 912%379.8
=691 E1 $a KALIFORNIEN, BUNDESSTAAT (USA) $z ger $u (730.94)
```

http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22209015926%22

This has not been specified in the contract...

Note: in the contract specification is in fact `,(,` which must be wrong as there are large number of geographic subjects without commas in $u - one of them is visible above as well...

@ethbib-susanne please comment.

**Comment by ethbib-susanne** [comment]
URGENT

We have to adapt the rule as soon as possible: all terms with a code in field 691$u that starts with '912' must be included.

How many working hours?

**Comment by klokan** [comment]
Done on 2013-12-18.
