### ISSUE TITLE
Transparency problem of displayed map series

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#227]
In Firefox 26.0 and Internet Explorer 10.0 this map series is displayed nontransparent:

http://klokan.github.io/maprank-client/index.de.html#series&id=157377253

**Comment by klokan** [comment]
This series contains many overlapping world maps - which hides the smaller maps underneath.
It is technically impossible to make all the world maps selectable in such a serie anyway.

It is related to #215.

3 hours of extra work again, implemented "even in transparency". Rendering may be slightly slower now.
