### ISSUE TITLE
Synonyme list - special characters

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#228]
There is a problem concerning secial characters:

brace (
colon :
plus +

Terms that contain this characters are not processed.

Example colon - string '~verkehrskarte:' is on the synonyme list

![synonymes1](https://f.cloud.github.com/assets/4223790/2028164/22fc1d00-88c9-11e3-9920-18d7a79ae57c.gif)

Example brace: term 'pläne (kartenmaterial)' is on the synonyme list

![synonymes2](https://f.cloud.github.com/assets/4223790/2028168/32bc4c7e-88c9-11e3-943d-2e1e04fa2d86.jpeg)

Example plus 
![synonymes3](https://f.cloud.github.com/assets/4223790/2028204/fcff301e-88c9-11e3-8d41-db353fb41290.jpeg)

**Comment by klokan** [comment]
We are searching in a fulltext index. So called "stop characters" are in fulltext ignored. Dots, commas, braces, colons, etc are therefore not filtered. This is expected behaviour.
You have to write your filters with keeping this in mind.

**Comment by ethbib-susanne** [comment]
Please provide a list of stop characters. Thank you.

**Comment by keosak** [comment]
We accept as words or terms only consecutive strings of letters and digits. Every other character is a word delimiter.

**Comment by ethbib-susanne** [comment]
J tried to set up the synonyme list without special characters. The result is not satisfying because we are limited by not using the special characters "(", ")" and ",". 

Is there a way to make this special characters available for configuration? How much hours of programming would it take?

**Comment by klokan** [comment]
Introducing support for special characters would mean quite a substantial reimplementation of the indexing - e.g. possibly over 40 hours of work. This is not how the system runs now.
We don't see a use case where this feature is really required. Explain your "not satisfying" please.

Could you please provide a real example of what you want to do and can't right now?

Ideally:
1) what you want to group together (a few sample subject fields)
2) what are your phrases in the synonyme Excel now (phrases you have made for the sample subjects)
3) what is expected in the autocomplete (input typed by person in Kartenportal interface and list of expected vs received autocomplete phrases)

All for a single example which is causing your a problem now.
Then we can recommend a solution of the problem or suggest required hour range for the implementation.

**Comment by ethbib-susanne** [comment]
Example 1:

1) ?
2) Geologie geology geologie    geologia    GEOLOGISCHE KARTEN  GEOLOGICAL MAPS     CARTES GÉOLOGIQUES     GEOLOGISCHE PROFILE GEOLOGICAL PROFILES PROFILS GÉOLOGIQUES    MEERESGEOLOGISCHE KARTEN    MARINE GEOLOGY MAPS     CARTES GÉOLOGIQUES DES FONDS MARINS    ~erdkruste  ~erdkern    ~regional geologie  meeresgeologie  ~erdölgeologie ~batholit   ~geotope    ~stratigraphie  ~regional geology   ~batholiths ~stratigraphy   ~stratigraphic  ~fault  ~marine geology ~geological géologie structurale   ~géologie historique   géologie et géophysique appliquée    ~batholites ~géologie régionale   ~géologie marine   ~geologia marina
3) The expected autocomplete phrase is only "geologie"

The received list after typing 4 letters is:
![synonyms_geologie](https://f.cloud.github.com/assets/4223790/2434571/ab58d826-adb5-11e3-87a3-ed34301670ab.jpg)

Example 2:

2) Geschichte   history histoire    storia  GESCHICHTSKARTEN    HISTORICAL MAPS     CARTES HISTORIQUES  ~epochen     zeitgeschichte ~nationalsozialismus ~histoire militaire ~histoire mondiale ~histoire culturelle    ~histoire de l'église  ~histoire locale    ~histoire contemporaine

3) The expected autocomplete phrase is only "geschichte"

The received list:
![synonyms_geschichtet](https://f.cloud.github.com/assets/4223790/2434683/07cbd64c-adb8-11e3-9c80-10fbf18fdfda.jpg)

**Comment by klokan** [comment]
Solution for example 1):

If you want to merge all subjects containing the word "geologie" into one group you must add the phrase "~geologie" to the Excel in the end of the row. We have did it now online - so you can see it in action at http://klokan.github.io/maprank-client/
This will hide all phrases such as "geologie: schweiz", "geologie - solothurn", "geologie/einzelne gebiete", etc. in the autocomplete and suggest "geology" in English interface instead.

Solution for example 2):

Exactly the same story. Please add phrase "~geschichte" in the end of the Excel. This has not been done yet - so you can test by yourself the solution.
Remember to visit the update link and wait for the next day for the re-indexing of the autocomplete database.

Clearly, there is no need to do anything with special characters as originally requested for this ticket to solve the problem you described. Please confirm this is the solution of the problem.

**Comment by ethbib-susanne** [comment]
1) There is a problem if J use „geologie“ and “~geologie” in the same row. The filter doesn’t work correctly then.
2) dito

Your solutions unfortunately don't work. J tried them out before.
