### ISSUE TITLE
Frontpage - Graphic design find map section

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#23]
Font must be bold as in the previous version.

Background should be more transparent as in the previous version (maybe between).

![find maps section](https://f.cloud.github.com/assets/4223790/453518/0e32d894-b31a-11e2-9cbe-057d2d67b2e8.jpg)

**Comment by klokan** [comment]
Additional comment from Sussane, wrongly posted into a wrong ticket:

In addition a comment on the font size:

The 'Find Maps' title should have the same font size as 'Swiss Map Collecitons'. The red color accentuates the importance of the service.

The example terms ('Stadt Luzern, Walensee') must have the same font size as the other texts (see pevious version).

![a8b5e634-b31c-11e2-8283-19463153377e](https://f.cloud.github.com/assets/59284/453601/3c16d022-b31e-11e2-91b4-72bf54961cc1.jpeg)

**Comment by klokan** [comment]
The front photo has been replaced. This is the final version - we have made 10 iterations to make it better, but still keep the text readable.

The changes related to fonts of the title are remaining on this ticket.

**Comment by klokan** [comment]
Closing, I expect these sort of requests are going to be reported and resolved in July - during beta version testing.
