### ISSUE TITLE
Geographic keywords Field 651 used for autocomplete

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#231]
It seems that geograpic keywords MARC Field 651 are used for autocomplete.

Examples:
Use "Schweiz ost" or "luzern region" for filtering.

**Comment by klokan** [comment]
Susanne, could you please with a bug report ALWAYS provide:

1) copy and paste of the URL address from your web browser for the query you used with the Kartenportal search - so we see the same results as you.
2) when relevant, the version of browser - Firefox / IE 7 / IE 8 / IE 9 / IE 10 / Chrome ?
3) when relevant, links to individual SwissBib MARC records demonstrating the problem

At least 1) is really always required - it does not take you any effort extra at all. Just copy&paste the address from your browser.

Then it is much easier for us to investigate the problem you are describing.

I have spend now 15 minutes searching maps with "Schweiz" or "luzern" in $651 as you report here and could not find one. Thank you.

**Comment by ethbib-susanne** [comment]
J am sorry. Here the complete information:

URL of search 1:
http://klokan.github.io/maprank-client/index.de.html#bbox=-110,-52,119.99999744444449,72&q=subject%3Aschweiz%20%3Cnordwest%3E&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road
Result of search 1:
http://klokan.github.io/maprank-client/index.de.html#id=10231165X
URL of search 2:
http://klokan.github.io/maprank-client/index.de.html#bbox=-110,-52,119.99999744444449,72&q=subject%3Aluzern%20%3Cregion%3E&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road
Result of search 2:
http://klokan.github.io/maprank-client/index.de.html#id=223244457

J use Firefox 26.0. But J think this is not a question of browser version.

**Comment by keosak** [comment]
Both records contain geographic keywords in MARC field 690. Our filter removes this field, but only if it has a subfield "D" with value "g". This is in accordance with previously agreed specification (#206, #226). For reference, this is the current specification.

```
Include into subject all 6XX fields, except:
    651
    690 where $D = "g"
    691 where $u contains "(" but doesn't start with "912"
```

The two records you mentioned have the following 690 fields that according to the above should be included.

```
=690 -9 $a Alpenländer $x Strassenkarte
=690 -9 $a Schweiz $x Strassenkarte
```

```
=690 -9 $a Luzern $v Stadtplan
=690 -9 $a Luzern $x Luftbild $v Karte
```

**Comment by ethbib-susanne** [comment]
J agree that we can't exclude geographical keywords that are contained in 690 -9 $a fields.

**Comment by klokan** [comment]
New reported issue moved to #241
