### ISSUE TITLE
New SwissBib: new backlinks

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#233]
Tobias Viegener provided details for the required switch to new backlinks and OAI endpoint for the SwissBib.
The switch of backlinks should be made by mid-Fabruary.
Complete reload of metadata and switch to new OAI endpoint  should follow - the existing infrastructure is going to be shutdown by the end of July 2014 the latest.

Details to be discussed with Tobias soon.

Details are in the email ("swissbib: change notification on back linking and data services") and in our internal ticketing system.

**Comment by klokan** [comment]
From Tobias:

We recommend to change the back-linking-mechanism as a short term solution, if you cannot manage to switch to our new data-source in time. Changing the backlink-layout is easy:
-- if you cannot reload the data, use a local system number for back linking for as long as you're working on the reload of our data. It is a fairly straight forward approach:
--- firstly prepare one of the local system numbers by concatenating the system number in 035$a with its prefix. It is important that you remove the brackets first.
--- secondly use the number in the following search link: https://test.swissbib.ch/Search/Results?lng=de&sort=relevance&type=CTRLNUM&lookfor=ABN000698094

Example: https://test.swissbib.ch/Search/Results?lng=de&sort=relevance&type=CTRLNUM&lookfor=ABN000698094

If you're able switch to the new data source by mid-February, you can use the URL-following format: https://test.swissbib.ch/Record/{swissbibID} 
Example: https://test.swissbib.ch/Record/006107060

**Comment by klokan** [comment]
The backlinks to Swissbib (which are after the switch broken since today at around 18:00) are going to be fixed tomorrow morning.

**Comment by keosak** [comment]
Old Swissbib links are now redirected to the new ones through the suggested SwissBib search interface. Fix is applied on the public Kartenportal.CH search interface.

**Comment by klokan** [comment]
The http://klokan.github.io/maprank-client/ interface has been upgraded to the new SwissBib.
There are new permalink IDs in the portal and new links to Swissbib following the final new https://www.swissbib.ch/Record/{swissbibID} pattern.
