### ISSUE TITLE
Urgent: Code for statistics and usability

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#236]
Please insert as soon as possible some script code for statistics and usability. The code is under way by private e-mail. Note that it is intended not only for the map search part but also for the whole Kartenportal web site. The usability team said that the code should be before the `</body>` tag or in the footer of the web pages.

**Comment by klokan** [comment]
Done.

A note: It is good to provide the complete specification into the ticket - or on one place at least.

**Comment by klokan** [comment]
I see here the request for including the code in both website and search (mentioned in the email).
