### ISSUE TITLE
Map series that are not displayed correctly

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#238]
This map series displays only single sheets:
http://klokan.github.io/maprank-client/index.de.html#id=196382718
http://klokan.github.io/maprank-client/index.de.html#id=196296730

When you zoom out suddenly more sheets (also neighbouring sheets) are displayed:
http://klokan.github.io/maprank-client/index.de.html#series&id=195725972

J use Firefox 26.0.

**Comment by klokan** [comment]
These were issues related to the cache of tiles and regular updates of the database.
We are now testing alternatives. The map series functionality may be broken for a short time.

**Comment by klokan** [comment]
All of this should be now temporarily fixed.
We will fix it permanently in the week 10-14th March, on which we scheduled reinstallation of the Kartenportal Search server required by the hosting provider (#232).

**Comment by klokan** [comment]
This should be fixed properly in the new version. Beta available at: http://klokan.github.io/maprank-client/
