### ISSUE TITLE
Permalinks to Kartenportal needs to be changed

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#240]
Markus, Susanne,

The change in SwissBib introduced recently is so radical - that none of the numerical "permalinks" to our search website on Kartenportal.CH will be permanent anymore.
It seems there is no way how to continue to keep the existing identifiers of records after we upgrade to the new SwissBib database.

Links such as:
http://suche.kartenportal.ch/#id=204676622

are going to stop to run, or will display a different map - because new SwissBib is assigning a new identifier to all records.

The original record with id "204676622" will have a new id "01610918X".

This means the new link to the same map on Kartenportal will become:
http://suche.kartenportal.ch/#id=01610918X or maybe:
http://suche.kartenportal.ch/#01610918X  (it does not run yet)

SwissBib does not provide any way how to directly access their old ids (204676622) from records with the new ids (01610918X). It seems the old id simply disappears in the new version of the SwissBib portal, I have not seen it in the new exports.

Unfortunately, as a result, I don't forsee a long term technical solution for preserving the existing "permalinks" in Kartenportal because of these reasons. We are fully dependent on the SwissBib data exports.

Even if SwissBib agree to include in the new records the old IDs (which I doubt), it would mean a significant effort to keep the permalinks active an in use - and for some of the records the old IDs will not exist anyway. A switch to new permalinks on Kartenportal is inevitable.

The question is how to preserve the existing old permalinks, and how much effort are we allowed to invest into this.

I will write about this fact to SwissBib people and ask about the details and if they were considering some solution for similar problems.

Please comment about this subject in here and share your opinions.

**Comment by ethbib-susanne** [comment]
Do J understand right that there will be new IDs that are permanent too? In my opinion it is not a problem if permalinks that were produced before the upgrade don't work afterwards as we still are in a kind of pilot phase. J suppose that similar changes will not repete frequently in the future.

**Comment by zb-markus** [comment]
I fully agree with Susanne. As long that all internal links (for example from http://www.kartenportal.ch/maps/vogelschaukarte/) can be fixed accordingly, then I do not see any problem.

**Comment by klokan** [comment]
OK. I hope similar large upgrade is not going to be made again - so the SwissBib identifiers will be really permanent.

The permalinks on http://klokan.github.io/maprank-client/ interface have been upgraded to the new SwissBib.

BEFORE MONDAY YOU SHOULD PROBABLY LOOK UP THE MAPS linked to the old system with old identifiers and find the new SwissBib identifiers - so upgrade of the links in the articles such as http://www.kartenportal.ch/maps/vogelschaukarte/ can be made on Tuesday.

I am closing this ticket. If new related requests are made - please open a new ticket.
