### ISSUE TITLE
Again: CrazyEgg code for statistics and usability 

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#242]
Following implementation of the CrazyEgg script (#236) its team noted some problems with loading our site. They wish that an additional script is being inserted between the current CrazyEgg script and the `</body>` tag. Here the additional piece:

```
<script type="text/javascript">
var loop11_key = "4d7d05fac0131a36bab38661cf9e8261f8b2d741";
document.write(unescape("%3cscript src='//cdn.loop11.com/my/loop11.js' type='text/javascript'%3e%3c/script%3e"));
</script>
```

**Comment by klokan** [comment]
I suggest to include this update into the new version which should be public on Monday afternoon.

**Comment by zb-markus** [comment]
Urgent: The following script needs to be implemented within 24 hours. The public testing is starting this week. Please insert after the Swissmetrix script, just before the </body>:



<script type="text/javascript">
var loop11_key = "4d7d05fac0131a36bab38661cf9e8261f8b2d741";
document.write(unescape("%3cscript src='//cdn.loop11.com/my/loop11.js' type='text/javascript'%3e%3c/script%3e"));
</script>

**Comment by zb-markus** [comment]
Urgent: The following script needs to be implemented within 24 hours. The public testing is starting this week. Please insert after the Swissmetrix script, just before the /body

start crazyegg

```
<script type="text/javascript">
var loop11_key = "4d7d05fac0131a36bab38661cf9e8261f8b2d741";
document.write(unescape("%3cscript src='//cdn.loop11.com/my/loop11.js' type='text/javascript'%3e%3c/script%3e"));
</script>
```

end crazyegg

**Comment by zb-markus** [comment]
Sorry, this seems not to accept code. See e-mail.

**Comment by klokan** [comment]
Included in the www.kartenportal.ch website and all language variants of the search interface.

```
  <!-- begin crazyegg -- >
  <script type="text/javascript">
  setTimeout(function(){var a=document.createElement("script");
  var b=document.getElementsByTagName("script")[0];
  a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0018/6944.js?"+Math.floor(new Date().getTime()/3600000);
  a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
  </script>

  <script type="text/javascript">
  var loop11_key = "4d7d05fac0131a36bab38661cf9e8261f8b2d741";
  document.write(unescape("%3cscript src='//cdn.loop11.com/my/loop11.js' type='text/javascript'%3e%3c/script%3e"));
  </script>
  <!-- end crazyegg -->
```

In a case some of this uncontrolled code could be removed, let me know.
Closing - if issues are reported let's reopen this.

**Comment by zb-markus** [comment]
The testing team is very sorry that the script again needs to be updated. Follows by e-mail.

**Comment by klokan** [comment]
The required new code is:

```
<script type="text/javascript">
var loop11_key = "4d7d05fac0131a36bab38661cf9e8261f8b2d741";
var l11_clientOptions = {"crossDomainSupport":true}; document.write(unescape("%3cscript src='//cdn.loop11.com/my/loop11.js' type='text/javascript'%3e%3c/script%3e"));
</script>
```

**Comment by klokan** [comment]
Deployed on both geosearch and and web. Closing.

**Comment by zb-markus** [comment]
There is still a problem: The internal "begin crazyegg" comment should close with 

hyphen hyphen greater-than-sign

instead of

hyphen hyphen space greater-than-sign

That is: omit a space. This typo problem was found in the 4 web language versions of the web site, while the closing tag in the map search is correct.

**Comment by klokan** [comment]
I am sorry for this typo. It is fixed now.

**Comment by zb-markus** [comment]
The external test management has tested and accepted. We will open a new issue as soon as the code can be removed.
