### ISSUE TITLE
Again: Updating the library list

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#244]
Since at least from 12 March, the library list has not been updated. The figures are the same since. This concerns both the official and the test versions.

We are aware that this may be due to the reorganization at Swissbib. We expect that the library list will be updated regularly afterwards. Nevertheless, please check whether there is a new bug on your side.

**Comment by klokan** [comment]
I expect you report here that the number of indexed record per library is not as expected for you. The library list is complete, i.e. all expected libraries are visible.

Can you let us know the actual numbers - which are expected (and where are you getting them?).
Is it a difference in hundreds or a few maps for what is visible on the website?

Map records from SwissBib can be ignored if:
- bounding box is missing
- bounding box is completely wrong (numbers not in the expected range)
- if the maps is a map of the sky (034$z)

BTW The XML list of libraries was not anymore provided from SwissBib for quite some time. Just two days ago we have received a new format in JSON and we work on reimplementation of this part for the new Swissbib in #235

**Comment by zb-markus** [comment]
You are right, it is the number of records per library (and its total figure) that is not updated, not the library list as such. We found out that already at 26 February the figures stoped to be updated. So I can compare with figures as of 26 February:

Uni Basel - UB Hauptbibliothek has catalogued about 270 maps since 26 February, which should give a new total of about 5240. Information by the cataloguer.

Zentralbibliothek Zürich - Kartensammlung has catalogued about 30 maps since 26 February. The expected total should rise to about 25130. Information from catalogue query.

Schweizerische Nationalbibliothek, Bern has announced about 30 new maps recorded between 28 February and 15 March, giving a new total of about 17190. Source is "Schweizer Buch", the online service that announces new titles in the catalogue recorded the 2 previous weeks.

**Comment by klokan** [comment]
It may be possible that Swissbib stopped to update the old OAI-PMH database by that time.

Now the new SwissBib is indexed at http://klokan.github.io/maprank-client/.

The numbers there are higher then mentioned here - so probably as expected.
I consider this is now a solved problem from our side.
Please verify, if another issue is discovered we will reopen and fix it.

**Comment by klokan** [comment]
Reported AGAIN AND AGAIN!!!

No change in the numbers of indexed maps since March 26th. There are new maps in SwissBib - why are the numbers in the library list not updated? @keosak

**Comment by klokan** [comment]
@zb-markus this should be fixed by now (there was a rights issue on the server). Please verify this within the following days. If you see this is now fixed, please close this ticket.

The OAI and the database has been always re-indexed but the numbers next to the libraries were not.

**Comment by klokan** [comment]
@zb-markus as there is no error of issues, I expect this runs now fine. Closing the ticket. If there is report of a problem we will reopen.
