### ISSUE TITLE
Links from Detailansicht to library directory

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#247]
Hundreds of links from Detailansicht to library directory need to be restored. Some examples of missing links:

http://klokan.github.io/maprank-client/index.de.html#id=174009917
(link Zentralbibliothek to http://www.kartenportal.ch/library/Z04/)

http://klokan.github.io/maprank-client/index.de.html#id=015211193
(link Swisstopo to http://www.kartenportal.ch/library/AX40/)

http://klokan.github.io/maprank-client/index.de.html#id=065672534
(link National Library to http://www.kartenportal.ch/library/10000/)

**Comment by klokan** [comment]
Technically this is a duplicate to issue #246

**Comment by zb-markus** [comment]
Maybe. While I considered #246 as a problem of import from Swissbib, I think that #247 deals with internal Kartenportal links. Anyway, the manual change of some identifiers may indeed solve both issues.
