### ISSUE TITLE
Empty records list when scale filter is set

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#248]
I have filtered by scale
http://klokan.github.io/maprank-client/index.de.html#bbox=12.524260474902348,55.65272409087972,12.664701973341834,55.70853711556554&q=&date_from=0&date_to=9999&scale_from=5000&scale_to=25000&libraries=&map=road
and no records were found. Some example records that should still be in the records list:
http://klokan.github.io/maprank-client/index.de.html#id=169027724
http://klokan.github.io/maprank-client/index.de.html#id=174009917
http://klokan.github.io/maprank-client/index.de.html#id=015070727

Seen in IE8 and IE9.

**Comment by keosak** [comment]
There was a problem with parsing scale numbers from the relevant MARC fields. It is fixed now.
