### ISSUE TITLE
URGENT - New swissbib identifiers for libraries

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#249]
There are three libraries that seem to have new identifiers:

Kartensammlung swisstopo (NB001/10000)
Schweizerische Nationalbibliothek (AX040/AX40)
Zentralbibliothek Zürich (Z01/Z04)

Can J remove the old records (10000, AX40, Z04)?

J already transferred an event from the old to the new swisstopo record. But there is still a map portrait of Zentralbibliothek Zürich and news of swisstopo that J can't transfer personally because there is no appropriate field available. Could the field be added similair to the event form?

![autor](https://cloud.githubusercontent.com/assets/4223790/2567086/c554f8c4-b8d0-11e3-8416-aaa90502ffa6.jpeg)

**Comment by klokan** [comment]
The user accounts with old identifiers are now removed - all appropriate published posts should be assigned to the new accounts.

These three libraries may need to reset their passwords for login into Kartenportal administration.
