### ISSUE TITLE
Services page: new landing picture

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#25]
For section 'Services' please use the following picture and integrate it with the list of other services (agreed on meeting on May 30th):

![services](https://f.cloud.github.com/assets/4223790/453599/1cc806c8-b31e-11e2-91f9-f9a641dedebb.jpeg)

The high resolution version (of all the photos) is at:
https://drive.google.com/a/klokantech.com/#folders/0BwUe1kqIRJWSNElXb1U3R2ozWUU

The existing overview page is going to be removed - instead we directly display "Services" record with this photo and short paragraph (in this moment we do not have the text yet - let's use lorem ipsum).

**Comment by klokan** [comment]
TODO: Add this photo as the first article in the list. It should be displayed when the user clicks in menu on Services.
