### ISSUE TITLE
Map series that are not displayed

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#251]
Examples tested in Firefox 26.0:

http://suche.kartenportal.ch/#series&id=184130190

http://suche.kartenportal.ch/#series&id=182958094

http://suche.kartenportal.ch/#series&id=184849292

http://suche.kartenportal.ch/#series&id=18462133X

http://suche.kartenportal.ch/#series&id=18480681X

http://suche.kartenportal.ch/#series&id=183606205

**Comment by klokan** [comment]
Fixed.
