### ISSUE TITLE
~geomagnetische subjects in autocomplete

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#253]
In the synonym autocomplete table is "~geomagnetische" phrase, as well as other phrases such as "~archäologische" or "~ökologische" and others which runs correctly on the search filtering, but autocomplete suggests such phrases if it should not suggests these (they are in the 4th column or further in the synonym table - only the single phrase from one of the first 4 column should be suggested in the autocomplete).

**Comment by klokan** [comment]
Maybe related problem "(CANTON" not accepted with "~canton".

**Comment by klokan** [comment]
We have just updated the autocomplete and this issue is not anymore present.

Susanne - have you been calling the updating script after the modification of Google Drive table or not?

The updates are applied via this procedure:
1) The Google Drive table is edited
2) You MUST visit the link: http://api.kartenportal.ch/update-synonyms so the table is downloaded from Google Drive to the server
3) The whole autocomplete and maprank is re-indexed over the night, you have to wait for the next day

If all these three steps are done then you should see the results on the production Kartenportal.CH.
It seems to me you have forgotten the step 2). If this is true, I expect we can close this ticket as a report of a problem which does not really exists.

BTW we are removing the "-" from autocomplete.

@ethbib-susanne please verify that everything runs as expected and comment. Thank you!

**Comment by ethbib-susanne** [comment]
Thank you very much for solving the problem.

Did you simply follow the described procedure? J am quite sure that J always carried out step 2 and always got the success message:

![update](https://cloud.githubusercontent.com/assets/4223790/2720710/34c456b0-c573-11e3-8e1c-51394426358e.jpeg)

**Comment by ethbib-susanne** [comment]
J made an update at 17:50 can you please check if the update was carried out successfully?

**Comment by ethbib-susanne** [comment]
The configuration of the synoyms table is not finished yet. 

A minute ago J startet the update routine an got an error message: "attempt to write a readonly database"

**Comment by keosak** [comment]
I fixed the permissions issue. Database should be up to date as of now.
