### ISSUE TITLE
Configuration event list on start page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#255]
There is an ongoing exhibition (biwak) that is listed on the German start page but not in French, English or Italian.

**Comment by klokan** [comment]
How was this one prepared? (under what account).

There is a JavaScript code which ensures the multi-linguality. We can fix this single even, but more important is that it does not happen again. Please provide more info.

**Comment by ethbib-susanne** [comment]
There was an extension of time and the library (Alpines Museum) changed the finish date if J remember correctly.

**Comment by klokan** [comment]
For some reason (maybe deactivated JavaScript on the client side) this even has not been saved in with the date in multiple language variants.

It should be now fixed. We re-opened it and saved the date of the event again.

It is not clear how to reproduce the error. If more details are available we can make a fix preventing the issue in future. Right now it is not clear, but reported issue is fixed.
