### ISSUE TITLE
Display of map series

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#256]
The map series are not displayed at all zoom levels. If they are displayed at a certain zoom level there are not all sheets visible:
Examples:
http://suche.kartenportal.ch/#series&id=184389100
http://suche.kartenportal.ch/#series&id=184341590

Firefox 26.0

**Comment by klokan** [comment]
Reproduced. We are looking at the reason for this issue.

**Comment by keosak** [comment]
The issue was probably a race condition in the regular update process, causing the database and its index to be out of sync. I have repaired the database and implemented a fix that should prevent this from happening again.
