### ISSUE TITLE
Synonyms list update

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#258]
J updated the synonyme list yesterday but the update of the list was not carried out over night although J sent the update command after saving the list and got a "SUCCESS" message.

**Comment by keosak** [comment]
The update failed yesterday, because the OAI-PMH server is broken. It returns a "200 OK" response status but an empty body to any request. I will update synonyms in the current database file, but the OAI-PMH server must be fixed for MapRank to function properly.

**Comment by klokan** [comment]
In other words - there are problems on the SwissBib side. If these are not resolved soon we will contact them.

**Comment by klokan** [comment]
@ethbib-susanne is the latest synonym list applied by now or this issue is still in here?

**Comment by ethbib-susanne** [comment]
At the moment updates are not possible:
<class 'sqlite3.OperationalError'>

Python 2.7.3: /home/maprank/venv/bin/python
Wed Jun 4 08:02:49 2014

A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.
 /var/www/cgi-bin/update_synonyms.pyfile:///\varwwwcgi-binupdate_synonyms.py in ()

```
116     connection = sqlite3.connect(DB_PATH)

117     cursor = connection.cursor()
```

=>  118     errors = update_synonyms(cursor, res.content)

```
119     if not errors:

120         connection.commit()
```

errors undefined, update_synonyms = <function update_synonyms>, cursor = <sqlite3.Cursor object>, res = <Response [200]>, res.content = 'de,en,fr,it,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...rwaltung,~toponymy,zeit,zeithintergrund,zeittafel'

 /var/www/cgi-bin/update_synonyms.pyfile:///\varwwwcgi-binupdate_synonyms.py in update_synonyms(cursor=<sqlite3.Cursor object>, csv_data='de,en,fr,it,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...rwaltung,~toponymy,zeit,zeithintergrund,zeittafel')

```
 64             synonyms[(id, term)] = sub

 65     if not errors:
```

=>   66         cursor.execute("DROP TABLE IF EXISTS translations")

```
 67         cursor.execute("""CREATE TABLE translations (

 68                                 id INTEGER,
```

cursor = <sqlite3.Cursor object>, cursor.execute = <built-in method execute of sqlite3.Cursor object>

<class 'sqlite3.OperationalError'>: attempt to write a readonly database
      args = ('attempt to write a readonly database',)
      message = 'attempt to write a readonly database'

Von: Petr Pridal [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. Juni 2014 10:02
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Synonyms list update (#258)

@ethbib-susannehttps://github.com/ethbib-susanne is the latest synonym list applied by now or this issue is still in here?

**Comment by keosak** [comment]
Please try again. I have been checking-in on the update process regularly and perhaps I have inadvertently changed permissions on the file.

**Comment by ethbib-susanne** [comment]
Works successfully now, thank you.

Susanne

Von: Václav Klusák [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. Juni 2014 10:13
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Synonyms list update (#258)

Please try again. I have been checking-in on the update process regularly and perhaps I have inadvertently changed permissions on the file.
