### ISSUE TITLE
Library 'c30000' is now 'RE31002' in SwissBib

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#259]
The collection filter doesn't persist when J start the map search out of a specific collection profile for some collections:

http://www.kartenportal.ch/library/c30000/

**Comment by klokan** [comment]
This seems to be a problem of the identifier of the mentioned library "c30000".
In new SwissBib it looks like it is now "RE31002".

Can you confirm @ethbib-susanne?

To fix this we need to replace the profile of the library in Wordpress and reset their password.

**Comment by ethbib-susanne** [comment]
You are right, J didn't realize the modification of the swissbib ID.

**Comment by klokan** [comment]
New library record created in WordPress, old deleted:
http://www.kartenportal.ch/library/RE31002/
