### ISSUE TITLE
More simplified admin interface for the libraries

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#26]
A comment from Susanne:

Please keep in mind that the word press admin interface for maps collections must be as simple as possible. There are still to many filter options displayed.

The workflow for publishing pictures will be as follows: the user in the map collections upload a picture in a highest possible image resolution. The image will be processed and inserted later by the administrator. Pictures will always have a predefined width-to-height ratio so a clipping of the whole image will be published. Another clip in a predefined width-to-height ratio is prepared for the blog overview page by the administrator.

**Comment by ethbib-susanne** [comment]
In the library profile section there should be an example or list of possible values after every field. For the example take the values of ETH-Bibliothek.

**Comment by klokan** [comment]
Related are the changes of Look & Feel and dashboard mentioned in #63

**Comment by klokan** [comment]
Elements which should be removed / adjusted are marked:
![admin-remove](https://f.cloud.github.com/assets/59284/584355/8b95ad9c-c914-11e2-8e51-f6a8c85092b7.jpeg)

**Comment by klokan** [comment]
Implemented.
