### ISSUE TITLE
Link styles

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#260]
The evaluation of Kartenportal.CH showed that we have a huge consistency problem concerning link styles. Please check all links and add the correct style tags.

Style for links was defined as blue underlined for internal links and blue underlined followed by a little arrow for external links (see table for examples).

External Links inside buttons should be followed by an arrow.

![link_extern_button](https://cloud.githubusercontent.com/assets/4223790/3172219/f03cc06a-ebd1-11e3-83a3-594479727890.jpeg)

Please note that the arrow of an activated external link doesn't have the correct color.

Please note that url's starting with "https:" are not recognized/displayed as external links (Example page services - search)

![darstellung_links](https://cloud.githubusercontent.com/assets/4223790/3172101/2ab6acb2-ebd0-11e3-8e8d-4a02bfa991db.jpeg)

**Comment by klokan** [comment]
I expect to receive a list of similar requests for new development as a result of the usability evaluation. Does this work has a confirmed budget already?

Where shall we track the time for such development?

The maintenance and hosting fees for 2014 for Kartenportal.CH is not yet confirmed, nor signed and paid. Can the contract part of this request be resolved first please? Thank you!

**Comment by klokan** [comment]
Implemented: new white icons, application of changes in the geosearch, deployment. Done in 2:35.
Updated for using font on retina displays (another ~0:30).

Still missing: modifications in Wordpress - more complicated (compiled CSS via LESS).

**Comment by klokan** [comment]
Points 1.3 and 1.5 solved properly in Wordpress / Blog with #280
