### ISSUE TITLE
URGENT: Modified coordinates not updated in Kartenportal.CH

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#261]
The coordinates of the following records have been corrected at ETH library 1 month ago. The modifications are visible in swissbib but not in Kartenportal.CH:

http://suche.kartenportal.ch/#id=133924440
http://suche.kartenportal.ch/#id=166877336

**Comment by klokan** [comment]
Scheduled for review by @keosak.

**Comment by keosak** [comment]
Our database of incremental updates from OAI-PMH said that these records were last updated at the beginning of this year. I have done a completely new harvest, and there they have last updates at the end of May. I will re-create the MapRank database from this new harvest, but I don't see this as our fault. We rely on _incremental_ updates from OAI-PMH, and this is part of the contract. Downloading a whole new database every now and then is not a solution.

I have no answer as for why the updates didn't propagate to us, and I recommend you take up this issue with whoever is maintaining the OAI-PMH server. As I recall, it had some issues during May, being non-responsive or returning completely nonsensical data.

**Comment by ethbib-susanne** [comment]
This will have to be analyzed in collaboration with swissbib. You are right that you have count on reliable database information.

**Comment by klokan** [comment]
We have done additional research on this ticket.

The OAI service provided by SwissBib has been broken in the week 26-30 May. They probably made some large changes on OAI and destroyed the service in a sense that it reported a wrong XML files during that period (while it was not down for maintenance).

The above mentioned two records were changed in SwissBib exactly on 27th May and this caused the reported problems.

Our system survives unavailablility of the SwissBib incremental updates (remote service down, etc), but in case the OAI is broken in an unpredictable way we can't guatentee a correct functionality.

**If this should not happen again then SwissBib OAI-PMH must always provide correct incremental update on the production URL. If large updates are done on SwissBib OAI-PMH side it is better to turn the whole OAI-PMH service down completely (this we should correctly handle) then to provide incorrect answers.**

If this will not be the case, we must manually restore the database after their OAI-PMH is available again.
