### ISSUE TITLE
Records with more than one field 034

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#262]
J have a suspicion that records with more than one MARC field 034 are not displayed in Kartenportal.CH. According to the specification (F.33) there should be two records in Kartenportal.CH each showing one extent of map:

Examples:
https://www.swissbib.ch/Record/184756758
https://www.swissbib.ch/Record/184728819

**Comment by klokan** [comment]
This has been unfortunatelly a bug appearing after migration of the system to a new server.
It is fixed now and should not appear again. Thanks for reporting.
