### ISSUE TITLE
Settings and functions in Wordpress after update

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#267]
FROM:zb
Text formatting settings in the Wordpress interface have changed after the update.

Please hide the text menu. 

In the icons menu following icons should be visible (according to the setting before the update):
-   Bold
-   Citation
-   Standard numeration •
-   Insert link
-   Remove Link
-   Back
-   Forward

**Comment by klokan** [comment]
FROM:zb
Susanne says that the text menu should be hidden, while the icons menu should still be displayed.

She says that the Insert Text Tool should be visible, too, in addition to the 7 icons mentioned in the previous comment of 12 August.

It should be ensured that the configuration does not change during a future update.

**Comment by JackuB** [comment]
Menu has been simplified again.

![snimek obrazovky 2014-08-29 v 15 35 41](https://cloud.githubusercontent.com/assets/1788727/4090792/6f5df9ac-2f81-11e4-8be4-6ad2362ec163.png)
