### ISSUE TITLE
Inserting Google places in Wordpress

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#268]
FROM:zb
After the Wordpress update it is not possible anymore to insert Google places for events. Please fix.

**Comment by JackuB** [comment]
I fixed missing dependency that prevented map from loading in edit event screen.

Other than that: venues can be added/edited. Selected venue in post will be shown on front.

Can this be closed or bug was something else?

**Comment by ghost** [comment]
FROM:zb
The bug has been reported by Susanne. It seems that the reported bug has been fixed since. Please close this ticket.

**Comment by klokan** [comment]
Closed.
