### ISSUE TITLE
Logo sharpness

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#27]
J have the impression that the logo is not very sharp.

![logo](https://f.cloud.github.com/assets/4223790/459199/e3533fe2-b3fa-11e2-88c4-411260b4d5b6.jpg)

**Comment by klokan** [comment]
We plan to display it in vectors at later point. Have a look at: http://dev.klokantech.com/kartenportal/

**Comment by klokan** [comment]
Logo replaced with the vector rendering.
