### ISSUE TITLE
/press/ section on Kartenportal.CH

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#273]
For the official project announcement for media we need to add a special page with structure similar to:

http://pressandpolicy.bl.uk/Press-Releases/Crowdsourcing-the-past-georeferencing-website-puts-historic-maps-in-their-place-5f1.aspx
or
http://epsg.io/about

It is a one-time page only. It will be avialble in 4 languages - and must link the images and zip.
Either we create it as a static page (HTML/CSS) or we create an administration page for it - avilable only to admin.

**Comment by JackuB** [comment]
May it be static page like http://www.kartenportal.ch/impressum/ ?

I've already created /press in admin. If we decide to change it's layout (let's say to full-width, we can do it by changing page template)

**Comment by klokan** [comment]
We may need exactly the same layout, but with a custom content in the sidebar. Both the main body and the sidebar must be translatable.

**Comment by ghost** [comment]
FROM:zb
This issue to be fixed until evening of 20 October at the very latest. 

Kartenportal's Admin will then upload some images and text files. Or should these files sent to Klokan Tech in order to be uploaded at short notice?

**Comment by klokan** [comment]
http://www.kartenportal.ch/press/ exists and should be editable by the kartenportal user, since September 4th.

**Comment by ghost** [comment]
FROM:zb
Sorry, we did not realise before that this section is ready. We now started with the upload of the press releases and the screenshots. 

Feature tested and accepted.
