### ISSUE TITLE
K.1.1 - Thumbnails from MARC 856$u

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#274]
If a link in the MARC field 856 subfield u is a picture of e-manuscripta or e-rara, thumbnail from Swissbib is copied and displayed in the detail view. 

eg thumbnail for 
http://suche.kartenportal.ch/#id=197883192 
will be taken from
https://www.swissbib.ch/Record/197883192)

**Comment by klokan** [comment]
The given example on SwissBib is using this thumbnail link:
https://externalservices.swissbib.ch/services/ImageTransformer?imagePath=http://opac.nebis.ch/thumb_zb/1/MK_0181_01_tn.jpg&scale=1

It looks like we have to construct it from the field 

```
956 4       |B NEBIS  |C ZAD50  |D EBI01  |a Z04  |u http://opac.nebis.ch:80/F?func=service&doc_library=EBI01&local_base=EBI01&doc_number=005383341&line_number=0001&func_code=DB_RECORDS&service_type=MEDIA  |y Karte  |x THUMBNAIL  |f MK_0181_01_tn.jpg  |q jpg  |d $zad50_dev/zad50/objects/thumbnail/1 
```

where is mentioned the `MK_0181_01_tn.jpg`.

We need exact specification of rules for usage of the thumbnails in SwissBib. To be discussed with SwissBib people.

**Comment by klokan** [comment]
It is still unclear how to get the URL to the thumbnail from MARC:
http://opac.nebis.ch/thumb_zb/1/MK_0181_01_tn.jpg

**Comment by klokan** [comment]
The information may be on the SwissBib Wiki, but we (user "PetrP") don't have access to it now:
http://www.swissbib.org/wiki/index.php?title=Thumbnail_locations

**Comment by klokan** [comment]
It seems the only proper way how to display thumbnails visible in SwissBib is to reimplement (and keep in sync) their code from:
https://github.com/swissbib/vufind/blob/development/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php#L548

**Comment by klokan** [comment]
Markus, this is now being implemented. To be finished and available online later today.

**Comment by keosak** [comment]
I have re-implemented thumbnail parsing from the PHP code mentioned above. The code is now deployed and the new database is online. There are 7611 records with thumbnails now, up from 4344 before.

**Comment by klokan** [comment]
Finished and deployed.
Markus, please verify.

**Comment by klokan** [comment]
We have to keep the source code in sync in future.
This is the page where we have to check the availability of changes:

https://github.com/swissbib/vufind/commits/development/module/Swissbib/src/Swissbib/RecordDriver/SolrMarc.php

**Comment by ghost** [comment]
FROM:zb
Clicking on a thumbnail in Detailansicht should open a new window if there is an URL behind the thumbnail.

**Comment by klokan** [comment]
Done. Deployed.
