### ISSUE TITLE
K.1.2 - Scale Filter: prevent collision

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#275]
The scale in the box on the right must always be smaller than the scale in the selection box on the left. The reverse setting is newly impossible.

This is how it should be:
![richtig](https://cloud.githubusercontent.com/assets/8998570/4494045/71488d6c-4a4e-11e4-8f6f-87bd3451fc75.png)

And this is how it CANNOT be:
![lastenheft und technische offerte 2014 v0_1](https://cloud.githubusercontent.com/assets/8998570/4494013/3553b70a-4a4e-11e4-909c-ccad4943dead.png)

**Comment by klokan** [comment]
Implemented as disabled valued - dynamically set. Deployed.

**Comment by ghost** [comment]
FROM:admin
Markus, could you please verify?

**Comment by ghost** [comment]
FROM:zb
Tested and accepted.
