### ISSUE TITLE
K.1.4 - Map series: Merging via MARC 490$9 otherwise 490$a

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#277]
Linking the maps with the map series based on MARC field 490 show subfield 9 
If no subfield 9 is present, subfield a is used.

**Comment by keosak** [comment]
@petrsloup The "series" field in the MapRank JSON reponse is now a series identifier. It should be used to compute the MD5 hash for series visualization as before. For display, there is a new field "series_name".

**Comment by klokan** [comment]
The priority of fields is: 490$9 then 490$a then 830$a

**Comment by ghost** [comment]
FROM:admin
Markus, could you please verify?
