### ISSUE TITLE
Font size Headings

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#28]
For my perception the headings are too big. For the reason of beeing consistent J would prefer the blue color (same color for all headings).

![titel_font_size](https://f.cloud.github.com/assets/4223790/459207/35004d62-b3fb-11e2-8fed-23e8da334cf7.jpg)

**Comment by klokan** [comment]
We are unifying the design - as discussed on the meeting on May 30th. This title is going to be removed. Title will appear in the left sidebar in all pages.
