### ISSUE TITLE
S.1.2 - Collections web: css / design / text changes

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#280]
Long links to the website are shown only up to the maximum width of the Info column (IE bug only?) 

The full link is displayed on the hoover with a mouse

Instead of the button "Visit site" will be just the title "Website" 

The icon before the title "E-mail" will be removed

![design](https://cloud.githubusercontent.com/assets/8998570/4494498/8066571c-4a52-11e4-991f-f32347957b96.png)

**Comment by klokan** [comment]
Should be fixed by now:
http://www.kartenportal.ch/en/library/AKB/

**Comment by klokan** [comment]
Extra testing in IE 9, shortening of the url runs fine.

**Comment by klokan** [comment]
Markus, could you please verify?

**Comment by ghost** [comment]
FROM:zb
Tested and accepted.
