### ISSUE TITLE
B.1.1 - Blog: linking the profile to the Event records

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#281]
The name of the collection that has captured an event will be linked with the profile (such as the posts under "News" and "Card portraits").

![b 1 1](https://cloud.githubusercontent.com/assets/59284/4644404/8fe7e68a-545a-11e4-818a-8c4f9dd4ed2c.png)

**Comment by klokan** [comment]
The originally displayed name of the venue has been now replaced by the author of the post (with a link to the profile).
The changes propagated to the event detail page as well, when on the top is now only date and the name of the venue was added bellow to the venue address.

**Comment by klokan** [comment]
Markus, could you please verify?

**Comment by ghost** [comment]
FROM:zb
We should find a small (I hope) workaround when the library is called "Kartenportal" (for example top event at http://www.kartenportal.ch/blog/event/ Panorama Thun). Clicking that "library" name links to its profile, but there is nothing of interest at all. Therefore we suggest to suppress the link if the "library" is "Kartenportal".

**Comment by klokan** [comment]
Hiding "Kartenportal" author on events - as requested in #281
implemented in 540b765f720ee88c3f28df6336e1628639a61aa7

**Comment by ghost** [comment]
FROM:zb
Tested and accepted.
