### ISSUE TITLE
Autocomplete direct Enter issue

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#282]
By the usability test was identified a bug in the autocomplete.

It may happen the when Enter is hit by the user an unrelated item may be displayed because it was selected for the old phrase.

(reported by Petr Pridal)

**Comment by klokan** [comment]
Deployed.

**Comment by klokan** [comment]
Markus, could you please verify?

**Comment by ghost** [comment]
FROM:zb
Have not seen that bug myself and was unable to reproduce it before and now.
