### ISSUE TITLE
Hide calendar

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#285]
FROM:zb
On short notice we have decided that the calendar should be hided for the present release. The navigation then looks like this:

Blog
Alle Einträge
Aktuell
Veranstaltungen
Kartenporträts
Tags
Suche
RSS

Do accordingly in the other three language versions.

Note that further developments in connection with calendar and events are scheduled for the 2015 developments under items A.1.4, B.1.2 and B.1.4 (see Lastenheft). We therefore propose to consider this small issue as an advance part of item B.1.2 and to pay for it together with the other 2015 developments.

**Comment by klokan** [comment]
The calendar widget is now hidden.
