### ISSUE TITLE
Bug: Detailansicht layout when libraries are missing

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#286]
FROM:zb
There is a layout bug in Detailansicht of records which have no assigned library. Example: http://suche.kartenportal.ch/#id=172404916

Because there is no library no address can be shown, i.e. there is only one row of information instead of two at the right of the catalogue button. The layout should be flexible in order to fit the button completely between the upper and lower dividing lines.

**Comment by klokan** [comment]
Change in compiled JavaScript required. This is not in templates.
After implementation we need to check also the example reported in #252.

**Comment by petrsloup** [comment]
@klokan Layout fixed in the CSS. To be deployed.

**Comment by klokan** [comment]
Deployed.
