### ISSUE TITLE
Bug: Library list

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#289]
FROM:zb
The library list in the library filter suddenly disappeared. The only item currently on display is "all Swiss libraries". The library list must be visible at any time. 

The bug was first noticed at 10 February 2015 using IE 10 (other browsers not tested).

**Comment by klokan** [comment]
@keosak - please verify and fix ASAP. Thanks!

**Comment by keosak** [comment]
On February 10, the OAI-PMH server was malfunctioning, returning HTTP status code 500 to all requests. This crashed the update process and caused an empty `swissbib.js` to be generated as a result. The OAI-PMH server is working now and I have started the update procedure manually. I have also modified the process to be fail-safe in this scenario.
