### ISSUE TITLE
Search detail popup look&feel (F.20 / Trefferliste)

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#29]
- [ ] The MARC elements have to be in the order as shown in the attached images.
- [ ] The wording of the labels like Author, Edition etc. has to be as shown in the attached images.
- [ ] In the Trefferliste there is only a single label, namely that for the Series. Therefore the series is displayed in normal font, not in italics.
- [ ] There is no additional line spacing between the above-mentioned MARC21 elements.
- [ ] If a given MARC element is empty (e.g. when there is no edition statement), its label does not show up at all.

**Comment by klokan** [comment]
Related images for Detail Popup are already in the internal ticket: https://github.com/klokan/maprank-client/issues/6

**Comment by klokan** [comment]
Markus, MapRank does not see the MARC fields directly, we can't access these - all records are mapped into DublinCore during indexing, e.g. Title, Publisher, Creator, Contributor, and possibly additional custom fields (Series, Sheet, etc.)

Mapping between DC and MARC fields has been provided by you before and we are using it now. We have made best effort to improve it based on this original request in January - but still, what you are requesting now is partly incompatible. We have to display the available indexed data.

**Comment by zb-markus** [comment]
Mapping
My request is not regarding the mapping or the data display, it only asks for the labelling. For example, MARC field 245 $c contains the author, which is mapped to either DC contributor or DC creator. That is OK. But our users need to see the label "Author" in the Geosearch frontend. That's it. In short: Let the MARC/DC mapping be as it is, but present the data in the Geosearch frontend in the wording and punctuation as requested.

**Comment by klokan** [comment]
Required changes on the server side implemented. Work on the client side started.

**Comment by klokan** [comment]
This should be fixed now.
