### ISSUE TITLE
K.1.14 Translations

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#291]
FROM:zb
de: Karten für diese Region  (instead for: Karten für diesen Ort)
de: xx Karten gefunden

en: Maps for this area
en: xx maps found

fr: Cartes pour cette région
fr: xx cartes trouvées

it: Mappe per questa zona
it: xx mappe trovate

**Comment by petrsloup** [comment]
Deployed to the temporary hosting:
http://klokan.github.io/maprank-client/
http://klokan.github.io/maprank-client/index.de.html
http://klokan.github.io/maprank-client/index.fr.html
http://klokan.github.io/maprank-client/index.it.html
