### ISSUE TITLE
K.1.16 Translations

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#292]
FROM:zb
de: Kartenwerk-Ansicht

en: Map series view

fr: Vue des séries de cartes

it: Modo di serie delle mappe

**Comment by ghost** [comment]
FROM:zb
The sheet number label in the grey part of the map series info box should be translated as well. 

de: Blattnummer: xx

en: Sheet number: xx

fr: Numéro de feuille: xx

it: Numero del foglio: xx

**Comment by petrsloup** [comment]
Deployed to the temporary hosting:
http://klokan.github.io/maprank-client/
http://klokan.github.io/maprank-client/index.de.html
http://klokan.github.io/maprank-client/index.fr.html
http://klokan.github.io/maprank-client/index.it.html
