### ISSUE TITLE
Logins for new user

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#293]
FROM:zb
Please create logins for Roman Walt (eth-roman) who is the successor to Susanne in ETH. Logins are needed for:
- clientportal (this site)
- map search translations toolkit

His e-mail address is roman.walt@library.ethz.ch

Thank you.

**Comment by klokan** [comment]
I have submitted Roman the access information to clientportal - and his email address is now set as the main contact for ETH.

The Map Search translation toolkit is not in active use now - for the new development.
