### ISSUE TITLE
Start page title change (layout with title spanning two columns)

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#294]
FROM:zb
As we now display 2 events on the start page that may come from the same category, we find it confusing that the overall news title is "Latest news", which is similar to one of the Blog categories ("News") but seems to exclude the second Blog category ("Exhibitions and Events"). Also, the overall news title should optically belong to both columns, i.e. the grey dividing line should only start at the top edge of the events titles. See mockup sent by e-mail.

Rewording of the overall news title on the start page:

de: "Nachrichten und Veranstaltungen" (instead of: "Aktuell")
en: "News, exhibitions and events" (instead of: "Latest news")
fr: "Nouvelles et événements" (instead of: "Actualités")
it: "Novità ed eventi" (instead of: "News")

Rewording of some Blog categories:

de: "Nachrichten" (instead of: "Aktuell")
en: "Exhibitions and events" (instead of: "Exhibitions and Events")
fr: "Nouvelles" (instead of: "Actualités")
it: "Novità" (instead of: "News")

Blog categories not mentioned above remain as before.

**Comment by klokan** [comment]
OK. This is a new request. Change of the existing responsive layout may be required here - not estimated in the original ZB contract. 
Time on this ticket to be tracked to Kartenportal Maintenance 2015.

![image001 2](https://cloud.githubusercontent.com/assets/59284/7041653/7c891a90-dddb-11e4-8fd9-85c58d848d55.png)

**Comment by ghost** [comment]
FROM:zb
How many hours, approximately?

**Comment by klokan** [comment]
Around 2 hours (changes in layout with new translated texts of variable length, testing before deployment in multiple browsers, deploy).

**Comment by ghost** [comment]
FROM:zb
OK, go ahead.

**Comment by klokan** [comment]
The work on this has started. After 1 hour we have to correct the estimate unfortunately.
Total required time is 4 hours - including testing in different browsers and deploy.
Shall we continue or stop?

**Comment by ghost** [comment]
FROM:zb
Well ... OK, go ahead. 4 hours max on 2015 maintenance.

**Comment by ghost** [comment]
FROM:zb
We are looking forward to hearing whether this issue can be deployed and closed soon.

**Comment by daliborjanak** [comment]
Sorry for the delay, I was out of office. I changed desired composition and I also updated translations. Please review

**Comment by ghost** [comment]
FROM:zb

Start page is now fine. Do not forget the Blog (see opening remark of this issue).

**Comment by daliborjanak** [comment]
Thanks for reminding. I renamed also blog now

**Comment by ghost** [comment]
FROM:zb

Still to do in the Blog (en)
- the menu item should be "Exhibitions and events" (it is still "Exhibitions and Events")
- the grey title top right should be identical "Exhibitions and events" (it is still "Events").

**Comment by daliborjanak** [comment]
Changed.

**Comment by ghost** [comment]
FROM:zb

Tested and accepted.
