### ISSUE TITLE
K.2.1 Position of red rectangle and arrow design

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#296]
FROM:zb
The new red rectangle that points the user to the result list should overlap the place input field as shown in the Lastenheft/technical requirements. Currently it is close to the result list. According to our tests, users do not see it because they still focus the place input field. Therefore, the red rectangle must overlap the place input field or be at least very close to it. 

In addition, the arrow should fit into the design of other Kartenportal controls. It should be "heavier". Why not reuse the design of the up and down arrows in the records detail view in the map search?

**Comment by klokan** [comment]
![screen shot 2015-04-08 at 11 18 00](https://cloud.githubusercontent.com/assets/59284/7042298/25a79e30-dde1-11e4-8911-33b8c749488a.png)

**Comment by petrsloup** [comment]
Modified according to the mockup and deployed to the temporary hosting.

**Comment by klokan** [comment]
Markus - could you please comment?

The implementation is visible in an incognito mode of a browser (simulating first visit) at http://klokan.github.io/maprank-client/

It looks like:
![screen shot 2015-04-15 at 08 40 26](https://cloud.githubusercontent.com/assets/59284/7153417/8fdce160-e34b-11e4-84d3-b2097539b066.png)

**Comment by ghost** [comment]
FROM:zb
Tested and accepted.
