### ISSUE TITLE
K.2.3 Attributes advanced search

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#297]
FROM:zb
The advanced search part of the attributes window should retract 
- either when the user deletes all attributes by clicking on the [x] control in the blue box
- or when the user leaves the window without filling in any attribute at all

This is to make sure that the attribute window is always in its default position when it is not in use. Currently, the advanced search part remains open even when the user has only clicked on the "Advanced search" link out of curiosity. That behaviour is cumbersome because the user is unable to close that advanced search part after he has found out that the default is good enough.

**Comment by petrsloup** [comment]
Implemented and deployed to the temporary hosting.

**Comment by ghost** [comment]
FROM:zb
Tested. Please close.
