### ISSUE TITLE
Bug: Scale filter handling

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#299]
FROM:zb
The scale filter consists of 2 pop-ups. When one of them is used, the second is blocked until the window is closed and reopened or until the scale filter is reset by clicking the [x] control.

IE only, other browsers not affected.

**Comment by klokan** [comment]
Could you please provide an information about which version of IE is affected?

I expect this is a bug production version of the system at http://suche.kartenportal.ch/ - not a bug related to new development in ZB contract, correct?

**Comment by ghost** [comment]
FROM:zb
Seen in IE10.

This seems to be a bug in the productive system that is not newly introduced with the current developments. Therefore this goes to the 2015 maintenance budget.

**Comment by petrsloup** [comment]
I'm not able to reproduce this bug in any browser (including IE 9, 10, 11) at http://suche.kartenportal.ch/ or http://klokan.github.io/maprank-client/. I tried searching for possible causes of this problem, but didn't find any definite reason for this behavior.

What version of Windows is running on the affected computer? Is it a touch-enabled device or a regular computer? Have you seen this problem on more than the one computer?

**Comment by ghost** [comment]
FROM:zb
We made further tests. It seems that the bug only occurs in IE10 running on Citrix clients or on special Windows Server installations. Other (stand-alone) computers are indeed not affected. It would therefore be disproportionate to work on this issue anymore. Please close.
