### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#3]
The contact page linked from the footer should contain a simple contact form, probably with recaptcha to protect against SPAM / robot submission.

http://kartenportal.klokantech.com/contact/

**Comment by JackuB** [comment]
Are fields for contact form specified?
Right now Name, Email and Message is active. Will we want any other?

Also (multilanguage) text for confirmation email is required (e.g. "We received your message..")

**Comment by klokan** [comment]
This should be appropriate for now.
What about SPAM protection and configuration of the address where we deliver email?
How are the emails submitted? Can we use custom SMTP with authentication (such as GMail account SMTP) instead of the direct submition from the server (which could be possibly dangerous).

**Comment by JackuB** [comment]
For SMTP support we should switch to http://www.gravityforms.com/ (they also have improved multilang support)

Dumb, but working version is live here: http://kartenportal.klokantech.com/contact/

**Comment by klokan** [comment]
Design provided, it is waiting for implementation now.

**Comment by JackuB** [comment]
http://kartenportal.klokantech.com/contact/ done

**Comment by klokan** [comment]
Look & feel - alignement with the top bar, blue color of the portal on the button, styling for error messages.

**Comment by JackuB** [comment]
Done

**Comment by klokan** [comment]
TODO: Fix alignment for small screen.

**Comment by JackuB** [comment]
Done
