### ISSUE TITLE
Links to e-Rara, e-Manuscripta and Ryhiner in detail window

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#30]
The links to e-Rara, e-Manuscripta and Ryhiner are not specifically marked in the SwissBib. 

@zb-markus: 
If we should display these we need a clear rules how to recognise and extract these from the SwissBib MARC.

Could you please provide these?

**Comment by klokan** [comment]
Example record which should contain a link to Ryhiner high-res image: http://dev.klokantech.com/kartenportal/#id=044243618

**Comment by zb-markus** [comment]
e-rara and e-manuscripta links are in MARC field 856.

Example records that should show up in Geosearch and contain e-rara link:

http://aleph.unibas.ch/F/?local_base=DSV01&con_lng=GER&func=find-b&find_code=SYS&request=002621861
http://www.e-rara.ch/doi/10.3931/e-rara-12277

http://aleph.unibas.ch/F/?local_base=DSV01&con_lng=GER&func=find-b&find_code=SYS&request=005203978
http://www.e-rara.ch/doi/10.3931/e-rara-13245

**Comment by klokan** [comment]
Example record for e-rara:
http://search.kartenportal.ch/#id=045311757

Example record for e-manuscripta:
http://search.kartenportal.ch/#id=149915888

Example record for Ryhiner:
http://search.kartenportal.ch/#id=044243618

In other words: our JSON record 'viewer' should contain first MARC field 856$u. These links are not ideal, but it is a first step.

@zb-markus Problems: e-rara/e-manuscripta does not have thumbnails, ryhiner links are linking preview jpeg after confirmation. The ideal would be to have links to zoomable viewers in 856u in SwissBib, but is it doable?

**Comment by klokan** [comment]
Thumbnails to fit into 250x250px on top of the title in the detail window. The thumbnail is clickable.
Under the detail metadat and above catalogs is "View this map" link.

**Comment by klokan** [comment]
Implemented in b78f09d. Demo links:

Example record for Ryhiner:
http://search.kartenportal.ch/#id=044243618

Example record for e-rara:
http://search.kartenportal.ch/#id=045311757

Example record for e-manuscripta:
http://search.kartenportal.ch/#id=149915888

**Comment by zb-markus** [comment]
We expect that the link called "View this map" is designed as a button, in the same size like the "Catalog" and "Metacatalog" buttons below but perhaps in another colour? If "View this map" is too long, there are two solutions:
- enlarge catalog/metacatalog buttons
- use "View", "Large image" or "Full size" instead

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
