### ISSUE TITLE
Bug: clientportal e-mails

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#300]
FROM:zb
When I open a new issue, an e-mail is sent @zb. At any further comment, an e-mail is sent both @zb and @eth. The latter behaviour is fine. Please check why at opening no e-mail is sent @eth, although the label @eth is assigned automatically.

Conversely, when ETH opens an issue, e-mails should be sent both @eth and @zb

**Comment by ghost** [comment]
FROM:zb
Compare #290 last comment.

**Comment by klokan** [comment]
Submission of the email to other customers on the same project after creating a new ticket in ClientPortal is fixed now.

Emails should be delivered to Roman from ETH.

Ticketing system is switching to internal project (for Kartenportal 2015 project in ClientPortal) for the new tickets so the @eth user should not be alerted by GitHub in future.
