### ISSUE TITLE
Search detail popup: Permalink and Print icon

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#31]
@zb-markus:
Do you really want to have in the popup window the icons for Permalink and Print?
Where exactly it should be placed and what should happen if you click on these?

IMHO there is no need for Permalink and Print icon. The link in addressbar is automatically updated and it is the permalink. The print functionality is part of every web browser - available via File->Print menu or similarly. Do you really want to have additional icons in the detail page itself?

Shall we prepare the printing output specifically (so that it looks good for the detail page - with only the relevant information and no maps or result list, possibly with a Kartenportal header and a custom footer, etc.?

BTW Work on print-out layouts has not been budgeted I think.

**Comment by zb-markus** [comment]
Compare Lastenheft F.20: We request icons for permalink and printing somewhere within the Detailansicht window. I propose them just below the cross for closing the window:
x   [tooltip: close this record]
○○ [tooltip: permalink of this record]
□  [tooltip: print this record]

The permalink is naturally the same as in the browser adressbar. After clicking the icon the permalink could be shown in a small box opening to the left or below the icon, labelled thus:
Permalink of this record: http://dev.klokantech.com/kartenportal/#id=204472571

The printing icon should enable the user to print the Detailansicht window. There is no need to specifically design the output, simpliy print the content of the window including the visible permalink. More is not necessary.

Of course, make your own icon design that fit into the overall design concept.

**Comment by klokan** [comment]
Styles for printing are now deployed - print via File->Print looks much better now.

**Comment by klokan** [comment]
Bottom left, gray, icons to be added into the font.

**Comment by klokan** [comment]
Done in 4e9ae1f

**Comment by zb-markus** [comment]
We expect that by clicking the permalink button the permalink is going to be displayed next to the cursor. This may happen in a small overlay window. Currently, the Geosearch vanishes completely, the background of the browser window is white throughout and the text "null" is displayed in the upper left corner. We insist that the permalink display in the browser adressline is ot enough and that the permalink must be visible close to the button after clicking it.

The print functionality is well done.

**Comment by klokan** [comment]
In what web browser this happens for Permalink click?

**Comment by zb-markus** [comment]
IE 8.0.6001.18702

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
