### ISSUE TITLE
OpenStreetMap in the GeoSearch (F.05)

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#32]
Show an icon in order to switch between Google Maps and OpenStreetMap (see Lastenheft F.05).

**Comment by klokan** [comment]
We can easily add this switch, but this would not really solve the F.05 point, because the GeoSearch would still use Google Maps API with the OSM.
We continue to work on the OpenLayers V3 rewrite for the whole GeoSearch interface which is the proper solution.

**Comment by zb-markus** [comment]
"We continue to work on the OpenLayers V3 rewrite for the whole GeoSearch interface which is the proper solution."

OK, this is according to Lastenheft.

**Comment by klokan** [comment]
Initial implementation at http://dev.klokantech.com/kartenportal/ol3/ - made with OpenLayers V3, modern browsers are required.

**Comment by klokan** [comment]
The client is now reimplemented to support dynamically both Google Maps API V3 and the OpenLayers V3. It is possible to switch dynamically and keep the same instance and URL.
We have to add the missing controls and deploy this to dev.klokantech.com.com/kartenportal/ now.

**Comment by klokan** [comment]
Done and deployed to http://search.kartenportal.ch/

**Comment by zb-markus** [comment]
Does not work until OpenLayers v3 is available, is that correct? I find it better to remove the OSM button until it can be correctly implemented.

**Comment by klokan** [comment]
It works well in IE9+ and all other modern browsers. Support for IE8 should be added by OL3 team hopefully before FOSS4G in September.

This has been HUGE amount of work for us and it seriously complicates the code of the interface. But now it is done. Shall this be hidden for now?

**Comment by zb-markus** [comment]
Sorry, I have forgotten to mention that this is IE8-specific. Ok then, let the button be as it is. But please let this issue open, so I can see in the open issues list that I need to have an eye on it until September.

**Comment by klokan** [comment]
We started to work on reimplementation into LeafletJS library instead of OpenLayers V3 - to be able to close this ticket as well.

**Comment by zb-markus** [comment]
Now OSM is working also in IE8!

**Comment by klokan** [comment]
Yes. We are fixing some last small issues and this ticket can be closed then.

**Comment by klokan** [comment]
The implementation in Leaflet should be now finished. Please test.

**Comment by zb-markus** [comment]
Tested and accepted.
