### ISSUE TITLE
Help icon with label "Help"

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#34]
The help icon should have a label such as "Help". This is in order to be consistent with the design and labelling of the filters.

**Comment by klokan** [comment]
I do not agree.

Help icon is not one of the filters - it is different function. We have problem with space on small screens (1024x768) already. If we add the responsive design functionality we can add the label which will be visible on larger screens and hidden on smaller, but in this moment I would suggest to keep the icon without a label.

@zb-markus: please confirm this decision. If you really want the label, let us know and we make it.

**Comment by zb-markus** [comment]
I agree to show the label on larger screens and to hide it on smaller screens. As long as there is no responsive design, the Geosearch is intended to be used on larger screens with enough space for the label. So, please add a label called "Help".

**Comment by klokan** [comment]
OK. Scheduled to be done under internal ticket: https://github.com/klokan/maprank-client/issues/36

**Comment by klokan** [comment]
Done in 86446db
