### ISSUE TITLE
The library filter

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#36]
The library filter should display the most important map libraries immediately after clicking the icon. The order is alphabetically:

ETH Zürich
LIB4RI
Schweizerische Nationalbibliothek
UB Basel
UB Bern, Zentralbibliothek
Zentralbibliothek Zürich   [omit: Kartensammlung]
more libraries …

After the user clicks on"more libraries …", the full list opens. The full libraries list is available from Swissbib. If possible the original Swissbib list is filtered in order to show only libraries that actually hold maps. The full list is ordered alphabetically.

**Comment by klokan** [comment]
Scheduled for development, under internal ticket:
https://github.com/klokan/maprank-client/issues/34

**Comment by klokan** [comment]
Initial implementation done - but the data are in this moment hardcoded inside of the HTML. We need this to be dynamically updated during the OAI-PMH harvesting and available in a suitable JSON formatted list / lookup table from the MapRank Server or Kartenportal website.

**Comment by klokan** [comment]
The possible look&feel I was suggesting would be similar to http://harvesthq.github.io/chosen/ - first exampe, e.g. hovering+click for selection and input box on the top for filtering of the list.

**Comment by klokan** [comment]
The styling of the toolbar must be finished - I expect the selected libary be in blue and the search box under the list. Scrollbar always visible and scrolling only in the list of libraries (over the filter input)

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Initially we wished the 6 top libraries shown only, with "more" at the end. The now implemented search box is fine and accepted. 

However, we think that all libraries at the end of the list with only 1 or 2 records (approx. 80 and 60 libraries respectively) are omitted completely. This is rather akward "noise" without any relevance.

**Comment by klokan** [comment]
As you wish. We will show only libraries which has 3 and more maps.

**Comment by petrsloup** [comment]
Done.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
A new bug appeared: the filter box does not work anymore. Any text entered into the library filter box should immediately filter the library list. Seen in IE8/9.

**Comment by klokan** [comment]
We have seen this bug earlier today and it is fixed now in the code.
It is going to be visible after we deploy new version of the MapRank Client.

**Comment by klokan** [comment]
Done.

**Comment by zb-markus** [comment]
Tested and accepted.
