### ISSUE TITLE
Maps crossing dateline (F.06/08)

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#38]
Please make sure that all maps crossing the 180th meridian are shown. Currently all of them are still missing!

Reproduction: Center search map on Russia, and there should be loads of maps crossing the meridian. Actually I found a single record covering the meridian, but that one was wrongly catalogued as going from E 120° to E 280° …

Correct records are:
http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=000666014
http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=005470538
http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=004108234

**Comment by klokan** [comment]
This has been implemented on the server side already last year and on the client side via internal ticket:
https://github.com/klokan/maprank-client/issues/1

An example query with a first result as a map crossing date line:
http://dev.klokantech.com/kartenportal/#bbox=122.695313,14.944785,-109.335937,68.39918&q=&date_from=1750&date_to=2005&scale_from=&scale_to=&libraries=

There may be some issues with indexing from SwissBib.

@keosak: please review if the production server has the records Markus mentioned, and if these are available via direct query to the FastCGI server and let us know if the client should be changed to handle the request to server for maps crossing dateline somehow differently.

**Comment by zb-markus** [comment]
The example query mentioned above by Klokan (http://dev.klokantech.com/kartenportal/#id=196999804) contains unfortunately wrong data in 034 field. I have reported this to the responsible library for immediate correction. I was unable to find within Geosearch a correctly coded record crossing the 180th meridian.
