### ISSUE TITLE
External links must be marked with a special symbol via CSS

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#4]
We may need to add a plugin such as "External Links".

http://www.semiologic.com/software/external-links/

**Comment by JackuB** [comment]
Done

**Comment by klokan** [comment]
Temporary demo: http://kartenportal.klokantech.com/map/hullo-werld/ and link to Google.com

**Comment by klokan** [comment]
This file has a wrong color(not the same as textual links):
http://kartenportal.klokantech.com/assets/img/external.png
To be replaced.

**Comment by radimkacer** [comment]
![external2](https://f.cloud.github.com/assets/3808072/583875/89a5ac72-c904-11e2-8dd6-20807d4744d4.png)

**Comment by radimkacer** [comment]
![external20x20](https://f.cloud.github.com/assets/3808072/583900/4b2c3640-c905-11e2-8357-54f2c73d0858.png)

**Comment by klokan** [comment]
Second one is for retina - to be used with css background-size property.
Alternatively - we can render it as a font. The symbol is in the the font available at #57

**Comment by JackuB** [comment]
Implemented, tested on retina

**Comment by klokan** [comment]
Great!
