### ISSUE TITLE
Size of Detailansicht window

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#43]
The height of the Detailansicht window should be reduced. The window should not cover the filter bar and the help icon.

Actually, the window is in most instances still to big in comparison with its content. If it is reduced that the search map is visible above and below the window, the user would get more the feeling of a "temporary" overlay (see attached variant A).

![detailansicht_variant_a](https://f.cloud.github.com/assets/59284/544081/44a83e4a-c248-11e2-9565-08bf345eaeb5.jpg)

An even more advanced proposal has a blue line bordering the Detailansicht window. This gives the user the visual connection between window and the blue-marked record in the Trefferliste (see attached variant B). Please consider variant B as working base.

![detailansicht_variant_b](https://f.cloud.github.com/assets/59284/544082/550f62fe-c248-11e2-8a3b-565a3c7b358d.jpg)

Compare https://github.com/klokantech/kartenportal-tickets/issues/29 and https://github.com/klokantech/kartenportal-tickets/issues/31.

**Comment by klokan** [comment]
To be discussed personally before implementing it.

**Comment by zb-markus** [comment]
Related to the window size is the number of libraries shown. In the images above there is 1 library and Swissbib. But there are records with 10 or more libraries. In that case the end of the libraries list is out of the window. But clicking on the arrow does not help as the arrows are intended to browse through the Trefferliste. 

The solution is to show max. 4 libraries plus Swissbib. Compare images for Detailansicht in klokan/maprank-client#6. Space can also be saved when only the library names are displayed, not the complete postal addresses.

**Comment by klokan** [comment]
This has been resolved by the scrollable content of the detail window - and discussed on the meeting personally.
