### ISSUE TITLE
Attributes filter (Full text and Subject)

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#45]
The Full text filter should also work on MARC fields 6xx (subject fields).
Reproduction: Center map on Zurich, use Full text filter, type "Kind" - no records found. It should find http://dev.klokantech.com/kartenportal/#id=139639322 (Zürich für Kinder) which contains a 650 field with content "Kind".

Likewise, the Subject filter should work on MARC fields 6xx (subject fields). 
Reproduction: Center map on Zurich, use Subject filter, type "Kind" - no records found. It should find http://dev.klokantech.com/kartenportal/#id=139639322 (Zürich für Kinder) which contains a 650 field with content "Kind".

Compare Lastenheft F.10 for fields that should be taken into account for Full text and Subject filters.

**Comment by klokan** [comment]
DublinCore Subject needs to be added to fulltext and subject created by concatenation of all 6xx, 906c and 907c fields from MARC.
It should run with subject:abcdf via the attributes toolbox in the interface.

**Comment by klokan** [comment]
Work started.

**Comment by klokan** [comment]
Also related to fulltext:
We will have 'author' field with 245c - for displaying in the detail window
and field 'creator' with 100a, 700a - for fulltext search with creator:...

Change on both server and client is required.
Client implementation waits for the server and is internally tracked as: https://github.com/klokan/maprank-client/issues/6

**Comment by keosak** [comment]
I have added the "author" field (MARC 245c) to the JSON record. The "creator" (MARC 100a, 700a) and "subject" (MARC 6xx, 906c, 907c) fields are indexed but not in the JSON record. Closed in maprank-server/ba611839fd7daa3fce1ffcb78f2a128d11d058fc.

**Comment by zb-markus** [comment]
It is still not working in the test frontend. Typing "Kind" either in Full Text or Subject filters retrieves no maps (see initial post to this issue).

**Comment by klokan** [comment]
Unfortunately - there is regression. The GUI has been implemented and deployed but during testing the search queries for subject as "subject:Kind" as well as via fulltext "Kind" does not run anymore on the production server.

@keosak Please ensure the production server contains the related functionality and the complete SwissBib dataset has been reindexed for this to run. The GUI at http://search.kartenportal.ch/ is sending the correct queries now.

**Comment by klokan** [comment]
Finished and deployed.
