### ISSUE TITLE
Map Gallery (Wissenwertes Karten)

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#5]
Please find attached the texts and pictures for section „maps“ (things worth knowing):

https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWSMHM4WjNtaU11dGs/edit?usp=sharing

The texts are partly real, partly dummies with a realistic length. Please use them twice to have a realistic amount of items.

The definitive texts will be filled in by Markus and me as soon as available (we work on it). Definitive selected pictures follow as soon as possible.

Pictures in the document are definitively chosen. In the word document you find only a screenshot of them. The idea is, that Radim chooses a suitable detail in the representation that is online (links). The idea is to choose a close detail out of the map. Differences between Kupferdruck and Lithografie should be visible. As far as possible pictures should have a similar degree of detail but for Kartenwerke this is of evidently not possible.

The Layout should be prepared for 15 – 20 items. We need an extensible concept.

Notes (from Petr):
On the front page will be displayed 5 random maps selected from these.

Each map should have it's own website - with large image and text next to it and layout similar to the one designed for "Services".
There must be a way how to navigate between the maps / thumbnails on the detail page - ideally a clickable slider of the thumbnails on the top of the page.

**Comment by klokan** [comment]
@JackuB On the front page will be displayed 5 random maps selected from these.

**Comment by klokan** [comment]
The detail page of a map is going to look similar to the Services (#10). The thumbnails on the bottom should be scrollable.

**Comment by klokan** [comment]
@radimkacer We need to prepare the thumbnails and previews.

**Comment by klokan** [comment]
From Susanne: The missing articles for the 'worth knowing about maps' pages are at the moment edited and finished by Markus Oehrli. I will ask him to send the data directly to you.

**Comment by radimkacer** [comment]
Here are images for thumbnails.. 
![kartenportal-digitalekarten](https://f.cloud.github.com/assets/3808072/642752/ef1a8b66-d365-11e2-8d67-c07ca43f9c36.png)
![kartenportal-holzschnitt](https://f.cloud.github.com/assets/3808072/642753/ef342328-d365-11e2-9d23-92bb37e7aded.png)
![kartenportal-kartenwerk](https://f.cloud.github.com/assets/3808072/642754/ef4b6b6e-d365-11e2-98bb-c25d3fb0c906.png)
![kartenportal-offsetdruck](https://f.cloud.github.com/assets/3808072/642755/ef4f1e44-d365-11e2-918d-2c8d8e235140.png)
![kartenportal-kupferstich](https://f.cloud.github.com/assets/3808072/642756/ef54439c-d365-11e2-856f-9832d6e59eff.png)
![kartenportal-manuskriptkarten](https://f.cloud.github.com/assets/3808072/642757/ef541dae-d365-11e2-841b-3e750ff917ec.png)
![kartenportal-panorama](https://f.cloud.github.com/assets/3808072/642758/ef53e4b0-d365-11e2-9eae-2b4f5e70d8da.png)
![kartenportal-profil](https://f.cloud.github.com/assets/3808072/642759/ef598eb0-d365-11e2-8faf-6419139abcf3.png)

**Comment by klokan** [comment]
TODO:
- Fix displaying of the list - so that selected item stays at the place - as in the mockup for the layout
- Ensure the switching between languages runs well and there are correct URLs

**Comment by JackuB** [comment]
Looks like there is some problem with updating again kartenportal.klokantech.com/githubwebhook.php

**Comment by klokan** [comment]
I will fix it today after 15:00. Going to be off line now.

On Sunday, August 11, 2013, Jakub Mikulas wrote:

> Looks like there is some problem with updating again
> kartenportal.klokantech.com/githubwebhook.php
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/klokantech/kartenportal-tickets/issues/5#issuecomment-22450487
> .

## 

Petr Pridal
(managing director)

Klokan Technologies GmbH
Bahnhofstrasse 9, Baar 6340, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/
