### ISSUE TITLE
Update of the font with icons

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#57]
We need to add to the existing font the vector icons:
- Print
- Permalink
- Announce
- Map (photo)
- Event (calendar)
- Triangle pointing to the right (we have one pointing right)

Did I miss something what should be used on the web, and is not yet available?

**Comment by klokan** [comment]
Two more symbols are required:
- Unlocked lock
- Locked lock

**Comment by klokan** [comment]
New icon for external link - now it is an birmap icon.

**Comment by radimkacer** [comment]
icons for profile and dashboard ...

**Comment by klokan** [comment]
The latest font is at:
https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWST1k4OFhoRUcwbGM/edit
