### ISSUE TITLE
Administration look&feel

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#63]
We need to restyle the administration interface for the libraries. This ticket contains all related work.
### Kartenportal logo for the login page:

For the login page we need Kartenportal logo replacing these icons:
http://kartenportal.klokantech.com/wp-admin/images/wordpress-logo-2x.png
http://kartenportal.klokantech.com/wp-admin/images/wordpress-logo.png
that means - two PNGs:
- admin-kartenportal-logo-2x.png - 548×126px
- admin-kartenportal-logo.png  - 274x63px
### Icons for the individual menu sections in sizes: 45x45px and 90x90px
- admin-dashboard-2x.png - 90x90px
- admin-dashboard.png - 45x45px
- admin-events-2x.png - 90x90px
- admin-events.png - 45x45px
- admin-announcements-2x.png - 90x90px
- admin-announcements.png - 45x45px
- admin-maps-2x.png - 90x90px
- admin-maps.png - 45x45px
- admin-profile-2x.png - 90x90px
- admin-profile.png - 45x45px
### The admin dashboard

After the libraries logs into administration we should show them a guidance and attractive dashboard.
On the dashboard should be the name of a library.
We need to present a link to create new: Announcement, Event, Featured map.
Under should be also link to update profile and link to Instruction page, formulated as:

"In the [Profile section] it is possible to update information about your library collections, your password and address."
"For more detailed step by step guides please read [Instructions]."
### Order of the items in the menu

The menus in administration on the left should be with titles in order:
Announcements, Events, Featured Maps (or Maps if there is no space).

**Comment by radimkacer** [comment]
![admin-kartenportal-logo](https://f.cloud.github.com/assets/3808072/583794/2bbb0fe2-c901-11e2-8768-5d8b71ef55e6.png)
![admin-kartenportal-logo-2x](https://f.cloud.github.com/assets/3808072/583795/2bd31682-c901-11e2-91a4-8314c5608c34.png)

**Comment by klokan** [comment]
The icons for individual sections in administration are available at:
https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWSYVJHSUZyVlZPbTg/edit

**Comment by klokan** [comment]
Mockup for the dashboard of the administration section is:

![admin-dashboard-mockup](https://f.cloud.github.com/assets/59284/584280/f647c7e0-c911-11e2-8041-542f946d4fd5.png)

**Comment by klokan** [comment]
@JackuB design is ready - please start to work on the integration with WP.
