### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#64]
The mockups for how the news (blog) page should look like are bellow.

Notes:
- The calendar in sidebar contains links to blog post by their date of publishing. Highlighted are also links to posts by dates of events (highlighted with blue background).
- The gray text in the search box background is: "Search posts".
- The "Featured Image" appears on top of the page, in case it is available.
- Click on the type of the posts (Announcements, etc.) in sidebar are filtering the list on the left.
- If a single post is displayed, the relevant type of the post in the sidebar is highlighted.
- The gray boxes on the left of from the sidebar should not be there.
- The responsive design displays first the content of the page and then the sidebar - expanded to fill the width.
- Sidebar has always links to RSS and ICS feeds
- Title "Neuikeiten" or "News" - should be probably 23px size - to be the same as "Kartensamlungen" on another page. In the mockups it is slightly bigger now.

Mockups:
![kartenportal-webdesign5-v3 copy 29](https://f.cloud.github.com/assets/59284/585963/e6dcc136-c941-11e2-9ef5-b90358b9220f.jpg)

![kartenportal-webdesign5-v3 copy 30](https://f.cloud.github.com/assets/59284/585964/f4a47a84-c941-11e2-998d-8bce475dcac3.jpg)

![kartenportal-webdesign5-v3 copy 44](https://f.cloud.github.com/assets/59284/586124/b47d8eb0-c945-11e2-9bf6-51aa47ccfdb4.jpg)

**Comment by radimkacer** [comment]
![kartenportal-webdesign-blog04](https://f.cloud.github.com/assets/3808072/590627/f1f38328-c9e8-11e2-93de-2fec9eb1d97d.jpg)

**Comment by klokan** [comment]
TODO:
Sidebar: Tag cloud, Archives for years
Detail of an event: displaying the dates more visually.

**Comment by JackuB** [comment]
I tried to create yearly archive across different post types (maps, announcements, events), but it can't be done.

I already removed archive part from sidebar

**Comment by JackuB** [comment]
Ad email question: Consolidated yearly/monthly/daily archive of posts can't be done with current setup - as each post type (custom_post_type) have it's own taxonomy/archives/paging. There are APIs for working with such setup (we are using them on blog), but there is no _automatic_ way to generate archives (archive url, archive paging etc.) for multiple post_types. 
Ofc, there are ways to generate archives _almost_ manually, but AFAIK yearly archive is really low priority on this project, so I suggest to skip it.
