### ISSUE TITLE
Exclude maps of extra-terrestrial bodies

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#65]
Adjust the importing script in order to exclude maps of extra-terrestrial bodies. These maps will be coded by the libraries in MARC field 034 $z. The subfield will contain the name of the extra-terrestrial body. Any record with 034 $z should be excluded from Geosearch.

Background info: 034 $z is a new subfield currently being implemented in the cataloguing rules. There are no records yet coded in 034 $z.

**Comment by klokan** [comment]
Server side issue. Scheduled under internal ticket: https://github.com/klokan/maprank-server/issues/18
