### ISSUE TITLE
Time filter sliders

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#66]
When the time filter sliders are close together, the left one vanishes behind the right one. Both should be readable at any time, even when they are close together (e.g. 5 or 10 years difference). A possible solution would be that the text boxes are right-aligned (earlier year) and left-aligned (later year) respectively.

**Comment by zb-markus** [comment]
We suggest to keep it simple, i.e. to show only markings for the centuries. Mockup by radimkacer and proposal by zb-markus sent by e-mail to klokan for upload here.

**Comment by klokan** [comment]
![time_sliders_zb](https://f.cloud.github.com/assets/59284/653432/8c69c942-d4d6-11e2-8918-917bc6617e97.gif)

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
