### ISSUE TITLE
Multiple 034 fields plus scale filter

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#67]
Records with multiple 034 fields are shown at the wrong place when scale filter is set. Example:
http://dev.klokantech.com/kartenportal/#bbox=52.93763754999998,24.026407034914932,136.25243703714,72.23209480543836&q=&date_from=1960&date_to=1970&scale_from=500000&scale_to=500000&libraries=

Among the records found is:
http://dev.klokantech.com/kartenportal/#id=130129860#1

This record contains two 034 fields. It is retrieved because of the scale in the first 034. It is also retreived because of the bounding-box in the second 034. But the combination of $b from one 034 and $d-g from another 034 make no sense. Avoid mixing multiple 034.

**Comment by klokan** [comment]
Work has started.
