### ISSUE TITLE
Sorting of records with identical bounding-boxes

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#68]
When there are many records with _identical_ bounding-boxes and scales the sorting in the Trefferliste seems to be accidental and needs to be refined. 

Example:
http://search.kartenportal.ch/#bbox=73.49941360000002,18.153521599999994,134.77280955959213,53.56097399999999&q=atlas&date_from=1950&date_to=9999&scale_from=&scale_to=&libraries=

The first 30 or so records are atlases with the same bounding-box (and empty scale field). These records shoud be sorted according to the year in descending order.

**Comment by klokan** [comment]
Server side issue. Scheduled under https://github.com/klokan/maprank-server/issues/19
