### ISSUE TITLE
Administration / Map collections field names & translations

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#69]
You receive the nomenclature for the fields in the profile section by e-mail (Word).

**Comment by ethbib-susanne** [comment]
First column nomenclature. Seccond column Example. Ideally the example is displayed after every input field.

**Comment by klokan** [comment]
The file is on Intranet at:
https://docs.google.com/a/klokantech.com/document/d/1y1YU2R2lgKHtj-ot9rfQGtojNhBJuJZ22uzCZE0NMeU/edit

**Comment by ethbib-susanne** [comment]
The example texts should appear next to the corresponding input field.

**Comment by ethbib-susanne** [comment]
The logins should be standardised. The e-mail-adress would be ideal.

**Comment by klokan** [comment]
@ethbib-susanne PLEASE, CREATE NEW TICKETS FOR YOUR NEW REQUESTS AND DO NOT COMBINE THE TASKS TOGETHER. Unrelated requests moved to #95.

Email addresses should be usable as logins already.

**Comment by klokan** [comment]
Done.
