### ISSUE TITLE
Library filter and Trefferliste update

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#71]
When the library filter is opened and the selection changed by the user, occasionally the Trefferliste does not update immediately. Usually a second change in the library filter forces the Trefferliste to update correctly. The non-update effect has been seen especially when the Geosearch has been opened the first time and the change of the library is the first action done. Also, when the user goes to another web site and comes back to Geosearch, the described effect can happen. Seen in IE8 browser.

The Trefferliste should in any case be updated immediately after the user changes the library to be searched.

**Comment by klokan** [comment]
Work started. Internal note: CHANGE vs CLICK event in IE8.

**Comment by klokan** [comment]
Fixed.
