### ISSUE TITLE
Red footprint of records in search map is white

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#72]
It occasionally happens that the red footprint rectangle of a record has white background instead of the half-transparent map background. This effect has been seen after adding and deleting attributes filters and moving heavily around on the map. Unfortunately no real pattern has been found. The effect is difficult to reproduce, sometimes it occurs and sometimes it does not, even with identical user behaviour. It is probably IE8 specific.

The red footprint rectangle should always display the half-transparent map background.

**Comment by klokan** [comment]
We have not managed to reproduce it. Provide an exact description how to reproduce the error, please.

**Comment by zb-markus** [comment]
I did find a pattern to reproduce it:
- go to Geneva, Basel, Bern or Zurich or indeed any other place in Switzerland
- open Library filter
- choose the last library (Uni Basel - Slavisches Seminar) -> footprint remains
- then change your mind and choose the next to last library (Uni Basel - Philosophisches Seminar) -> footprint disappears
- again change your mind and choose "All libraries" -> footprint appears with white background

**Comment by zb-markus** [comment]
Another pattern (again in IE8 only) is the following:
- go to a remote place such as a Pacific island http://search.kartenportal.ch/#bbox=-140.0683531101563,-10.706532674698008,-138.1455722065205,-8.647501650048267&q=&date_from=0&date_to=9999&scale_from=&scale_to=&libraries=&map=road
- scroll down the Trefferliste relatively quickly using the mouse wheel
- when one comes to a record that covers the entire screen, the background switches to white
- from that point, all footprints have white background, even when one scrolls up to the beginning of the Trefferliste

**Comment by klokan** [comment]
Finally fixed. This one was hard.

It is a bug made by Microsoft in implementation of the transparency filter in IE8 which runs out of memory on large elements. We have found and deployed a workaround with partly transparent texture used instead of the native filter.

This has been the last opened ticket of the internal milestone for deploying the updates to http://search.kartenportal.ch/

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
