### ISSUE TITLE
Links to new NEBIS libraries

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#74]
Because of the merger of Univ of Zurich libraries and NEBIS some back links are broken. The libraries are coded in MARC field 949 $b. Those to be corrected have a name beginning with U..., such as UGEOG, USTAR, USTAZ, UBOT, UPHZH, UHS.
Example: http://dev.klokantech.com/kartenportal/#id=130845019

Clicking on a library button in Swssbib http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22130845019%22+IN+%5B4%5D&v=nose&l=de links correctly to NEBIS. An updated library list must therefore be available from Swissbib.

**Comment by klokan** [comment]
This is direct duplicate to #56.

Lets close this ticket when we validate the mentioned links are correctly exposed in the public http://dev.klokantech.com/kartenportal/ installation.

**Comment by klokan** [comment]
This is now correct, check: http://search.kartenportal.ch/#id=130845019
