### ISSUE TITLE
Wrong backlink in record 209128704

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#77]
http://search.kartenportal.ch/#id=209128704 is a mystery: Clicking on the "Catalog" button(s) will always go to the holdings of the record that was selected immediately before selecting this record or that can be found above or below this record in Trefferliste. The correct holdings of ETH library are never displayed. See NEBIS http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=007606153 (last update of catalog record at 10 June 2013) and see Swissbib record 209128704. No other records with a similarly wrong backlinks appeared so far, but please analyse whether there is a general problem in the importing script or elsewhere.

**Comment by klokan** [comment]
@keosak Can you please verify this by reviewing the importing script and relevant OAI-PHM record?

The 'catalog' record is completely missing, there should be a link to NEBIS / ETH Zurich.

This is the link to SwissBib: http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22209128704%22
Our JSON is visible at: http://api.kartenportal.ch/cgi-bin/maprank.fcgi?id=209128704

**Comment by keosak** [comment]
The record didn't have the catalog field set in OAI-PMH, so it wasn't in the MapRank response either. Now after a database update it has both. There are however 2657 other records with the catalog field missing at this time.

**Comment by klokan** [comment]
Such records must be fixed in SwissBib OAI-PMH records. Kartenportal simply do not have available the catalog information from SwissBib at this point for similar records.

Once the records are fixed in SwissBib the next day they should be correct in Kartenportal too.

@zb-markus May we close this ticket?

**Comment by zb-markus** [comment]
I do not really understand because there _is_ catalog information in the Swissbib record at http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22209128704%22. What has to be fixed on the Swissbib side? Did you already notified Swissbib about your opinion?

**Comment by klokan** [comment]
Here is a sample record:

http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22130129852%22+IN+%5B4%5D&v=nose&l=de

which (now) does not have the catalog information in SwissBib, eg. field 949$b or $e is missing in MARC.
The same MARC we are retrieving via OAI-PMH and indexing in Kartenportal.
There are around 2000 of such records in the complete OAI-PMH dump.
In this moment such record does not display link to catalog: http://search.kartenportal.ch/#id=130129852
Once SwissBib is fixed the links will appear the next day (which is the case for the record you mentioned originally).

No, we have not notified SwissBib about the issue. Could you do that please, @zb-markus?

**Comment by klokan** [comment]
Note: we will fix the client, to ensure the link from the previously visited catalog record is not shown in case the catalog information is missing completely. This happens now - and that is what you are describing as a mystery.

**Comment by keosak** [comment]
The list of records with missing 949 catalog field is at: https://gist.github.com/keosak/6172309.

**Comment by zb-markus** [comment]
I have checked some of the records out of the list provided by keosak. Indeed, these records mainly lack field 949. Field 956 seems to have been vanished since we wrote the specification F.20. 

However, the library information needed is in fields 852 (for whatever reason). For example record 001333259: 
- 852 4- $B NEBIS $b Z04 $a Verschiedene Signaturen, siehe Bandübersicht
- 852 4- $B IDSLU $b LUZHB $j KA 206 $a Bd. 1, 5-6, 11, 16-17, 28, 33-34, 37

Handle 852 exactly as you handle 949, i.e. 
- 852 $B = 949 $B
- 852 $b = 949 $b
- 852 $j = 949 $j

**Comment by klokan** [comment]
Implemented. We are running the OAI harvesting again to reindex the whole database and test this.

**Comment by keosak** [comment]
Finished, there are still 599 records missing both 949 and 852 catalog entries.
This list is at: https://gist.github.com/keosak/6192215.

**Comment by zb-markus** [comment]
Tested and accpeted. Swissbib will be informed by us.

**Comment by klokan** [comment]
Reopening. Before we close this ticket on our side I have to improve the JavaScript client so it correctly displays the fact that the record has no links to catalogs. In this moment it may show "mysterious" links to previously displayed records.

**Comment by zb-markus** [comment]
Or rather, that records without any backlinks are not displayed at all. We think that records without links are useless for users and should therefore not appear within Geoseach.

**Comment by klokan** [comment]
Sample record for fixing the JavaScript issue: http://search.kartenportal.ch/#id=045903921

**Comment by petrsloup** [comment]
Done.

**Comment by klokan** [comment]
@zb-markus We have fixed the JavaScript displaying. These records should not be available via OAI-PMH from SwissBib in a first case.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
