### ISSUE TITLE
Record 130161896 does not show up when filters set

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#78]
Record http://search.kartenportal.ch/#id=130161896 is in the system but can not be retrieved. Setting Time filter to past-1520, or setting Attributes filters (either title "situ" or author "Türst"), or setting library filter "ZB Zürich Handschriftenabteilung" does not show this record. A couple of other records will show up, all of them modern facsimiles. The manuscript map 130161896 needs to be found accordingly.

We are aware, however, that Swissbib erroneously merged the NEBIS record describing the manuscript map with another NEBIS record describing modern facsimiles. This does not normally results in the cmplete lost of records within Geosearch.

**Comment by klokan** [comment]
We will check it.

This is what MapRank see for the record http://api.kartenportal.ch/cgi-bin/maprank.fcgi?id=130161896
@keosak Surprisingly, this record is not in the list when filtering only on word "situ" is applied. Manuscripts are in a separate OAI-PMH group - isn't there a bug in the indexing script related to this?

**Comment by keosak** [comment]
The Javascript client sends time filter with each request, but the record in question doesn't have the date property set. The query engine assumes that records without a date cannot be filtered by date and thus rejects them from the result. This seems like the logical behavior to me.

There are three solutions, ordered by preference to me. Either 1) the client will stop sending misleading requests, or 2) we  detect them in the server and throw the ballast options away, or 3) we change the filtering behavior.

**Comment by klokan** [comment]
OK. This is clearly a bug - caused by incorrect communication between the client and server.

Solution we will use:
- The server and indexing of the records is not going to be changed.
- The client is going to be modified - if the filter on timeline is not set (e.g. it is set at Past to Present, in url with #date_from=0&date_to=9999) the client will not send any dtstart and dtend arguments to the server at all.
  This way the filter is going to be disabled correctly and ALL RECORDS, even these without proper date information, will appear, which is expected behaviour.

**Comment by klokan** [comment]
Note: this record contains a pubdate (MARC 260 $c) information. The timeline is filtering only on the date field (mapped from MARC 008 in fields $m $q $s $r) therefore filtering on the timeline for this record cannot run. There are other records with the same title with date field properly set and with a different pubdate.

**Comment by zb-markus** [comment]
The date problem seems to be at Swissbib because they
- merged different original records into a sigle one, which is incorrect
- filled nonsense date information into field 008, although the original library records are correct
  Did you already notified Swissbib about that specific problem?

However, it is also the text filter that did not work. As the record (by the way the oldest map of Switzerland of 1495) is actually available in the Kartenportal under  http://search.kartenportal.ch/#id=130161896, it should at least show up when a title search is performed. It does not, while four other records with the same title (all modern facsimiles) do.

**Comment by petrsloup** [comment]
Client modification done.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
