### ISSUE TITLE
Trefferliste: earlier editions (background)

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#79]
In the Trefferliste we have records with white and grey background. When a record with grey background has "Earlier editions of this map", the opened list should be grey as well in order to "stay connected" with the main record. Currently the list is white n any case, so it looks as if the list belongs to the next title below.

The reverse case is OK, i.e. when the record has white background and the list of earlier editions is white, too

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
