### ISSUE TITLE
Domain KartenPortal.ch: Klokan Technologies GmbH as administrative contact

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#8]
We need the rights to change DNS records to point the domain to the production server.

We may also set the development server to dev.kartenportal.ch for now and locate there the geosearch interface.

**Comment by ethbib-susanne** [comment]
J checked this and we will register Klokan Technologies GmbH as technical contact (there is no administrative contact) a few days before the website is relaunched. For 'political' reasons the holder of the domain is until further notice the EAWAG library. Later it might be transfered to ZB or ETH-Bibliothek. 

https://www.nic.ch/reg/ds03/whois/view-result.html?lid=de#WhoisForm

**Comment by klokan** [comment]
This is now moving forward.

The final domains for the geosearch functionality are going to be configured as http://search.kartenportal.ch/ (English) and http://suche.kartenportal.ch/ (German) and http://rechercher.kartenportal.ch/ (French).

**Comment by klokan** [comment]
@zb-markus Can you please confirm the domains?

**Comment by zb-markus** [comment]
We confirm for Geosearch http://search.kartenportal.ch/ (English) and http://suche.kartenportal.ch/ (German). However, the French address should read http://recherche.kartenportal.ch/ (French). We also intend to provide an Italian version under http://ricerca.kartenportal.ch/ (Italian).

**Comment by klokan** [comment]
Thank you. We will set it up this way.

**Comment by klokan** [comment]
Domains are configured now. The multilingual search interface is still to be deployed.
