### ISSUE TITLE
Scrolling through records when Detailansicht open

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#81]
When the Detailansicht is open and one tries to scroll down through the records with the arrow, the records are shown as expected until one comes to the end of the visible Trefferliste (depending on window size this is for example record #10). The next click on the down arrow does not show the details of record #11 but again those of the top record.

With the same, the button for closing the Deailansicht (x) vanishes.

Seen in Firefox 21.0 and IE 8.0.

**Comment by klokan** [comment]
Acknowledged. Thanks for the report.

**Comment by klokan** [comment]
@zb-markus Please test and validate.
