### ISSUE TITLE
Improved URLs across the whole website

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#84]
We need to improve the URLs and keep them consistent across the whole website - including localisation.
- Main page: /, /en/, /fr/, /it/
- Blog: /blog/, /en/blog/, /fr/blog/,
- Blog post: /events/EVENT-TITLE/ (remove /event/ in the middle).
- Maps gallery: /maps/
- Search in the menu is going to be a link to a third level domain - separately not as static sites in the web. Let's remove the static HTML websites from the repository created for #11.
  Instead the "Kartensuche" and alternatives in the main menu should link to http://search.kartenportal.ch/ (English) http://suche.kartenportal.ch/ (German). http://recherche.kartenportal.ch/ (French). http://ricerca.kartenportal.ch/ (Italian).

**Comment by JackuB** [comment]
✓ Main page: /, /en/, /fr/, /it/
✓ Blog: /blog/, /en/blog/, /fr/blog/,
✓ Blog post: /events/EVENT-TITLE/ (remove /event/ in the middle).
✓ Maps gallery: /maps/
✓ Search in the menu is going to be a link to a third level domain - separately not as static sites in the web. Let's remove the static HTML websites from the repository created for #11. Instead the "Kartensuche" and alternatives in the main menu should link to http://search.kartenportal.ch/ (English) http://suche.kartenportal.ch/ (German). http://recherche.kartenportal.ch/ (French). http://ricerca.kartenportal.ch/ (Italian).

**Comment by klokan** [comment]
It makes probably sense to make the URLs for blog and blog types following:
/blog/ - all blog posts together
/blog/announcements/ - all posts of type annuncement
/blog/events/ - all post of type events
/blog/maps/ - all posts of type featured maps

The links to individual posts in the blog can be then either:
more universal  /blog/[whatever-title-or-id-of-a-post]
or
more specific /blog/events/[whatever-title-or-id-of-a-post] and the same for /blog/announcements/XXX and /blog/maps/XXX
