### ISSUE TITLE
Search with a #place= link problematic

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#85]
We need a permalink for zooming the map to a certain region for a given placename.
This has been implemented as #place= but it does not run perfect yet.

This link is used from the Kartenportal frontpage.

The MapRank query region (rectangle) is not properly set - instead it fills the whole screen:

Example query:
http://search.kartenportal.ch/#place=zurich

**Comment by petrsloup** [comment]
Done.
