### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#86]
1. The logo should be adjusted with the menu items:

![logo](https://f.cloud.github.com/assets/4223790/937577/95e877fe-00df-11e3-80aa-c3194965e240.jpeg)
1. The line below the logo should be less solid. It is to strong and attracts the look to much. 

![logo_line](https://f.cloud.github.com/assets/4223790/937583/5425f44e-00e0-11e3-847f-ce8c3baa567f.jpeg)

**Comment by radimkacer** [comment]
Done on Blog page... same we will make on other pages..
