### ISSUE TITLE
Blog Layout

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#87]
J am not happy with the order of elements of the blog menu and the huge space on top of the blog list. The search function should appear below the most important elements of the blog page which are the title and the filteroptions. 

![blog_layout](https://f.cloud.github.com/assets/4223790/937694/69ebe1d0-00e5-11e3-9dc9-a4f5bae3e27f.jpeg)

**Comment by JackuB** [comment]
Sidebar is now reordered.
