### ISSUE TITLE
Show & sign correctly

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#88]
The & sign should appear correctly, see for example record
http://search.kartenportal.ch/#id=217263348
(title: ... Terræ Firmæ®: Amazonum) and compare with Swissbib: ...  Terræ Firmæ & reg: Amazonum

**Comment by klokan** [comment]
Tests done:

In Kartenportal (http://search.kartenportal.ch/#id=217263348) and in our JSON we are missing space between & and reg:

```
curl "http://klokan.nine.ch/cgi-bin/maprank.fcgi?id=217263348"
```

Original SwissBib (http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22217263348%22+IN+%5B4%5D&v=nose&l=de) and the OAI-PMH request both have the space in between:

```
curl "http://oai.swissbib.ch:20103/oai/?verb=GetRecord&metadataPrefix=m21-xml%2Foai&identifier=217263348"
```

The HTML viewer is interpreting &reg as &reg; (surprisingly for back compatibility). Details: http://stackoverflow.com/questions/15532252/why-is-reg-being-rendered-as-without-the-bounding-semicolon

Solution: we have to fix the OAI importing scripts to ensure the space between is preserved.

**Comment by zb-markus** [comment]
Tested and accepted.
