### ISSUE TITLE
Font-Sizes

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#89]
I am not entirely happy with the font sizes. The concept should be consistent over all pages. Some titles are for my perception to big. Concretely this means:

For the frontpage:
h1 35px ("Karten suchen" -> new 30px
h2 24px ("Veranstaltungen", "Kartensammlung finden") -> 24px
h3 18px ("Wissenswertes ..") -> new 20px
sucheButton  18px ("Suche starten") -> new 16px

Blog page:
("Kartenblog" see new Layout Blog) -> h1 30px
h2 (titles articles) 26px -> 24px
h3 (titels menu) 22.75px -> 20px

Blog article pages:
("Kartenblog" see new Layout Blog) -> h1 30px
h1 35,75px (title article) -> h2 24px
h3 (titels menu) 22.75px -> 20px

Map collections detail page:
h2 29.25px (name map library) -> h1 30px
h3 ("Veranstaltungen", "Neuigkeiten") 22.75px -> 20px

Summarised:
h1 30px
h2 24px
h3 20px

**Comment by ethbib-susanne** [comment]
This section on the front page was bold in a earlier mockup - can you make it bold again?

![intro](https://f.cloud.github.com/assets/4223790/954017/e9d50abe-0407-11e3-8e2c-a492d59f44f4.jpg)

**Comment by klokan** [comment]
We were refining the headers now - please check. These are now according the agreed mockups.

The text on the front page is with intention not bold - this is the way designer suggest it. It looks ugly when bold. But if you request we make it that way.

![screen shot 2013-08-13 at 5 15 14 pm](https://f.cloud.github.com/assets/59284/955501/addd0eca-042b-11e3-9fea-0f93d2b5c5cf.png)

**Comment by ethbib-susanne** [comment]
Maybe this is to strong. Could we find somethin between?

**Comment by klokan** [comment]
The header font sizes are fixed.

The bold is not intended for whole paragraphs. It does look ugly on larger amount of text. We have tried also slightly less strong variant, but it did not help.

**Comment by ethbib-susanne** [comment]
J really don't want to annoy you but this ticket is not closed. Please read my first instructions carefully. They are very clear. 

We don't have the same perception of the header hierachy. Of course the website must be consisent, that means that also the titles of the articles in "Wissenwertes" are h2.

**Comment by ethbib-susanne** [comment]
Then there was a missunterstanding concerning these items in the menu on the left side of the page. The font size should here also be 20 px (h3).

![menu](https://f.cloud.github.com/assets/4223790/993682/a3b52f26-099f-11e3-8a03-b3645a48b57d.jpg)
