### ISSUE TITLE
Fix footer and header

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#9]
Header should support full responsive interaction. Now it is broken.

Footer as well.

Normally the footer should look like:

![footer](https://f.cloud.github.com/assets/59284/405101/4aebdf84-a9b4-11e2-9cea-4dd871b01b6b.jpg)

**Comment by JackuB** [comment]
Done

**Comment by klokan** [comment]
Thank you. It looks great.

Two small issues: The footer should have Facebook,Twitter,Google+ and "Share" on the left.
In the header the selection of languages should have the same size in the curtain as they have in the upper right corner.

Then please close this ticket.

**Comment by klokan** [comment]
One more small issue - the red line on top of logo in header must be always aligned to the left corner of the content in the page. It is especially visible on the front page - when resizing the block in the front picture does not always align to the header (for example if the page has width 1080px).

**Comment by JackuB** [comment]
What functionality should "Share" have?

We may use this for sharing options - http://sharethis.com/

**Comment by JackuB** [comment]
Ad red line on top: it should be aligned in all resolutions

Ad language select: I made it bigger on purpose - it was prone to missclicks (button was smaller than 40px)

**Comment by klokan** [comment]
Implementation of the Share is available here: http://dev.klokantech.com/klokan/share.html

**Comment by JackuB** [comment]
Done

**Comment by klokan** [comment]
Blog layout is now broken (footer wrong, missing sidebar):
http://kartenportal.klokantech.com/karten-blog/

as well as the header on the detail page (as discussed before):
http://kartenportal.klokantech.com/events/event/another-event/

**Comment by klokan** [comment]
Thank you!

**Comment by klokan** [comment]
Again broken - on the front page. Red line on top of header is not aligned with the image when resizing window.
If possible keep the height of the header constant.

**Comment by ethbib-susanne** [comment]
Please adapt copyright text

OLD: ![copyright](https://f.cloud.github.com/assets/4223790/455043/3620af58-b346-11e2-9282-21dc922f1756.jpeg)

NEW: © 2013 Kartenportal.CH
