### ISSUE TITLE
Trefferliste update after location change

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#90]
When the user changes the location of the base map using the place-name search box or the zoom controls, the Trefferliste should immediately reflect the new location and update. This was the case before ca. 8 August. Seen in IE8 and IE9.

**Comment by klokan** [comment]
Tested and reproduced. This is a bug.

**Comment by petrsloup** [comment]
Done.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepetd.

A similar bug is in the small overview map. Panning there should immediately update the Trefferliste.

**Comment by klokan** [comment]
Done.

**Comment by zb-markus** [comment]
Tested and acepted.
