### ISSUE TITLE
Layout Angebote / Wissenwertes page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#94]
Please leave a bit more space after the paragraph:

![layout angebote](https://f.cloud.github.com/assets/4223790/985014/9bdf39da-08b0-11e3-97db-fac5f80fea03.jpg)

**Comment by ethbib-susanne** [comment]
Please reduce the space between pictures and titles of paragraphs:

![layout angebote2](https://f.cloud.github.com/assets/4223790/985150/a409fc2c-08b4-11e3-9d72-dca480aed063.jpg)

**Comment by klokan** [comment]
Well, the HTML for this layout has not been complete. Now it is according the original mockups.
