### ISSUE TITLE
Administration for libraries - changes

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#95]
Changed requested in the administration interface for the libraries:
- Marked menu items should not appear in the libraries interface:
  ![menu libraries interface](https://f.cloud.github.com/assets/4223790/985252/884b353e-08b7-11e3-9f35-ccdddbc913c9.jpg)

Remove these fields from the profile:
![cd819c5c-08ac-11e3-89d7-077535b83375](https://f.cloud.github.com/assets/59284/985477/42756aaa-08be-11e3-8576-76fa6eebbbdb.jpg)
![d38a66ec-08ac-11e3-806d-ca3bcd1d9f5e](https://f.cloud.github.com/assets/59284/985478/46e0adfc-08be-11e3-81c8-1f0a376631aa.jpg)
![0c2febc0-08ad-11e3-8602-a5d80b514266](https://f.cloud.github.com/assets/59284/985479/49882986-08be-11e3-86be-6cb3f1091df0.jpg)

Note from @klokan: The name of the library should be preserved.

**Comment by ethbib-susanne** [comment]
@klokan moved the note about localisation from this place to #97.

**Comment by ethbib-susanne** [comment]
Remove the following fields from the admin and map libraries interface, they have no meaning for our website:

![laenge breite](https://f.cloud.github.com/assets/4223790/985907/7e40fe4c-08cc-11e3-86cb-7798c33f4a52.jpg)

**Comment by ethbib-susanne** [comment]
Please remove the following features from the map libraries interface:

![permalink](https://f.cloud.github.com/assets/4223790/986804/1d900c8c-08e0-11e3-8cb3-84b4c64df34b.jpg)

![bersetzung](https://f.cloud.github.com/assets/4223790/986802/1198155a-08e0-11e3-844c-f71a7b82ed55.jpg)

**Comment by klokan** [comment]
Advertisement for professional translation is removed.
Länge & Breite removed.

**Comment by klokan** [comment]
@JackuB Please ensure the administrative interface for libraries is also correctly translated. Check the paragraph with translation in the first comment of #97

**Comment by klokan** [comment]
Done
