### ISSUE TITLE
Header menu on kartensuche page

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#96]
Add the complete menu header to the kartensuche page:

![menu kartensuche](https://f.cloud.github.com/assets/4223790/985353/7f103bec-08ba-11e3-8991-4b3e6411b93d.jpg)

**Comment by klokan** [comment]
Implementation notes:
We include static menu in english from http://kartenportal.klokantech.com/en/.
The links will go to pages in domain http://www.kartenportal.ch/XXX (not valid yet).
Switching of languages must be on the right and it will go to thrid level domains as mentioned in #84, e.g. should link to http://search.kartenportal.ch/ (English) http://suche.kartenportal.ch/ (German). http://recherche.kartenportal.ch/ (French). http://ricerca.kartenportal.ch/ (Italian).

**Comment by klokan** [comment]
Done.
