### ISSUE TITLE
Susanne: Translating the web site

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#97]
There are three types of text to be translated:

1) Content

The content itself (posts / sites / ..) is created in multiple languages (in database). It is editable via administration interface by clicking on the "Bearbeiten" or the symbol ![edit_translation](https://f.cloud.github.com/assets/59284/1119655/26ee9cd4-1a7f-11e3-9789-eed06fb8e2bf.png) next to the translation.

For example:
http://kartenportal.klokantech.com/wp-admin/edit.php?post_type=page

All the "Seiten", "Angebote" and "Wissenswertes".
All the "Neuikeiten", "Veranstaltungen", "Karten".

These are natively all in German language. Content alternatives can be then created in other languages.

2) Menu

Menu are in multiple languages defined at:
http://kartenportal.klokantech.com/wp-admin/nav-menus.php
(I think this is already correctly translated)

3) Phrases in the WordPress theme

Next to that all the short texts and phrases encoded in the WordPress theme on the web must be localised native English into the alternative languages, especially German.

There is a localisation interface for "Themes" available for the admin account:
http://kartenportal.klokantech.com/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php&type=themes

The front page is now localizable via the Phrases as well, because of it's complicated layout.

**Comment by klokan** [comment]
@ethbib-susanne You have caused a lot of troubles by editing the PHP source codes in the past and by replacing English phrases with German inconsistently via the 'admin' account. The language of source code is English - and there is a translation system for turning the English phrases to other languages. Your changes also broke our automatic deployment system in the past...

We have to revert your edits now, otherwise the translation of the website will have on the input a mixture of English and German.

**Comment by klokan** [comment]
These are the custom fields - and their Labels. It can't be translated with the translation system - it must be done directly:
http://kartenportal.klokantech.com/wp-admin/edit.php?post_type=acf
Be extremely careful - no deleting, no restructuring, no change of names, only translating the Labels - if you really want to do that yourself.

And you are hacking the PHP code again and again, and breaking our deployment system.

**Comment by ethbib-susanne** [comment]
The fields names are translated now, but the translated titles are not visible:

![librar_details](https://f.cloud.github.com/assets/4223790/1147831/ffbb2b06-1eb0-11e3-8c0e-62c08ba42a3a.jpg)

http://kartenportal.klokantech.com/library/E01/

**Comment by ethbib-susanne** [comment]
Where can J translate these terms and texts:

![welcome](https://f.cloud.github.com/assets/4223790/1148539/cf706b36-1ec5-11e3-84b6-d46c0c5fdc6f.jpg)

**Comment by ethbib-susanne** [comment]
The text of the tab is not dynamic and can't be translated in the Localization Interface.  It should be 'news' in English and translated in the other three languages. The same is true for 'events' and 'map portraits'.
![text_tab](https://f.cloud.github.com/assets/4223790/1156396/51e0d2ac-1f86-11e3-82ab-1aac8a4c25f9.jpg)

The best would be to use the titles from "Seiten" as the HEAD TITLE probably?

**Comment by JackuB** [comment]
> The fields names are translated now, but the translated titles are not visible visible

Fields names can now be translated same way as other strings in Localization Interface.

---

> Where can J translate these terms and texts:

These texts are being injected into admin area, thus they need to be translated separately http://kartenportal.klokantech.com/wp-admin/tools.php?page=codestyling-localization/codestyling-localization.php under plugin called "Sweet Custom Dashboard"

---

> The text of the tab is not dynamic and can't be translated in the Localization Interface.

Text is now part of Localization Interface. And sidebar title is changing dynamically now. (e.g. here: http://kartenportal.klokantech.com/blog/announcements/ )

**Comment by klokan** [comment]
Closing this ticket. The requested tasks are finished and questions answered.

**Comment by ethbib-susanne** [comment]
Where can J translate these terms and texts mentionned in the ticket dated 15 days ago?

**Comment by klokan** [comment]
Answered above already. The library admin area has a separate ticket #107 already.
