### ISSUE TITLE
Layout events

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#98]
Events should have the same layout as 'news' and 'featured map'. Instead of the author name and publication date the time period of the event should be displayed:

![event](https://f.cloud.github.com/assets/4223790/986681/0ca9c00e-08de-11e3-86d8-bc6b1b68151d.jpg)

**Comment by ethbib-susanne** [comment]
Display of the adress of the event and link to the google site map in the detail view would be usefull. Otherwise there is no need to record these informations it in the libraries interface.

**Comment by radimkacer** [comment]
Here is solution for Blog list (events) and detail page events... 

![screen shot 2013-08-22 at 12 49 54 pm](https://f.cloud.github.com/assets/3808072/1008073/0b5aece0-0b19-11e3-9530-c2c7c13fdb27.png)
![screen shot 2013-08-22 at 12 47 40 pm](https://f.cloud.github.com/assets/3808072/1008075/103e9f54-0b19-11e3-9e6f-8810f274958b.png)

@ethbib-susanne Can you please comment?

**Comment by ethbib-susanne** [comment]
J suggest this order of elements:

![layout](https://f.cloud.github.com/assets/4223790/1025797/bf34c9f0-0e4f-11e3-8a79-fe5150845999.jpg)

**Comment by ethbib-susanne** [comment]
The map doesn't have to be displayed - there can be a link in the adress section directs the user to the place in google maps.

**Comment by radimkacer** [comment]
![kartenportal-webdesign-event](https://f.cloud.github.com/assets/3808072/1128677/c0cd6c10-1b72-11e3-981f-5872b6142f8a.jpg)

**Comment by ethbib-susanne** [comment]
Perfect!

**Comment by JackuB** [comment]
Updated

**Comment by klokan** [comment]
On the top there should be without any bold formatting:

`Event - [date] - [place]`

if there is range of dates then it is:

`Event - from [date-from] to [date-to] - [name-of-the-place]`

Where "Event" and "from", "to" are translatable strings.

for example:

"Veranstalltung - vom 25 July 2013 bis 27 July 2013 - Gletschergarten"

Bellow is on the page there should be in all languages this:

Later on the bottom should be:

`Venue: [address-of-the-place] (See on a map)`

for example:

"Veranstaltungsort: Nadelberg 6, 4051 Basel (Karte anzeigen)"

(now this block is only in German - look at http://kartenportal.klokantech.com/en/blog/event/im-hafen-fahre-ich-zur-see-sebastian-munster-und-die-welt/).

**Comment by JackuB** [comment]
Just update on this ticket:
I see it now - it's nontrivial change directly linked to #137

**Comment by klokan** [comment]
Great! On the http://kartenportal.klokantech.com/blog/ page there is missing the "to". If it is problematic to write it there then keep just "from", but do not show "to" and empty space after, please.

**Comment by JackuB** [comment]
Corrected.

**Comment by ethbib-susanne** [comment]
J am sorry but this is not exactly what Petr specified 20 day ago:

![veranstaltung 1](https://f.cloud.github.com/assets/4223790/1281345/90ca74e2-2f61-11e3-83e7-ef427def57ac.jpeg)

should have the format:

Veranstaltung - Juni 27, 2013 bis September 27, 2013 - Gletschergarten

"Gletschergarten" is the name of the place, your implementation uses the adress of the place, which is wrong (see specification). 

Please remove "Von" (this was not specified) because it doesn't look well with the format of the date (there is no German format available) -> J guess J can do this myself setting "" instead of "From" in the localisation interface?

![veranstaltung 2](https://f.cloud.github.com/assets/4223790/1281376/3c9c84b8-2f62-11e3-9ace-34d9100029cf.jpeg)

should have the format:
Veranstaltungsort: Nadelberg 6, 4051 Basel (Karte anzeigen)

Please use ':' insteat of '-' (see specification)

**Comment by ethbib-susanne** [comment]
Is it possible to show this also on the complete list of all posts?

**Comment by ethbib-susanne** [comment]
The two lines should have the same color as the text.

**Comment by klokan** [comment]
Removed "From" and changed the color of the text in the detail window.
Fixed displaying of the venue name in the first list.
The venue address in the second list uses ":" instead of "-" after title.

The list in archive is displaying venue name now and range of dates.

It is not clear what you mean with "this" what should be shown on the complete list of all posts. Please clarify.

**Comment by ethbib-susanne** [comment]
Please remove time, there should onlly be displayed the date (without time).

Veranstaltung -  Juni 10, 2013 bis Februar 23, 2014 - focus Terra

'This' means that there should be displayed

Veranstaltung -  Juni 10, 2013 bis Februar 23, 2014 - focus Terra

instead of

Veranstaltung -  Juni 10, 2013 10:00  - focusTerra

---

Von: Petr Pridal [notifications@github.com]
Gesendet: Donnerstag, 10. Oktober 2013 02:56
An: klokantech/kartenportal-tickets
Cc: Zollinger Susanne
Betreff: Re: [kartenportal-tickets] Layout events (#98)

Removed "From" and changed the color of the text in the detail window.
Fixed displaying of the venue name in the first list.
The venue address in the second list uses ":" instead of "-" after title.

The list in archive is displaying venue name now and range of dates.

It is not clear what you mean with "this" what should be shown on the complete list of all posts. Please clarify.

**Comment by JackuB** [comment]
@ethbib-susanne time is not shown for all-day events, but only in case of event with defined time.

Should we really remove time?

![image](https://f.cloud.github.com/assets/1788727/1322600/117c0d80-343a-11e3-82ed-9fa61eca6138.png)

**Comment by klokan** [comment]
@JackuB Could you please add the "to" date to the list of all posts in the blog?

@ethbib-susanne We need your feedback regarding the deleting of the support of time. If this should be really done it must be done also in the administration - and it is a new request.
