### ISSUE TITLE
Overview map: omit blue rectangle

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#99]
In the small overview map (bottom left) there are two rectangles shown, a blue and a red one. Users become confused about the blue rectangle because this has no corresponding rectangle in the main map unless one pans that map. 

We think that the blue rectangle should only be shown in the overview map when it is also shown in the main map, i.e. when panning the map.

**Comment by klokan** [comment]
Done.

**Comment by zb-markus** [comment]
Tested and accepted.
